#!/usr/bin/env python3
"""Emit the monster vertical-alignment table from original-src
monster_align.dat.

Port-time tooling (NOT a build/CI dependency). monster_align.dat is the raw
256-byte table (ROM EC/E800; label MonsterAlign at the incbin site,
btlgfx_main.asm:48910-48916): one vertical-alignment byte per monster,
values strictly 0-4, named by the upstream comment block
(btlgfx_main.asm:2824-2829): 0 ceiling, 1 ground, 2 buried, 3 floating,
4 flying. Both consumers are colosseum-specific and index the table with an
8-bit monster id (btlgfx_main.asm:2872-2883, menu/colosseum.asm:555-564) —
monsters 256-383 have no alignment row, and that absence is contract. This
script reads the .dat straight off disk and emits:

  * src/data/generated/monster_align_data.inc — one designated-initializer
    MonsterAlignEntry row per monster (256 rows), identity as the MonsterId
    enumerator field and the value as its MonsterVerticalAlignment
    enumerator; the kMonsterAlignments array #includes it.
  * tests/fixtures/monster_align_expected.h — the same 256 bytes with
    decimal identity (the ground-truth byte contract) for a full-corpus
    equivalence test.

Identity names resolve against original-src/include/const.inc (MONSTER).

Structural guarantees, hard-errored at emit time:
  * the .dat is exactly 256 bytes (any other length is the wrong artifact);
  * every byte is 0..4 (a value outside the named alignment space is an
    escalation, not a guess);
  * every record index has a MONSTER name, and the MONSTER space is exactly
    384 ids (the table's 256 bound is the consumers' 8-bit index).

Python 3 standard library only; targets 3.9+.

Usage:
    parse_monster_align.py --source-root PATH --inc-out FILE --fixture-out FILE
    (Pass --check-only to validate + assert without writing files.)
"""

from __future__ import annotations

import argparse
import os
import sys

import common
import parse_const_enums as pce
from common import ParseError

RECORD_COUNT = 256
MONSTER_COUNT = 384

# Value -> MonsterVerticalAlignment enumerator (the upstream comment block's
# own names, btlgfx_main.asm:2824-2829; mirrors
# include/ostinato/monster_vertical_alignment.h).
_ALIGNMENT_NAMES = ("CEILING", "GROUND", "BURIED", "FLOATING", "FLYING")


class Symbols(object):
    """The const.inc MONSTER enum the identity names resolve against."""

    def __init__(self, const_inc):
        self.parsed = common.parse_ca65_constants(const_inc,
                                                  skip_body_enums=pce.SKIP)
        if self.parsed.enum("MONSTER") is None:
            raise ParseError(const_inc, 0,
                             "expected enum 'MONSTER' not found")
        # First declaration wins (trailing aliases never shadow the primary).
        self.monster_names = {}
        for m in self.parsed.enum("MONSTER").members:
            self.monster_names.setdefault(m.value, m.name)
        if max(self.monster_names) != MONSTER_COUNT - 1:
            raise ParseError(const_inc, 0,
                             "MONSTER max id {} != {} (index-space mismatch)"
                             .format(max(self.monster_names),
                                     MONSTER_COUNT - 1))


def read_values(dat_path):
    with open(dat_path, "rb") as fh:
        data = fh.read()
    if len(data) != RECORD_COUNT:
        raise ParseError(dat_path, 0,
                         "{} bytes, expected {} (one per 8-bit monster id — "
                         "wrong artifact)".format(len(data), RECORD_COUNT))
    for index, value in enumerate(data):
        if value >= len(_ALIGNMENT_NAMES):
            raise ParseError(dat_path, 0,
                             "monster {} alignment byte {:#04x} outside the "
                             "named 0..4 space — escalate, never guess"
                             .format(index, value))
    return list(data)


# --- rendering -------------------------------------------------------------

_HEADER_COMMON = (
    "// AUTO-GENERATED by tools/asm_parser/parse_monster_align.py\n"
    "// Source: src/btlgfx/monster_align.dat (MonsterAlign, ROM EC/E800,\n"
    "//         256 bytes — one vertical-alignment value per monster;\n"
    "//         incbin at btlgfx_main.asm:48910-48916, value names from the\n"
    "//         comment block at btlgfx_main.asm:2824-2829)\n"
    "// Source: include/const.inc (MONSTER values)\n"
    "// (original-src pinned at 1ea47b5)\n"
    "// DO NOT EDIT BY HAND — regenerate via:\n"
    "//   python3 tools/asm_parser/parse_monster_align.py \\\n"
    "//       --source-root  original-src \\\n"
    "//       --inc-out      src/data/generated/monster_align_data.inc \\\n"
    "//       --fixture-out  tests/fixtures/monster_align_expected.h\n"
    "\n"
)


def render_inc(values, symbols):
    lines = [_HEADER_COMMON,
             "// MonsterAlignEntry rows in MONSTER index order ($000..$0FF),\n"
             "// one row per monster, #included inside the\n"
             "// kMonsterAlignments array in src/data/monster_align.cpp. The\n"
             "// table covers monsters 0-255 only (both consumers index it\n"
             "// 8-bit; monsters 256-383 have no alignment row — that\n"
             "// absence is contract). Each row's identity is its .id field\n"
             "// — the MonsterId enumerator; a compile-time assert verifies\n"
             "// id == position. .alignment is the byte's\n"
             "// MonsterVerticalAlignment enumerator.\n\n"]
    name_width = max(len(symbols.monster_names[i]) for i in range(len(values)))
    for index, value in enumerate(values):
        name = symbols.monster_names[index]
        lines.append("    {{ .id = MonsterId::{},{} .alignment = "
                     "MonsterVerticalAlignment::{} }},\n".format(
                         name, " " * (name_width - len(name)),
                         _ALIGNMENT_NAMES[value]))
    return "".join(lines)


def render_fixture(values):
    lines = [_HEADER_COMMON,
             "// Test fixture for tests/test_monster_tables.cpp — the\n"
             "// ground-truth copy of the table (.id decimal identity,\n"
             "// .alignment raw ROM byte). The full-corpus test asserts\n"
             "// kMonsterAlignments matches this array entry by entry, so a\n"
             "// hand edit or re-emit drift in either file fails loudly.\n"
             "\n"
             "#pragma once\n"
             "\n"
             "#include <array>\n"
             "#include <cstdint>\n"
             "\n"
             "namespace ostinato::test {\n"
             "\n"
             "// Mirrors ostinato::MonsterAlignEntry\n"
             "// (src/data/monster_align.h) without depending on it.\n"
             "struct ExpectedMonsterAlignEntry {\n"
             "    std::uint16_t id;\n"
             "    std::uint8_t alignment;\n"
             "};\n"
             "\n",
             "inline constexpr std::array<ExpectedMonsterAlignEntry, {}> "
             "kExpectedMonsterAlignEntries = {{{{  // ROM MonsterAlign\n"
             .format(len(values))]
    for index, value in enumerate(values):
        lines.append("    {{ .id = {:>3}, .alignment = {} }},\n"
                     .format(index, value))
    lines.append("}};\n\n}  // namespace ostinato::test\n")
    return "".join(lines)


# --- driver ----------------------------------------------------------------

def run(dat_path, const_inc, inc_out, fixture_out, check_only=False):
    symbols = Symbols(const_inc)
    values = read_values(dat_path)

    if check_only:
        print("OK: {} alignment bytes; all in the named 0..4 space."
              .format(len(values)))
        return 0

    _write(inc_out, render_inc(values, symbols))
    _write(fixture_out, render_fixture(values))
    print("Emitted {} rows -> {}".format(len(values), inc_out))
    print("Emitted fixture -> {}".format(fixture_out))
    return 0


def _write(path, text):
    directory = os.path.dirname(path)
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source-root",
                    help="disassembly root (monster_align.dat + const.inc "
                         "resolved under it)")
    ap.add_argument("--align-dat", help="path to monster_align.dat")
    ap.add_argument("--const-inc", help="path to const.inc")
    ap.add_argument("--inc-out",
                    default="src/data/generated/monster_align_data.inc",
                    help="output path for the MonsterAlignEntry rows")
    ap.add_argument("--fixture-out",
                    default="tests/fixtures/monster_align_expected.h",
                    help="output path for the raw-byte fixture")
    ap.add_argument("--check-only", action="store_true",
                    help="validate + assert without writing files")
    args = ap.parse_args(argv)

    dat_path = args.align_dat
    const_inc = args.const_inc
    if args.source_root:
        if not dat_path:
            dat_path = os.path.join(args.source_root, "src", "btlgfx",
                                    "monster_align.dat")
        if not const_inc:
            const_inc = os.path.join(args.source_root, "include", "const.inc")
    if not dat_path or not const_inc:
        ap.error("provide --source-root, or both --align-dat and --const-inc")
    try:
        return run(dat_path, const_inc, args.inc_out, args.fixture_out,
                   check_only=args.check_only)
    except ParseError as exc:
        sys.stderr.write("PARSE ERROR: {}\n".format(exc))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
