#!/usr/bin/env python3
"""Emit the 256-byte RNG table from original-src rng_tbl.dat.

Port-time tooling (NOT a build/CI dependency). rng_tbl.dat is raw binary — the
256 byte values ARE the observable; the sound/battle consumers index it. This
script reads the .dat straight off disk and emits:

  * src/data/generated/rng_tbl_data.inc  — the 256 values, #included inside the
    kRngTable std::array initializer.
  * tests/fixtures/rng_tbl_expected.h     — the same 256 values as a raw array
    for a full-corpus equality test.

Structural guarantee: the .dat is exactly 256 bytes; any other length is a hard
error (the RNG table is fixed-size — a short/long file means the wrong artifact).

Python 3 standard library only; targets 3.9+.

Usage:
    parse_rng_tbl.py --source-root PATH --inc-out FILE --fixture-out FILE
    parse_rng_tbl.py --rng-dat PATH --inc-out FILE --fixture-out FILE
    (Pass --check-only to validate without writing files.)
"""

from __future__ import annotations

import argparse
import os
import sys

EXPECTED_LEN = 256


class RngError(Exception):
    pass


def read_table(dat_path):
    with open(dat_path, "rb") as fh:
        data = fh.read()
    if len(data) != EXPECTED_LEN:
        raise RngError("{}: {} bytes, expected {} (RNG table is fixed-size)"
                       .format(dat_path, len(data), EXPECTED_LEN))
    return list(data)


# Emitted-file header: AUTO-GENERATED line, Source lines, upstream pin,
# DO-NOT-EDIT + exact regeneration command, then a consumption paragraph.
_HEADER_COMMON = (
    "// AUTO-GENERATED by tools/asm_parser/parse_rng_tbl.py\n"
    "// Source: src/field/rng_tbl.dat (RNGTbl, ROM c0/fd00; see src/field/rng_tbl.asm)\n"
    "// (original-src pinned at 1ea47b5)\n"
    "// DO NOT EDIT BY HAND — regenerate via:\n"
    "//   python3 tools/asm_parser/parse_rng_tbl.py \\\n"
    "//       --source-root  original-src \\\n"
    "//       --inc-out      src/data/generated/rng_tbl_data.inc \\\n"
    "//       --fixture-out  tests/fixtures/rng_tbl_expected.h\n"
    "\n"
)


def _entry_rows(values, indent="    "):
    return "\n".join(
        "{}{{ .index = {:>3}, .value = 0x{:02X} }},".format(indent, i, b)
        for i, b in enumerate(values))


def render_inc(values):
    return (
        _HEADER_COMMON +
        "// 256 RngTableEntry rows (RNGTbl, ROM c0/fd00). The row's identity\n"
        "// (.index, decimal 0..255) is a typed field, not the array position —\n"
        "// a compile-time assert in src/data/rng_table.h verifies\n"
        "// index == position for every entry. .value is the raw ROM byte at\n"
        "// that index (hex; the byte values ARE the observable, copied\n"
        "// verbatim from the ROM). Included inside the hand-written\n"
        "//   `inline constexpr std::array<RngTableEntry, 256> kRngTable = "
        "{{ #include ... }};`\n"
        "// in src/data/rng_table.h, which backs the rngByte(index) accessor\n"
        "// (the original's RNGTbl+index read).\n"
        "\n"
        + _entry_rows(values) + "\n")


def render_fixture(values):
    return (
        _HEADER_COMMON +
        "// Test fixture for tests/test_rng_table.cpp — the ground-truth copy of\n"
        "// the table in the same self-labeling row shape (.index decimal\n"
        "// identity, .value raw ROM byte). The full-corpus test asserts\n"
        "// kRngTable matches this array entry by entry (index and value), so a\n"
        "// hand edit or re-emit drift in either file fails loudly.\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include <array>\n"
        "#include <cstdint>\n"
        "\n"
        "namespace ostinato::test {\n"
        "\n"
        "// Mirrors ostinato::RngTableEntry (src/data/rng_table.h) without\n"
        "// depending on it.\n"
        "struct ExpectedRngEntry {\n"
        "    std::uint8_t index;\n"
        "    std::uint8_t value;\n"
        "};\n"
        "\n"
        "inline constexpr std::array<ExpectedRngEntry, 256> kRngTblExpected = {{\n"
        + _entry_rows(values) + "\n"
        "}};\n"
        "\n"
        "}  // namespace ostinato::test\n")


def run(rng_dat, inc_out, fixture_out, check_only=False):
    values = read_table(rng_dat)
    if check_only:
        print("OK: {} RNG bytes (first={:#04x}, last={:#04x}).".format(
            len(values), values[0], values[-1]))
        return 0
    _write(inc_out, render_inc(values))
    _write(fixture_out, render_fixture(values))
    print("Emitted {} RNG bytes -> {}".format(len(values), inc_out))
    print("Emitted fixture -> {}".format(fixture_out))
    return 0


def _write(path, text):
    directory = os.path.dirname(path)
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def _resolve(args):
    if args.rng_dat:
        return args.rng_dat
    if args.source_root:
        return os.path.join(args.source_root, "src", "field", "rng_tbl.dat")
    return None


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source-root",
                    help="disassembly root (rng_tbl.dat resolved under it)")
    ap.add_argument("--rng-dat", help="path to rng_tbl.dat")
    ap.add_argument("--inc-out", default="src/data/generated/rng_tbl_data.inc",
                    help="output path for the kRngTable values")
    ap.add_argument("--fixture-out", default="tests/fixtures/rng_tbl_expected.h",
                    help="output path for the raw-byte fixture")
    ap.add_argument("--check-only", action="store_true",
                    help="validate without writing files")
    args = ap.parse_args(argv)

    rng_dat = _resolve(args)
    if not rng_dat:
        ap.error("provide --source-root or --rng-dat")
    try:
        return run(rng_dat, args.inc_out, args.fixture_out, check_only=args.check_only)
    except RngError as exc:
        sys.stderr.write("RNG ERROR: {}\n".format(exc))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
