#!/usr/bin/env python3
"""Emit the per-battle magic-points table from original-src battle_magic_points.dat.

Port-time tooling (NOT a build/CI dependency). battle_magic_points.dat is raw
binary — 512 one-byte magic-point awards (ROM DF/B400), indexed by battle
(formation) index. The consumer-side >= 512 guard (formations past the table
award 0 without reading it) is reward logic that ports with the battle engine;
the data layer ships the 512-entry table. This script reads the .dat straight
off disk and emits:

  * src/data/generated/battle_magic_points_data.inc — the 512 entries,
    #included inside the kBattleMagicPoints std::array initializer.
  * tests/fixtures/battle_magic_points_expected.h — the same 512 entries as a
    raw array for a full-corpus equality test.

Structural guarantee: the .dat is exactly 512 bytes; any other length is a hard
error (the table is fixed-size — a short/long file means the wrong artifact).

Python 3 standard library only; targets 3.9+.

Usage:
    parse_battle_magic_points.py --source-root PATH --inc-out FILE --fixture-out FILE
    parse_battle_magic_points.py --points-dat PATH --inc-out FILE --fixture-out FILE
    (Pass --check-only to validate without writing files.)
"""

from __future__ import annotations

import argparse
import os
import sys

EXPECTED_LEN = 512


class BattleMagicPointsError(Exception):
    pass


def read_table(dat_path):
    with open(dat_path, "rb") as fh:
        data = fh.read()
    if len(data) != EXPECTED_LEN:
        raise BattleMagicPointsError(
            "{}: {} bytes, expected {} (battle magic-points table is "
            "fixed-size)".format(dat_path, len(data), EXPECTED_LEN))
    return list(data)


# Emitted-file header: AUTO-GENERATED line, Source lines, upstream pin,
# DO-NOT-EDIT + exact regeneration command, then a consumption paragraph.
_HEADER_COMMON = (
    "// AUTO-GENERATED by tools/asm_parser/parse_battle_magic_points.py\n"
    "// Source: src/battle/battle_magic_points.dat (BattleMagicPoints,\n"
    "//         ROM DF/B400, 512 x 1 byte, indexed by battle index)\n"
    "// (original-src pinned at 1ea47b5)\n"
    "// DO NOT EDIT BY HAND — regenerate via:\n"
    "//   python3 tools/asm_parser/parse_battle_magic_points.py \\\n"
    "//       --source-root  original-src \\\n"
    "//       --inc-out      src/data/generated/battle_magic_points_data.inc \\\n"
    "//       --fixture-out  tests/fixtures/battle_magic_points_expected.h\n"
    "\n"
)


def _entry_rows(values, indent="    "):
    # Both fields decimal: .battleIndex is the identity, .magicPoints is a
    # semantic magnitude (MP earned), not an opaque ROM byte — hex stays
    # reserved for raw opaque bytes.
    return "\n".join(
        "{}{{ .battleIndex = {:>3}, .magicPoints = {:>3} }},".format(
            indent, i, b)
        for i, b in enumerate(values))


def render_inc(values):
    return (
        _HEADER_COMMON +
        "// 512 BattleMagicPointsEntry rows (BattleMagicPoints, ROM DF/B400).\n"
        "// The row's identity (.battleIndex, decimal 0..511) is a typed\n"
        "// field, not the array position — a compile-time assert in\n"
        "// src/data/battle_magic_points.h verifies battleIndex == position\n"
        "// for every entry. .magicPoints is the magic-point award for that\n"
        "// battle (decimal — a semantic magnitude). Included inside the\n"
        "// hand-written\n"
        "//   `inline constexpr std::array<BattleMagicPointsEntry, 512>\n"
        "//    kBattleMagicPoints = {{ #include ... }};`\n"
        "// in src/data/battle_magic_points.h, which backs the\n"
        "// magicPointsForBattle(index) accessor.\n"
        "\n"
        + _entry_rows(values) + "\n")


def render_fixture(values):
    return (
        _HEADER_COMMON +
        "// Test fixture for tests/test_battle_magic_points.cpp — the\n"
        "// ground-truth copy of the table in the same self-labeling row shape\n"
        "// (.battleIndex decimal identity, .magicPoints decimal award). The\n"
        "// full-corpus test asserts kBattleMagicPoints matches this array\n"
        "// entry by entry (index and value), so a hand edit or re-emit drift\n"
        "// in either file fails loudly.\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include <array>\n"
        "#include <cstdint>\n"
        "\n"
        "namespace ostinato::test {\n"
        "\n"
        "// Mirrors ostinato::BattleMagicPointsEntry\n"
        "// (src/data/battle_magic_points.h) without depending on it.\n"
        "struct ExpectedBattleMagicPointsEntry {\n"
        "    std::uint16_t battleIndex;\n"
        "    std::uint8_t magicPoints;\n"
        "};\n"
        "\n"
        "inline constexpr std::array<ExpectedBattleMagicPointsEntry, 512> "
        "kBattleMagicPointsExpected = {{\n"
        + _entry_rows(values) + "\n"
        "}};\n"
        "\n"
        "}  // namespace ostinato::test\n")


def run(points_dat, inc_out, fixture_out, check_only=False):
    values = read_table(points_dat)
    if check_only:
        print("OK: {} magic-point entries (first={}, last={}).".format(
            len(values), values[0], values[-1]))
        return 0
    _write(inc_out, render_inc(values))
    _write(fixture_out, render_fixture(values))
    print("Emitted {} entries -> {}".format(len(values), inc_out))
    print("Emitted fixture -> {}".format(fixture_out))
    return 0


def _write(path, text):
    directory = os.path.dirname(path)
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def _resolve(args):
    if args.points_dat:
        return args.points_dat
    if args.source_root:
        return os.path.join(args.source_root, "src", "battle",
                            "battle_magic_points.dat")
    return None


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source-root",
                    help="disassembly root (battle_magic_points.dat resolved "
                         "under it)")
    ap.add_argument("--points-dat", help="path to battle_magic_points.dat")
    ap.add_argument("--inc-out",
                    default="src/data/generated/battle_magic_points_data.inc",
                    help="output path for the kBattleMagicPoints values")
    ap.add_argument("--fixture-out",
                    default="tests/fixtures/battle_magic_points_expected.h",
                    help="output path for the raw-value fixture")
    ap.add_argument("--check-only", action="store_true",
                    help="validate without writing files")
    args = ap.parse_args(argv)

    points_dat = _resolve(args)
    if not points_dat:
        ap.error("provide --source-root or --points-dat")
    try:
        return run(points_dat, args.inc_out, args.fixture_out,
                   check_only=args.check_only)
    except BattleMagicPointsError as exc:
        sys.stderr.write("BATTLE MAGIC POINTS ERROR: {}\n".format(exc))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
