#!/usr/bin/env python3
"""Unit tests for parse_battle_magic_points.py.

Three layers per the parser-test discipline:
  1. pure helpers (row formatting);
  2. synthetic inputs (length guard, renderer shape);
  3. end-to-end against the real original-src battle_magic_points.dat
     (skipped cleanly when the rip output is absent).

Python 3 stdlib only (unittest, tempfile). Run:
    python3 -m unittest discover -s tools/asm_parser -p 'test_parse_*.py'
"""

from __future__ import annotations

import os
import tempfile
import unittest

import parse_battle_magic_points as pbm


def _write_dat(data):
    fd, path = tempfile.mkstemp(suffix=".dat")
    with os.fdopen(fd, "wb") as fh:
        fh.write(bytes(data))
    return path


# --- Layer 1: pure helpers ---------------------------------------------------

class RowFormatTests(unittest.TestCase):

    def test_entry_rows_shape(self):
        rows = pbm._entry_rows([3, 10]).splitlines()
        # Identity is a decimal field, right-aligned; the award value is
        # decimal too (a semantic magnitude, not an opaque ROM byte).
        self.assertEqual(rows[0],
                         "    { .battleIndex =   0, .magicPoints =   3 },")
        self.assertEqual(rows[1],
                         "    { .battleIndex =   1, .magicPoints =  10 },")

    def test_entry_rows_three_digit_index(self):
        rows = pbm._entry_rows([0] * 512).splitlines()
        self.assertEqual(len(rows), 512)
        self.assertTrue(rows[511].startswith("    { .battleIndex = 511,"))


# --- Layer 2: synthetic inputs -----------------------------------------------

class ReadTableTests(unittest.TestCase):

    def test_reads_exact_512(self):
        path = _write_dat([i % 256 for i in range(512)])
        try:
            values = pbm.read_table(path)
        finally:
            os.remove(path)
        self.assertEqual(len(values), 512)
        self.assertEqual(values[0], 0)
        self.assertEqual(values[511], 255)

    def test_short_file_raises(self):
        path = _write_dat([0] * 511)
        try:
            with self.assertRaises(pbm.BattleMagicPointsError):
                pbm.read_table(path)
        finally:
            os.remove(path)

    def test_long_file_raises(self):
        path = _write_dat([0] * 513)
        try:
            with self.assertRaises(pbm.BattleMagicPointsError):
                pbm.read_table(path)
        finally:
            os.remove(path)


class RendererTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.values = [i % 256 for i in range(512)]

    def test_inc_shape(self):
        text = pbm.render_inc(self.values)
        self.assertIn(
            "AUTO-GENERATED by tools/asm_parser/parse_battle_magic_points.py",
            text)
        self.assertIn("pinned at 1ea47b5", text)
        self.assertIn("DO NOT EDIT BY HAND", text)
        self.assertIn("BattleMagicPointsEntry", text)
        self.assertIn("identity", text)
        self.assertEqual(text.count(".battleIndex ="), 512)

    def test_fixture_shape(self):
        text = pbm.render_fixture(self.values)
        self.assertIn("namespace ostinato::test", text)
        self.assertIn("struct ExpectedBattleMagicPointsEntry", text)
        self.assertIn("#pragma once", text)
        self.assertIn(
            "inline constexpr std::array<ExpectedBattleMagicPointsEntry, 512>",
            text)
        self.assertEqual(text.count(".battleIndex ="), 512)


# --- Layer 3: end-to-end against the real contract ---------------------------

def _find_points_dat():
    here = os.path.dirname(os.path.abspath(__file__))
    candidate = os.path.join(here, "..", "..", "original-src",
                             "src", "battle", "battle_magic_points.dat")
    return candidate if os.path.isfile(candidate) else None


@unittest.skipUnless(_find_points_dat(),
                     "original-src battle_magic_points.dat not present "
                     "(rip output absent)")
class EndToEndTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.values = pbm.read_table(_find_points_dat())

    def test_corpus_shape(self):
        self.assertEqual(len(self.values), 512)

    def test_boundary_values(self):
        # Known values of the FF6 battle magic-points table (FF3 1.1 US rip,
        # verified at emit).
        self.assertEqual(self.values[0], 0)
        self.assertEqual(self.values[16], 1)
        self.assertEqual(self.values[256], 1)
        self.assertEqual(self.values[511], 0)

    def test_award_range_sanity(self):
        # One-byte awards; the table is sparse (zero rows exist by design).
        self.assertTrue(any(v > 0 for v in self.values))
        self.assertTrue(all(0 <= v <= 255 for v in self.values))


if __name__ == "__main__":
    unittest.main()
