#!/usr/bin/env python3
"""Unit tests for parse_genju_prop.py.

Three layers per the parser-test discipline:
  1. pure helpers (macro-arg splitting, spell-group parsing, rendering);
  2. synthetic inputs (grammar edge cases, hard-error paths);
  3. end-to-end against the real original-src genju_prop.asm + const.inc
     (skipped cleanly when the contract clone is absent).

Python 3 stdlib only (unittest, tempfile). Run:
    python3 -m unittest discover -s tools/asm_parser -p 'test_parse_*.py'
"""

from __future__ import annotations

import os
import tempfile
import unittest

import parse_genju_prop as pgp
from common import ParseError


def _write_tmp(text, suffix):
    fd, path = tempfile.mkstemp(suffix=suffix)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(text)
    return path


# A minimal const.inc: a 2-member GENJU space starting at a non-zero base
# (mirroring the real $36-based block) and the symbols the synthetic genju
# file references.
_SYNTH_CONST = """\
.enum ATTACK
        ALPHA                           = 0
        BETA
        GAMMA
        NONE                            = $ff
.endenum

.enum GENJU
        ESP_A                           = $10
        ESP_B                           ;= $11
.endenum

.enum GENJU_BONUS
        POWER_UP                        = 0
        NONE                            = $ff
.endenum
"""

_SYNTH_GENJU = """\
.export GenjuProp

.mac make_genju_spell spell_id, spell_rate
        .byte spell_rate, ATTACK::spell_id
.endmac

.mac make_genju_prop spell1, spell2, spell3, spell4, spell5, bonus
        .ifnblank spell1
                make_genju_spell spell1
        .endif
.endmac

.segment "genju_prop"

GenjuProp:

; 0: full record, bonus present
make_genju_prop {ALPHA, 10}, {BETA, 2}, {GAMMA, 5}, {}, {}, POWER_UP

; 1: single spell, no bonus (5-arg form)
make_genju_prop {GAMMA, 1}, {}, {}, {}, {}
"""


def _parse_synthetic(genju_text, const_text=_SYNTH_CONST):
    const_path = _write_tmp(const_text, ".inc")
    genju_path = _write_tmp(genju_text, ".asm")
    try:
        symbols = pgp._Symbols(const_path)
        return pgp.parse_genju_prop(genju_path, symbols)
    finally:
        os.remove(const_path)
        os.remove(genju_path)


# --- Layer 1: pure helpers ---------------------------------------------------

class SplitMacroArgsTests(unittest.TestCase):

    def test_top_level_commas_split(self):
        self.assertEqual(pgp.split_macro_args("A, B, C", "f", 1),
                         ["A", "B", "C"])

    def test_brace_group_commas_do_not_split(self):
        self.assertEqual(
            pgp.split_macro_args("{ALPHA, 10}, {}, BONUS", "f", 1),
            ["{ALPHA, 10}", "{}", "BONUS"])

    def test_unbalanced_open_brace_raises(self):
        with self.assertRaises(ParseError):
            pgp.split_macro_args("{ALPHA, 10", "f", 1)

    def test_unbalanced_close_brace_raises(self):
        with self.assertRaises(ParseError):
            pgp.split_macro_args("ALPHA}, 10", "f", 1)


class ParseSpellGroupTests(unittest.TestCase):

    def test_blank_group_is_empty_slot(self):
        sp = pgp.parse_spell_group("{}", "f", 1)
        self.assertEqual((sp.rate, sp.attack), (0, "NONE"))

    def test_populated_group(self):
        sp = pgp.parse_spell_group("{ALPHA, 10}", "f", 1)
        self.assertEqual((sp.rate, sp.attack), (10, "ALPHA"))

    def test_hex_rate_literal(self):
        sp = pgp.parse_spell_group("{ALPHA, $0a}", "f", 1)
        self.assertEqual(sp.rate, 10)

    def test_malformed_group_raises(self):
        with self.assertRaises(ParseError):
            pgp.parse_spell_group("{ALPHA 10}", "f", 1)

    def test_non_integer_rate_raises(self):
        with self.assertRaises(ParseError):
            pgp.parse_spell_group("{ALPHA, RATE}", "f", 1)


class RenderTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        spells = [pgp.Spell(10, "ALPHA"), pgp.Spell(0, "NONE"),
                  pgp.Spell(0, "NONE"), pgp.Spell(0, "NONE"),
                  pgp.Spell(0, "NONE")]
        rec = pgp.Record(0, spells, "POWER_UP",
                         [10, 0, 0, 0xFF, 0, 0xFF, 0, 0xFF, 0, 0xFF, 0])
        rec.name = "ESP_A"
        rec.id_value = 0x10
        cls.records = [rec]

    def test_inc_shape(self):
        text = pgp._render_inc(self.records)
        self.assertIn("AUTO-GENERATED by tools/asm_parser/parse_genju_prop.py",
                      text)
        self.assertIn("pinned at 1ea47b5", text)
        self.assertIn("DO NOT EDIT BY HAND", text)
        self.assertIn(".id = EsperId::ESP_A,", text)
        self.assertIn("// [$10]", text)
        self.assertIn(".learnRate = 10, .spell = AttackId::ALPHA", text)
        self.assertIn(".bonus = EsperBonus::POWER_UP,", text)
        self.assertEqual(text.count("EsperSpell{"), 5)

    def test_fixture_shape(self):
        text = pgp._render_fixture(self.records)
        self.assertIn("namespace ostinato::test", text)
        self.assertIn("struct ExpectedEsperRecord", text)
        self.assertIn("#pragma once", text)
        self.assertIn("kExpectedEsperFirstId = 16;", text)
        self.assertIn("std::array<ExpectedEsperEntry, 1>", text)
        self.assertIn("{ .id = 16,  // $10 ESP_A", text)
        self.assertIn(".rate1 = 0x0A, .spell1 = 0x00", text)


# --- Layer 2: synthetic inputs -----------------------------------------------

class GrammarTests(unittest.TestCase):

    def test_happy_path(self):
        records = _parse_synthetic(_SYNTH_GENJU)
        self.assertEqual(len(records), 2)
        self.assertEqual(records[0].name, "ESP_A")
        self.assertEqual(records[0].id_value, 0x10)
        # rate-first byte order within each pair.
        self.assertEqual(records[0].bytes,
                         [10, 0, 2, 1, 5, 2, 0, 0xFF, 0, 0xFF, 0x00])
        self.assertEqual(records[0].bonus, "POWER_UP")

    def test_missing_bonus_defaults_to_none(self):
        records = _parse_synthetic(_SYNTH_GENJU)
        self.assertEqual(records[1].bonus, "NONE")
        self.assertEqual(records[1].bytes,
                         [1, 2, 0, 0xFF, 0, 0xFF, 0, 0xFF, 0, 0xFF, 0xFF])

    def test_macro_bodies_are_skipped(self):
        # The make_genju_spell invocation inside the .mac body must not be
        # parsed as record content.
        records = _parse_synthetic(_SYNTH_GENJU)
        self.assertEqual(len(records), 2)

    def test_record_count_mismatch_raises(self):
        one_record = _SYNTH_GENJU.rsplit("; 1:", 1)[0]
        with self.assertRaises(ParseError):
            _parse_synthetic(one_record)

    def test_unknown_spell_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_GENJU.replace("{ALPHA, 10}", "{BOGUS, 10}"))

    def test_unknown_bonus_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_GENJU.replace("POWER_UP", "BOGUS"))

    def test_too_many_args_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_GENJU.replace(
                "{}, {}, POWER_UP", "{}, {}, {}, POWER_UP"))

    def test_too_few_args_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_GENJU.replace(
                "make_genju_prop {GAMMA, 1}, {}, {}, {}, {}",
                "make_genju_prop {GAMMA, 1}, {}, {}, {}"))

    def test_missing_label_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_GENJU.replace("GenjuProp:\n", ""))

    def test_stray_line_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_GENJU + "        .byte $12\n")

    def test_noncontiguous_genju_enum_raises(self):
        bad_const = _SYNTH_CONST.replace(
            "ESP_B                           ;= $11",
            "ESP_B                           = $15")
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_GENJU, const_text=bad_const)


# --- Layer 3: end-to-end against the real contract ---------------------------

def _source_root():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.join(here, "..", "..", "original-src")
    genju = os.path.join(root, "src", "menu", "genju_prop.asm")
    const = os.path.join(root, "include", "const.inc")
    if os.path.isfile(genju) and os.path.isfile(const):
        return root
    return None


@unittest.skipUnless(_source_root(),
                     "original-src genju_prop.asm / const.inc not present")
class EndToEndTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        root = _source_root()
        symbols = pgp._Symbols(os.path.join(root, "include", "const.inc"))
        cls.records = pgp.parse_genju_prop(
            os.path.join(root, "src", "menu", "genju_prop.asm"), symbols)

    def test_corpus_shape(self):
        self.assertEqual(len(self.records), 27)
        for rec in self.records:
            self.assertEqual(len(rec.bytes), 11)

    def test_index_space_base(self):
        # GENJU starts at $36 (the esper block of the unified actor space).
        self.assertEqual(self.records[0].id_value, 0x36)
        self.assertEqual(self.records[0].name, "RAMUH")
        self.assertEqual(self.records[26].id_value, 0x50)
        self.assertEqual(self.records[26].name, "PHOENIX")

    def test_boundary_records(self):
        # Ramuh: {BOLT, 10} first — rate-first byte order, BOLT = $02.
        self.assertEqual(self.records[0].bytes[0], 10)
        self.assertEqual(self.records[0].bytes[1], 0x02)
        # Ragnarok ($46, index 16): ULTIMA ($14) at rate 1, four blank slots,
        # no bonus — all derived from blank args, never assumed.
        rag = self.records[16]
        self.assertEqual(rag.name, "RAGNAROK")
        self.assertEqual(rag.bytes,
                         [1, 0x14, 0, 0xFF, 0, 0xFF, 0, 0xFF, 0, 0xFF, 0xFF])
        # Starlet: bonus STAMINA_2 = $0E; Shiva: five spells yet bonus NONE.
        self.assertEqual(self.records[25].name, "STARLET")
        self.assertEqual(self.records[25].bytes[10], 0x0E)
        self.assertEqual(self.records[2].name, "SHIVA")
        self.assertEqual(self.records[2].bytes[10], 0xFF)

    def test_blank_slot_census(self):
        # 43 blank spell slots and 9 bonus-less records across the corpus
        # (hand-counted from genju_prop.asm at emit).
        blank = sum(1 for r in self.records
                    for s in r.spells if s.attack == "NONE")
        no_bonus = sum(1 for r in self.records if r.bonus == "NONE")
        self.assertEqual(blank, 43)
        self.assertEqual(no_bonus, 9)


if __name__ == "__main__":
    unittest.main()
