#!/usr/bin/env python3
"""Unit tests for parse_rng_tbl.py.

Three layers per the parser-test discipline:
  1. pure helpers (row formatting);
  2. synthetic inputs (length guard, renderer shape);
  3. end-to-end against the real original-src rng_tbl.dat (skipped cleanly
     when the rip output is absent).

Python 3 stdlib only (unittest, tempfile). Run:
    python3 -m unittest discover -s tools/asm_parser -p 'test_parse_*.py'
"""

from __future__ import annotations

import os
import tempfile
import unittest

import parse_rng_tbl as prt


def _write_dat(data):
    fd, path = tempfile.mkstemp(suffix=".dat")
    with os.fdopen(fd, "wb") as fh:
        fh.write(bytes(data))
    return path


# --- Layer 1: pure helpers ---------------------------------------------------

class RowFormatTests(unittest.TestCase):

    def test_entry_rows_shape(self):
        rows = prt._entry_rows([0x07, 0xB6]).splitlines()
        # Identity is a decimal field, right-aligned; value is the raw ROM byte
        # in hex (the house index->value row shape).
        self.assertEqual(rows[0], "    { .index =   0, .value = 0x07 },")
        self.assertEqual(rows[1], "    { .index =   1, .value = 0xB6 },")

    def test_entry_rows_three_digit_index(self):
        rows = prt._entry_rows([0] * 256).splitlines()
        self.assertEqual(len(rows), 256)
        self.assertTrue(rows[255].startswith("    { .index = 255,"))


# --- Layer 2: synthetic inputs -----------------------------------------------

class ReadTableTests(unittest.TestCase):

    def test_reads_exact_256(self):
        path = _write_dat(range(256))
        try:
            values = prt.read_table(path)
        finally:
            os.remove(path)
        self.assertEqual(len(values), 256)
        self.assertEqual(values[0], 0)
        self.assertEqual(values[255], 255)

    def test_short_file_raises(self):
        path = _write_dat(range(255))
        try:
            with self.assertRaises(prt.RngError):
                prt.read_table(path)
        finally:
            os.remove(path)

    def test_long_file_raises(self):
        path = _write_dat([0] * 257)
        try:
            with self.assertRaises(prt.RngError):
                prt.read_table(path)
        finally:
            os.remove(path)


class RendererTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.values = list(range(256))

    def test_inc_shape(self):
        text = prt.render_inc(self.values)
        self.assertIn("AUTO-GENERATED by tools/asm_parser/parse_rng_tbl.py", text)
        self.assertIn("pinned at 1ea47b5", text)
        self.assertIn("DO NOT EDIT BY HAND", text)
        self.assertIn("RngTableEntry", text)
        self.assertIn("identity", text)
        self.assertEqual(text.count(".index ="), 256)

    def test_fixture_shape(self):
        text = prt.render_fixture(self.values)
        self.assertIn("namespace ostinato::test", text)
        self.assertIn("struct ExpectedRngEntry", text)
        self.assertIn("#pragma once", text)
        self.assertIn(
            "inline constexpr std::array<ExpectedRngEntry, 256>", text)
        self.assertEqual(text.count(".index ="), 256)


# --- Layer 3: end-to-end against the real contract ---------------------------

def _find_rng_dat():
    here = os.path.dirname(os.path.abspath(__file__))
    candidate = os.path.join(here, "..", "..", "original-src",
                             "src", "field", "rng_tbl.dat")
    return candidate if os.path.isfile(candidate) else None


@unittest.skipUnless(_find_rng_dat(),
                     "original-src rng_tbl.dat not present (rip output absent)")
class EndToEndTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.values = prt.read_table(_find_rng_dat())

    def test_corpus_shape(self):
        self.assertEqual(len(self.values), 256)

    def test_boundary_values(self):
        # Known bytes of the FF6 RNG table (FF3 1.1 US rip, verified at emit).
        self.assertEqual(self.values[0], 0x07)
        self.assertEqual(self.values[1], 0xB6)
        self.assertEqual(self.values[2], 0xF0)
        self.assertEqual(self.values[16], 0x60)
        self.assertEqual(self.values[128], 0x25)
        self.assertEqual(self.values[255], 0xF8)


if __name__ == "__main__":
    unittest.main()
