#!/usr/bin/env python3
"""Unit tests for parse_dance_prop.py.

Three layers per the parser-test discipline:
  1. pure helpers (row / fixture rendering);
  2. synthetic inputs (grammar edge cases, hard-error paths);
  3. end-to-end against the real original-src dance_prop.asm + const.inc
     (skipped cleanly when the contract clone is absent).

Python 3 stdlib only (unittest, tempfile). Run:
    python3 -m unittest discover -s tools/asm_parser -p 'test_parse_*.py'
"""

from __future__ import annotations

import os
import tempfile
import unittest

import parse_dance_prop as pdp
from common import ParseError


def _write_tmp(text, suffix):
    fd, path = tempfile.mkstemp(suffix=suffix)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(text)
    return path


# A minimal const.inc: a 4-member DANCE space and the ATTACK symbols the
# synthetic dance file references.
_SYNTH_CONST = """\
.enum ATTACK
        ALPHA                           = 0
        BETA
        GAMMA
        DELTA
        NONE                            = $ff
.endenum

.enum DANCE
        FIRST                           = 0
        SECOND                          = 1
.endenum
"""

_SYNTH_DANCE = """\
; ------------------------------------------------------------------------------

.mac make_dance_prop attack1, attack2, attack3, attack4
        .byte ATTACK::attack1, ATTACK::attack2
        .byte ATTACK::attack3, ATTACK::attack4
.endmac

DanceProp:

; 0: first
        make_dance_prop ALPHA, BETA, GAMMA, DELTA

; 1: second
        make_dance_prop DELTA, GAMMA, BETA, ALPHA
"""


def _parse_synthetic(dance_text, const_text=_SYNTH_CONST):
    const_path = _write_tmp(const_text, ".inc")
    dance_path = _write_tmp(dance_text, ".asm")
    try:
        symbols = pdp._Symbols(const_path)
        return pdp.parse_dance_prop(dance_path, symbols)
    finally:
        os.remove(const_path)
        os.remove(dance_path)


# --- Layer 1: pure helpers ---------------------------------------------------

class RenderTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        rec = pdp.Record(0, ["ALPHA", "BETA", "GAMMA", "DELTA"], [0, 1, 2, 3])
        rec.name = "FIRST"
        cls.records = [rec]

    def test_inc_shape(self):
        text = pdp._render_inc(self.records)
        self.assertIn("AUTO-GENERATED by tools/asm_parser/parse_dance_prop.py",
                      text)
        self.assertIn("pinned at 1ea47b5", text)
        self.assertIn("DO NOT EDIT BY HAND", text)
        self.assertIn(".id = DanceId::FIRST,", text)
        self.assertIn("AttackId::ALPHA,", text)
        # Every slot carries its probability-tier comment.
        for rate in pdp._SLOT_RATES:
            self.assertIn("({})".format(rate), text)
        self.assertEqual(text.count("DancePropertiesEntry{"), 1)

    def test_fixture_shape(self):
        text = pdp._render_fixture(self.records)
        self.assertIn("namespace ostinato::test", text)
        self.assertIn("struct ExpectedDanceRecord", text)
        self.assertIn("#pragma once", text)
        self.assertIn("std::array<ExpectedDanceEntry, 1>", text)
        self.assertIn(".attack1 = 0x00, .attack2 = 0x01,"
                      " .attack3 = 0x02, .attack4 = 0x03", text)
        self.assertIn("// $00 FIRST", text)


# --- Layer 2: synthetic inputs -----------------------------------------------

class GrammarTests(unittest.TestCase):

    def test_happy_path(self):
        records = _parse_synthetic(_SYNTH_DANCE)
        self.assertEqual(len(records), 2)
        self.assertEqual(records[0].name, "FIRST")
        self.assertEqual(records[0].attacks,
                         ["ALPHA", "BETA", "GAMMA", "DELTA"])
        self.assertEqual(records[0].bytes, [0, 1, 2, 3])
        self.assertEqual(records[1].bytes, [3, 2, 1, 0])

    def test_macro_body_is_skipped(self):
        # The .byte lines inside the .mac body must not be parsed as content.
        records = _parse_synthetic(_SYNTH_DANCE)
        self.assertEqual(len(records), 2)

    def test_record_count_mismatch_raises(self):
        one_record = _SYNTH_DANCE.rsplit("; 1: second", 1)[0]
        with self.assertRaises(ParseError):
            _parse_synthetic(one_record)

    def test_unknown_attack_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_DANCE.replace("ALPHA, BETA", "BOGUS, BETA"))

    def test_wrong_arg_count_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_DANCE.replace(
                "make_dance_prop ALPHA, BETA, GAMMA, DELTA",
                "make_dance_prop ALPHA, BETA, GAMMA"))

    def test_missing_label_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_DANCE.replace("DanceProp:\n", ""))

    def test_invocation_before_label_raises(self):
        moved = _SYNTH_DANCE.replace(
            "DanceProp:\n\n; 0: first\n        make_dance_prop ALPHA, BETA, GAMMA, DELTA\n",
            "        make_dance_prop ALPHA, BETA, GAMMA, DELTA\nDanceProp:\n")
        with self.assertRaises(ParseError):
            _parse_synthetic(moved)

    def test_stray_line_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_DANCE + "        .byte $12\n")

    def test_noncontiguous_dance_enum_raises(self):
        bad_const = _SYNTH_CONST.replace("SECOND                          = 1",
                                         "SECOND                          = 5")
        with self.assertRaises(ParseError):
            _parse_synthetic(_SYNTH_DANCE, const_text=bad_const)


# --- Layer 3: end-to-end against the real contract ---------------------------

def _source_root():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.join(here, "..", "..", "original-src")
    dance = os.path.join(root, "src", "battle", "dance_prop.asm")
    const = os.path.join(root, "include", "const.inc")
    if os.path.isfile(dance) and os.path.isfile(const):
        return root
    return None


@unittest.skipUnless(_source_root(),
                     "original-src dance_prop.asm / const.inc not present")
class EndToEndTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        root = _source_root()
        symbols = pdp._Symbols(os.path.join(root, "include", "const.inc"))
        cls.records = pdp.parse_dance_prop(
            os.path.join(root, "src", "battle", "dance_prop.asm"), symbols)

    def test_corpus_shape(self):
        self.assertEqual(len(self.records), 8)
        for rec in self.records:
            self.assertEqual(len(rec.bytes), 4)

    def test_boundary_records(self):
        # 0: wind song — WIND_SLASH ($65) leads, COKATRICE ($75) trails.
        self.assertEqual(self.records[0].name, "WIND_SONG")
        self.assertEqual(self.records[0].attacks,
                         ["WIND_SLASH", "SUN_BATH", "PLASMA", "COKATRICE"])
        self.assertEqual(self.records[0].bytes[0], 0x65)
        self.assertEqual(self.records[0].bytes[3], 0x75)
        # 7: snowman jazz — ICE_RABBIT ($7C) trails.
        self.assertEqual(self.records[7].name, "SNOWMAN_JAZZ")
        self.assertEqual(self.records[7].attacks,
                         ["SNOWBALL", "SURGE", "SNARE", "ICE_RABBIT"])
        self.assertEqual(self.records[7].bytes[3], 0x7C)


if __name__ == "__main__":
    unittest.main()
