#!/usr/bin/env python3
"""Unit tests for parse_natural_magic.py.

Three layers per the parser-test discipline:
  1. pure helpers (row / fixture rendering);
  2. synthetic inputs (anchored-region grammar, hard-error paths);
  3. end-to-end against the real original-src event.asm + const.inc
     (skipped cleanly when the contract clone is absent).

Python 3 stdlib only (unittest, tempfile). Run:
    python3 -m unittest discover -s tools/asm_parser -p 'test_parse_*.py'
"""

from __future__ import annotations

import os
import tempfile
import unittest

import parse_natural_magic as pnm
from common import ParseError


def _write_tmp(text, suffix):
    fd, path = tempfile.mkstemp(suffix=suffix)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(text)
    return path


_SYNTH_CONST = """\
.enum ATTACK
        ALPHA                           = 0
        BETA
        NONE                            = $ff
.endenum
"""


def _synth_event(pair_count=32, tail=".popseg\n", label_line="NaturalMagic:\n"):
    """Build a synthetic event.asm: unrelated code, the anchored region, more
    unrelated code. Pairs alternate ALPHA/BETA with the pair number as level."""
    lines = ["; unrelated event code the parser must skip\n",
             "SomeRoutine:\n",
             "        lda     $1234\n",
             "        rts\n",
             "\n",
             '.segment "natural_magic"\n',
             "\n",
             "; ec/e3c0\n",
             label_line]
    for i in range(pair_count):
        attack = "ALPHA" if i % 2 == 0 else "BETA"
        lines.append("        .byte ATTACK::{}, {}\n".format(attack, i + 1))
    lines.append(tail)
    lines.append("\n; more unrelated code\n")
    lines.append("OtherRoutine:\n")
    lines.append("        rts\n")
    return "".join(lines)


def _parse_synthetic(event_text, const_text=_SYNTH_CONST):
    const_path = _write_tmp(const_text, ".inc")
    event_path = _write_tmp(event_text, ".asm")
    try:
        symbols = pnm._Symbols(const_path)
        return pnm.parse_natural_magic(event_path, symbols)
    finally:
        os.remove(const_path)
        os.remove(event_path)


# --- Layer 1: pure helpers ---------------------------------------------------

class RenderTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.terra = [pnm.Pair(i, "ALPHA", i + 1, 0) for i in range(16)]
        cls.celes = [pnm.Pair(i, "BETA", i + 2, 1) for i in range(16)]

    def test_inc_shape(self):
        text = pnm._render_inc(self.terra, self.celes)
        self.assertIn(
            "AUTO-GENERATED by tools/asm_parser/parse_natural_magic.py", text)
        self.assertIn("pinned at 1ea47b5", text)
        self.assertIn("DO NOT EDIT BY HAND", text)
        self.assertIn("kNaturalMagicTerra", text)
        self.assertIn("kNaturalMagicCeles", text)
        self.assertIn(".spell = AttackId::ALPHA,", text)
        self.assertEqual(text.count("NaturalMagicSlot{"), 32)
        self.assertEqual(text.count(".slot =  0,"), 2)  # one per half

    def test_fixture_shape(self):
        text = pnm._render_fixture(self.terra, self.celes)
        self.assertIn("namespace ostinato::test", text)
        self.assertIn("struct ExpectedNaturalMagicRecord", text)
        self.assertIn("#pragma once", text)
        self.assertIn("kExpectedNaturalMagicTerra", text)
        self.assertIn("kExpectedNaturalMagicCeles", text)
        self.assertIn(".spell = 0x00, .level = 0x01", text)
        self.assertEqual(text.count("{ .slot ="), 32)


# --- Layer 2: synthetic inputs -----------------------------------------------

class GrammarTests(unittest.TestCase):

    def test_happy_path(self):
        terra, celes = _parse_synthetic(_synth_event())
        self.assertEqual(len(terra), 16)
        self.assertEqual(len(celes), 16)
        # ROM byte order: spell first, level second.
        self.assertEqual(terra[0].bytes, [0, 1])       # ALPHA, level 1
        self.assertEqual(terra[0].slot, 0)
        self.assertEqual(celes[0].bytes, [0, 17])      # pair 17 -> Celes slot 0
        self.assertEqual(celes[0].slot, 0)
        self.assertEqual(celes[15].bytes, [1, 32])     # BETA, level 32

    def test_surrounding_code_is_skipped(self):
        # The unrelated routines before and after the region must not trip
        # the grammar.
        terra, celes = _parse_synthetic(_synth_event())
        self.assertEqual(len(terra) + len(celes), 32)

    def test_truncated_block_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_synth_event(pair_count=31))

    def test_extra_pair_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_synth_event(
                tail="        .byte ATTACK::ALPHA, 50\n.popseg\n"))

    def test_missing_popseg_raises(self):
        with self.assertRaises(ParseError):
            _parse_synthetic(_synth_event(tail="SomeLabel:\n"))

    def test_missing_segment_raises(self):
        text = _synth_event().replace('.segment "natural_magic"\n', "")
        with self.assertRaises(ParseError):
            _parse_synthetic(text)

    def test_label_not_after_segment_raises(self):
        text = _synth_event(label_line="SomethingElse:\n")
        with self.assertRaises(ParseError):
            _parse_synthetic(text)

    def test_unknown_attack_raises(self):
        text = _synth_event().replace("ATTACK::ALPHA, 1\n", "ATTACK::BOGUS, 1\n")
        with self.assertRaises(ParseError):
            _parse_synthetic(text)

    def test_malformed_pair_raises(self):
        text = _synth_event().replace("ATTACK::ALPHA, 1\n", "ATTACK::ALPHA\n")
        with self.assertRaises(ParseError):
            _parse_synthetic(text)

    def test_duplicate_segment_raises(self):
        text = _synth_event() + '\n.segment "natural_magic"\n'
        with self.assertRaises(ParseError):
            _parse_synthetic(text)


# --- Layer 3: end-to-end against the real contract ---------------------------

def _source_root():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.join(here, "..", "..", "original-src")
    event = os.path.join(root, "src", "field", "event.asm")
    const = os.path.join(root, "include", "const.inc")
    if os.path.isfile(event) and os.path.isfile(const):
        return root
    return None


@unittest.skipUnless(_source_root(),
                     "original-src event.asm / const.inc not present")
class EndToEndTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        root = _source_root()
        symbols = pnm._Symbols(os.path.join(root, "include", "const.inc"))
        cls.terra, cls.celes = pnm.parse_natural_magic(
            os.path.join(root, "src", "field", "event.asm"), symbols)

    def test_corpus_shape(self):
        self.assertEqual(len(self.terra), 16)
        self.assertEqual(len(self.celes), 16)

    def test_boundary_pairs(self):
        # Terra: CURE ($2D) at level 1 through ULTIMA ($14) at 99.
        self.assertEqual(self.terra[0].attack, "CURE")
        self.assertEqual(self.terra[0].bytes, [0x2D, 1])
        self.assertEqual(self.terra[15].attack, "ULTIMA")
        self.assertEqual(self.terra[15].bytes, [0x14, 99])
        # Celes: ICE at level 1 through METEOR ($13) at 98.
        self.assertEqual(self.celes[0].attack, "ICE")
        self.assertEqual(self.celes[0].bytes[1], 1)
        self.assertEqual(self.celes[15].attack, "METEOR")
        self.assertEqual(self.celes[15].bytes, [0x13, 98])

    def test_celes_out_of_order_muddle_quirk(self):
        # The ROM's own out-of-sorted-order entry: MUDDLE ($1E) at level 32
        # AFTER BSERK at level 40. Contract — never re-sorted.
        self.assertEqual(self.celes[8].attack, "BSERK")
        self.assertEqual(self.celes[8].bytes[1], 40)
        self.assertEqual(self.celes[9].attack, "MUDDLE")
        self.assertEqual(self.celes[9].bytes, [0x1E, 32])


if __name__ == "__main__":
    unittest.main()
