// AUTO-GENERATED by tools/asm_parser/parse_battle_main_tables.py — DO NOT EDIT.
// Source: original-src/src/battle/battle_main.asm (the AI script command handlers)
// (original-src pinned at 1ea47b5)
//
// The commands a monster's AI script is written in. A script is a
// byte stream: any value below the first command is an attack to use,
// and these values introduce everything else. Each command is followed
// by a fixed number of argument bytes — see kAiCommandSizes in
// src/data/battle_tables.h.
#pragma once

#include <cstdint>

namespace ostinato {

enum class AiScriptCommand : std::uint8_t {
    USE_ATTACK                   = 0xF0,
    TARGETTING                   = 0xF1,
    BATTLE_CHANGE                = 0xF2,
    DISPLAY_SHORT_BATTLE_DIALOG  = 0xF3,
    DO_COMMAND                   = 0xF4,
    MONSTER_DEATH_ENTRY          = 0xF5,
    USE_THROW_ITEM               = 0xF6,
    EXECUTE_BATTLE_EVENT         = 0xF7,
    BYTE_WISE_VARIABLE_MANIPULATION = 0xF8,
    BIT_WISE_VARIABLE_MANIPULATION = 0xF9,
    MISC_MONSTER_ANIMATIONS      = 0xFA,
    MISC_BATTLE_EFFECTS          = 0xFB,
    CONDITIONAL                  = 0xFC,
    WAIT_UNTIL_END_OF_TURN       = 0xFD,
    END_IF                       = 0xFE,
    END_OF_SCRIPT                = 0xFF,
};

}  // namespace ostinato
