// AUTO-GENERATED by tools/asm_parser/parse_battle_bg.py — DO NOT EDIT.
// Source: original-src/include/gfx/battle_bg.inc (ca65 .enum BATTLE_BG_PAL)
// (original-src pinned at 1ea47b5)
//
// One battle-background palette (48 colours, BG palettes 5-7).
#pragma once

#include <cstdint>

namespace ostinato {

enum class BattleBackgroundPaletteId : std::uint8_t {
    FIELD_WOB        = 0x00,
    NARSHE_EXT       = 0x01,
    NARSHE_CAVES     = 0x02,
    CAVES            = 0x03,
    MOUNTAINS_EXT    = 0x04,
    MOUNTAINS_INT    = 0x05,
    RIVER            = 0x06,
    IMP_CAMP         = 0x07,
    TRAIN_EXT        = 0x08,
    TRAIN_INT        = 0x09,
    FANATICS_TOWER   = 0x0A,
    DESERT_WOB       = 0x0B,
    FOREST_WOB       = 0x0C,
    FIELD_WOR        = 0x0D,
    VELDT            = 0x0E,
    SNOWFIELDS       = 0x0F,
    TOWN_EXT         = 0x10,
    IMP_CASTLE       = 0x11,
    FLOATING_ISLAND  = 0x12,
    KEFKAS_TOWER_EXT = 0x13,
    OPERA_STAGE      = 0x14,
    OPERA_CATWALK    = 0x15,
    BURNING_BUILDING = 0x16,
    CASTLE_INT       = 0x17,
    MAGITEK          = 0x18,
    COLOSSEUM        = 0x19,
    SEALED_GATE      = 0x1A,
    VILLAGE_EXT      = 0x1B,
    WATERFALL        = 0x1C,
    BATTLE_BG_PAL_29 = 0x1D,
    TRAIN_TRACKS     = 0x1E,
    BATTLE_BG_PAL_31 = 0x1F,
    TENTACLES        = 0x20,
    FIRE_CAVES       = 0x21,
    TOWN_INT         = 0x22,
    ZOZO_INT         = 0x23,
    UNDERWATER       = 0x24,
    ZOZO_EXT         = 0x25,
    AIRSHIP_WOB      = 0x26,
    DARILLS_TOMB     = 0x27,
    CASTLE_EXT       = 0x28,
    KEFKAS_TOWER_INT = 0x29,
    BATTLE_BG_PAL_42 = 0x2A,
    OWZERS_HOUSE     = 0x2B,
    FINAL_BATTLE_1   = 0x2C,
    FINAL_BATTLE_2   = 0x2D,
    FINAL_BATTLE_3   = 0x2E,
    MAGITEK_TRAIN    = 0x2F,
    FINAL_BATTLE_4   = 0x30,
    FOREST_WOR       = 0x31,
    CYANS_DREAM      = 0x32,
    AIRSHIP_WOR      = 0x33,
    DESERT_WOR       = 0x34,
};

}  // namespace ostinato
