// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum BATTLE_CHAR_PAL)
#pragma once

#include <cstdint>

namespace ostinato {

enum class BattleCharacterPalette : std::uint8_t {
    EDGAR         = 0x00,
    SABIN         = 0x00,
    CELES         = 0x00,
    IMP           = 0x00,
    LEO           = 0x00,
    GHOST         = 0x00,
    GREEN_SOLDIER = 0x00,
    LOCKE         = 0x01,
    MERCHANT      = 0x01,
    BROWN_SOLDIER = 0x01,
    TERRA         = 0x02,
    STRAGO        = 0x03,
    RELM          = 0x03,
    GAU           = 0x03,
    GOGO          = 0x03,
    BANON         = 0x03,
    KEFKA         = 0x03,
    GESTAHL       = 0x03,
    CYAN          = 0x04,
    SHADOW        = 0x04,
    SETZER        = 0x04,
    MOG           = 0x05,
    UMARO         = 0x05,
    ESPER_TERRA   = 0x06,
};

}  // namespace ostinato
