// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum BATTLE_CMD)
#pragma once

#include <cstdint>

namespace ostinato {

enum class BattleCommandId : std::uint8_t {
    FIGHT   = 0x00,
    ITEM    = 0x01,
    MAGIC   = 0x02,
    MORPH   = 0x03,
    REVERT  = 0x04,
    STEAL   = 0x05,
    CAPTURE = 0x06,
    BUSHIDO = 0x07,
    THROW   = 0x08,
    TOOLS   = 0x09,
    BLITZ   = 0x0A,
    RUNIC   = 0x0B,
    LORE    = 0x0C,
    SKETCH  = 0x0D,
    CONTROL = 0x0E,
    SLOT    = 0x0F,
    RAGE    = 0x10,
    LEAP    = 0x11,
    MIMIC   = 0x12,
    DANCE   = 0x13,
    ROW     = 0x14,
    DEF     = 0x15,
    JUMP    = 0x16,
    X_MAGIC = 0x17,
    GP_RAIN = 0x18,
    SUMMON  = 0x19,
    HEALTH  = 0x1A,
    SHOCK   = 0x1B,
    POSSESS = 0x1C,
    MAGITEK = 0x1D,
    NONE    = 0xFF,
};

}  // namespace ostinato
