// AUTO-GENERATED by tools/asm_parser/parse_battle_bg.py — DO NOT EDIT.
// Source: original-src/include/gfx/battle_bg.inc (ca65 .enum BATTLE_BG_GFX)
// (original-src pinned at 1ea47b5)
//
// One 64-tile battle-background graphics block. A record in
// src/data/generated/battle_bg_prop_data.inc names up to three; NONE
// ($FF) means that block is not loaded. When a record's first block sets
// the double-width flag the block is 128 tiles and the second is skipped.
#pragma once

#include <cstdint>

namespace ostinato {

enum class BattleBackgroundGraphicsId : std::uint8_t {
    TOWN_EXT_1        = 0x00,
    TOWN_EXT_2        = 0x01,
    BATTLE_BG_GFX_2   = 0x02,
    MOUNTAINS_EXT_1   = 0x03,
    MOUNTAINS_INT_1   = 0x04,
    RIVER_1           = 0x05,
    IMP_CAMP_1        = 0x06,
    TRAIN_EXT_1       = 0x07,
    TRAIN_INT_1       = 0x08,
    CAVES_1           = 0x09,
    TRAIN_EXT_2       = 0x0A,
    MOUNTAINS_EXT_2   = 0x0B,
    MOUNTAINS_INT_2   = 0x0C,
    RIVER_2           = 0x0D,
    IMP_CAMP_2        = 0x0E,
    GHOST_TRAIN_1     = 0x0F,
    TRAIN_INT_2       = 0x10,
    CAVES_2           = 0x11,
    FIELD_1           = 0x12,
    FIELD_2           = 0x13,
    FIELD_3           = 0x14,
    TRAIN_EXT_3       = 0x15,
    COLOSSEUM         = 0x16,
    BATTLE_BG_GFX_23  = 0x17,
    DESERT_1          = 0x18,
    FOREST_1          = 0x19,
    FOREST_2          = 0x1A,
    FIELD_WOR         = 0x1B,
    VELDT             = 0x1C,
    DESERT_2          = 0x1D,
    IMP_CASTLE_1      = 0x1E,
    FLOATING_ISLAND_1 = 0x1F,
    KEFKAS_TOWER_1    = 0x20,
    OPERA_STAGE       = 0x21,
    OPERA_CATWALK     = 0x22,
    BURNING_BLDG_1    = 0x23,
    CASTLE_INT        = 0x24,
    MAGITEK_1         = 0x25,
    CASTLE_EXT_1      = 0x26,
    MAGITEK_2         = 0x27,
    IMP_CASTLE_2      = 0x28,
    FLOATING_ISLAND_2 = 0x29,
    KEFKAS_TOWER_2    = 0x2A,
    OPERA_CURTAIN     = 0x2B,
    BURNING_BLDG_2    = 0x2C,
    TENTACLES         = 0x2D,
    CASTLE_EXT_2      = 0x2E,
    TOWN_INT_1        = 0x2F,
    TOWN_INT_2        = 0x30,
    GHOST_TRAIN_2     = 0x31,
    UNDERWATER        = 0x32,
    SEALED_GATE_1     = 0x33,
    SEALED_GATE_2     = 0x34,
    ZOZO_1            = 0x35,
    ZOZO_2            = 0x36,
    CLOUDS_1          = 0x37,
    CLOUDS_2          = 0x38,
    AIRSHIP           = 0x39,
    DARILLS_TOMB_1    = 0x3A,
    DARILLS_TOMB_2    = 0x3B,
    WATERFALL         = 0x3C,
    FINAL_BATTLE_1    = 0x3D,
    FINAL_BATTLE_2    = 0x3E,
    FINAL_BATTLE_3    = 0x3F,
    FINAL_BATTLE_4    = 0x40,
    FINAL_BATTLE_5    = 0x41,
    FINAL_BATTLE_6    = 0x42,
    FINAL_BATTLE_7    = 0x43,
    FINAL_BATTLE_8    = 0x44,
    FANATICS_TOWER    = 0x45,
    MAGITEK_TRAIN_1   = 0x46,
    MAGITEK_TRAIN_2   = 0x47,
    DARILLS_TOMB_3    = 0x48,
    CYANS_DREAM_1     = 0x49,
    CYANS_DREAM_2     = 0x4A,
    NONE              = 0xFF,
};

}  // namespace ostinato
