// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum BATTLE_CMD_FLAG)
#pragma once

#include <cstdint>

namespace ostinato {

enum class BattleCommandFlags : std::uint8_t {
    NONE    = 0x00,
    GOGO    = 0x01,
    MIMIC   = 0x02,
    IMP     = 0x04,
    UNKNOWN = 0x08,
};

}  // namespace ostinato
