// AUTO-GENERATED by tools/asm_parser/parse_encounters.py — DO NOT EDIT.
// Source: original-src/include/gfx/battle_bg.inc (ca65 .enum BATTLE_BG)
// (original-src pinned at 1ea47b5)
//
// The battle background shown behind a formation. WorldBattleBGTbl
// (src/data/generated/encounter_bg_tables_data.inc) selects one per
// world-map sector slot; DEFAULT ($FF) is the loader's fallback.
#pragma once

#include <cstdint>

namespace ostinato {

enum class BattleBackgroundId : std::uint8_t {
    FIELD_WOB        = 0x00,
    FOREST_WOR       = 0x01,
    DESERT_WOB       = 0x02,
    FOREST_WOB       = 0x03,
    ZOZO_INT         = 0x04,
    FIELD_WOR        = 0x05,
    VELDT            = 0x06,
    CLOUDS           = 0x07,
    NARSHE_EXT       = 0x08,
    NARSHE_CAVES_1   = 0x09,
    CAVES            = 0x0A,
    MOUNTAINS_EXT    = 0x0B,
    MOUNTAINS_INT    = 0x0C,
    RIVER            = 0x0D,
    IMP_CAMP         = 0x0E,
    TRAIN_EXT        = 0x0F,
    TRAIN_INT        = 0x10,
    NARSHE_CAVES_2   = 0x11,
    SNOWFIELDS       = 0x12,
    TOWN_EXT         = 0x13,
    IMP_CASTLE       = 0x14,
    FLOATING_ISLAND  = 0x15,
    KEFKAS_TOWER_EXT = 0x16,
    OPERA_STAGE      = 0x17,
    OPERA_CATWALK    = 0x18,
    BURNING_BUILDING = 0x19,
    CASTLE_INT       = 0x1A,
    MAGITEK_LAB      = 0x1B,
    COLOSSEUM        = 0x1C,
    MAGITEK_FACTORY  = 0x1D,
    VILLAGE_EXT      = 0x1E,
    WATERFALL        = 0x1F,
    OWZERS_HOUSE     = 0x20,
    TRAIN_TRACKS     = 0x21,
    SEALED_GATE      = 0x22,
    UNDERWATER       = 0x23,
    ZOZO             = 0x24,
    AIRSHIP_CENTER   = 0x25,
    DARILLS_TOMB     = 0x26,
    CASTLE_EXT       = 0x27,
    KEFKAS_TOWER_INT = 0x28,
    AIRSHIP_WOR      = 0x29,
    FIRE_CAVES       = 0x2A,
    TOWN_INT         = 0x2B,
    MAGITEK_TRAIN    = 0x2C,
    FANATICS_TOWER   = 0x2D,
    CYANS_DREAM      = 0x2E,
    DESERT_WOR       = 0x2F,
    AIRSHIP_WOB      = 0x30,
    BATTLE_BG_31     = 0x31,
    GHOST_TRAIN      = 0x32,
    FINAL_BATTLE_1   = 0x33,
    FINAL_BATTLE_2   = 0x34,
    FINAL_BATTLE_3   = 0x35,
    FINAL_BATTLE_4   = 0x36,
    TENTACLES        = 0x37,
    DEFAULT          = 0xFF,
};

}  // namespace ostinato
