// AUTO-GENERATED by tools/asm_parser/parse_blitz_code.py
// Source: original-src/include/btlgfx/blitz_code.inc (ca65 .enum BLITZ_CODE)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_blitz_code.py \
//       --source-root  original-src
//
// One input in a blitz's button sequence: a face or shoulder
// button, or one of the eight pad directions. NONE pads a
// sequence out to its fixed length.
#pragma once

#include <cstdint>

namespace ostinato {

enum class BlitzCodeInput : std::uint8_t {
    NONE       = 0,
    A_BUTTON   = 1,
    B_BUTTON   = 2,
    X_BUTTON   = 3,
    Y_BUTTON   = 4,
    L_BUTTON   = 5,
    R_BUTTON   = 6,
    DOWN_LEFT  = 7,
    DOWN       = 8,
    DOWN_RIGHT = 9,
    RIGHT      = 10,
    UP_RIGHT   = 11,
    UP         = 12,
    UP_LEFT    = 13,
    LEFT       = 14,
};

}  // namespace ostinato
