// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum CHAR_GFX)
#pragma once

#include <cstdint>

namespace ostinato {

enum class CharacterGfxId : std::uint8_t {
    TERRA       = 0x00,
    LOCKE       = 0x01,
    CYAN        = 0x02,
    SHADOW      = 0x03,
    EDGAR       = 0x04,
    SABIN       = 0x05,
    CELES       = 0x06,
    STRAGO      = 0x07,
    RELM        = 0x08,
    SETZER      = 0x09,
    MOG         = 0x0A,
    GAU         = 0x0B,
    GOGO        = 0x0C,
    UMARO       = 0x0D,
    SOLDIER     = 0x0E,
    IMP         = 0x0F,
    LEO         = 0x10,
    BANON       = 0x11,
    ESPER_TERRA = 0x12,
    MERCHANT    = 0x13,
    GHOST       = 0x14,
    KEFKA       = 0x15,
    GESTAHL     = 0x16,
};

}  // namespace ostinato
