// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum CHAR_FLAG)
#pragma once

#include <cstdint>

namespace ostinato {

enum class CharacterFlags : std::uint16_t {
    TERRA  = 0x0001,
    LOCKE  = 0x0002,
    CYAN   = 0x0004,
    SHADOW = 0x0008,
    EDGAR  = 0x0010,
    SABIN  = 0x0020,
    CELES  = 0x0040,
    STRAGO = 0x0080,
    RELM   = 0x0100,
    SETZER = 0x0200,
    MOG    = 0x0400,
    GAU    = 0x0800,
    GOGO   = 0x1000,
    UMARO  = 0x2000,
};

}  // namespace ostinato
