// AUTO-GENERATED by tools/asm_parser/parse_char_ai.py — DO NOT EDIT.
// Source: original-src/include/btlgfx/char_ai.inc (ca65 .enum CHAR_AI)
// (original-src pinned at 1ea47b5)
//
// Which scripted battle setup a battle runs under. A setup places
// its own cast in the character slots and can override the
// background and music; NONE is the ordinary case, where the
// player's party fights.
#pragma once

#include <cstdint>

namespace ostinato {

enum class CharAiId : std::uint8_t {
    NONE             = 0x00,
    SHADOW_COLOSSEUM = 0x01,
    TERRA_FLASHBACK  = 0x02,
    VARGAS           = 0x03,
    KEFKA_IMP_CAMP_1 = 0x04,
    CYAN_IMP_CAMP_1  = 0x05,
    CYAN_IMP_CAMP_2  = 0x06,
    PIRANHA          = 0x07,
    UNUSED_08        = 0x08,
    UNUSED_09        = 0x09,
    GAU_VELDT        = 0x0A,
    UNUSED_0B        = 0x0B,
    SEALED_GATE_1    = 0x0C,
    SEALED_GATE_2    = 0x0D,
    BLACKJACK_ESPERS = 0x0E,
    ULTROS_RELM      = 0x0F,
    ESPERS           = 0x10,
    BLITZ_TUTORIAL   = 0x11,
    KEFKA_ESPER      = 0x12,
    KEFKA_GESTAHL    = 0x13,
    KEFKA_LEO        = 0x14,
    UNUSED_15        = 0x15,
    UNUSED_16        = 0x16,
    UNUSED_17        = 0x17,
};

}  // namespace ostinato
