// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum ELEMENT)
#pragma once

#include <cstdint>

namespace ostinato {

enum class Element : std::uint8_t {
    FIRE      = 0x01,
    ICE       = 0x02,
    LIGHTNING = 0x04,
    POISON    = 0x08,
    WIND      = 0x10,
    HOLY      = 0x20,
    EARTH     = 0x40,
    WATER     = 0x80,
    NONE      = 0x00,
};

}  // namespace ostinato
