// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum GENJU_BONUS)
#pragma once

#include <cstdint>

namespace ostinato {

enum class EsperBonus : std::uint8_t {
    HP_10      = 0x00,
    HP_30      = 0x01,
    HP_50      = 0x02,
    MP_10      = 0x03,
    MP_30      = 0x04,
    MP_50      = 0x05,
    HP_100     = 0x06,
    LV_30      = 0x07,
    LV_50      = 0x08,
    STRENGTH_1 = 0x09,
    STRENGTH_2 = 0x0A,
    SPEED_1    = 0x0B,
    SPEED_2    = 0x0C,
    STAMINA_1  = 0x0D,
    STAMINA_2  = 0x0E,
    MAGPWR_1   = 0x0F,
    MAGPWR_2   = 0x10,
    NONE       = 0xFF,
};

}  // namespace ostinato
