// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum GENJU)
#pragma once

#include <cstdint>

namespace ostinato {

enum class EsperId : std::uint8_t {
    RAMUH    = 0x36,
    IFRIT    = 0x37,
    SHIVA    = 0x38,
    SIREN    = 0x39,
    TERRATO  = 0x3A,
    SHOAT    = 0x3B,
    MADUIN   = 0x3C,
    BISMARK  = 0x3D,
    STRAY    = 0x3E,
    PALIDOR  = 0x3F,
    TRITOCH  = 0x40,
    ODIN     = 0x41,
    RAIDEN   = 0x42,
    BAHAMUT  = 0x43,
    ALEXANDR = 0x44,
    CRUSADER = 0x45,
    RAGNAROK = 0x46,
    KIRIN    = 0x47,
    ZONESEEK = 0x48,
    CARBUNKL = 0x49,
    PHANTOM  = 0x4A,
    SRAPHIM  = 0x4B,
    GOLEM    = 0x4C,
    UNICORN  = 0x4D,
    FENRIR   = 0x4E,
    STARLET  = 0x4F,
    PHOENIX  = 0x50,
};

}  // namespace ostinato
