// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum EVENT_DIR)
#pragma once

#include <cstdint>

namespace ostinato {

enum class EventDir : std::uint8_t {
    UP               = 0x00,
    RIGHT            = 0x01,
    DOWN             = 0x02,
    LEFT             = 0x03,
    UP_RIGHT         = 0x04,
    RIGHT_UP         = UP_RIGHT,
    DOWN_RIGHT       = 0x05,
    RIGHT_DOWN       = DOWN_RIGHT,
    DOWN_LEFT        = 0x06,
    LEFT_DOWN        = DOWN_LEFT,
    UP_LEFT          = 0x07,
    LEFT_UP          = UP_LEFT,
    RIGHT_UP_UP      = 0x08,
    RIGHT_RIGHT_UP   = 0x09,
    RIGHT_RIGHT_DOWN = 0x0A,
    RIGHT_DOWN_DOWN  = 0x0B,
    LEFT_DOWN_DOWN   = 0x0C,
    LEFT_LEFT_DOWN   = 0x0D,
    LEFT_LEFT_UP     = 0x0E,
    LEFT_UP_UP       = 0x0F,
};

}  // namespace ostinato
