// AUTO-GENERATED by tools/asm_parser/parse_npc_prop.py — DO NOT EDIT.
// Regenerate from original-src (pinned at 1ea47b5); hand edits will be lost.
// Source: original-src/include/event_cmd.inc  (ca65 .enum EVENT_VEHICLE)
#pragma once

#include <cstdint>

// Which vehicle an NPC rides (npc_prop byte 7 bits 6-7 on normal records).
// SHOW_RIDER ($80) is a separate bit, surfaced as the show-rider flag, not
// a vehicle; HIDE_RIDER is an alias of NONE.
namespace ostinato {

enum class EventVehicle : std::uint8_t {
    NONE    = 0x00,
    CHOCOBO = 0x20,
    MAGITEK = 0x40,
    RAFT    = 0x60,
};

}  // namespace ostinato
