// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum EVENT_OBJ)
#pragma once

#include <cstdint>

namespace ostinato {

enum class EventObjId : std::uint8_t {
    TERRA        = 0x00,  // == CharacterId::TERRA
    LOCKE        = 0x01,  // == CharacterId::LOCKE
    CYAN         = 0x02,  // == CharacterId::CYAN
    SHADOW       = 0x03,  // == CharacterId::SHADOW
    EDGAR        = 0x04,  // == CharacterId::EDGAR
    SABIN        = 0x05,  // == CharacterId::SABIN
    CELES        = 0x06,  // == CharacterId::CELES
    STRAGO       = 0x07,  // == CharacterId::STRAGO
    RELM         = 0x08,  // == CharacterId::RELM
    SETZER       = 0x09,  // == CharacterId::SETZER
    MOG          = 0x0A,  // == CharacterId::MOG
    GAU          = 0x0B,  // == CharacterId::GAU
    GOGO         = 0x0C,  // == CharacterId::GOGO
    UMARO        = 0x0D,  // == CharacterId::UMARO
    KUPEK        = 0x02,  // == CharacterId::KUPEK
    KUPOP        = 0x03,  // == CharacterId::KUPOP
    KUMAMA       = 0x04,  // == CharacterId::KUMAMA
    KUKU         = 0x05,  // == CharacterId::KUKU
    KUTAN        = 0x06,  // == CharacterId::KUTAN
    KUPAN        = 0x07,  // == CharacterId::KUPAN
    KUSHU        = 0x08,  // == CharacterId::KUSHU
    KURIN        = 0x09,  // == CharacterId::KURIN
    KURU         = 0x0B,  // == CharacterId::KURU
    KAMOG        = 0x0C,  // == CharacterId::KAMOG
    GHOST_1      = 0x07,  // == CharacterId::GHOST_1
    GHOST_2      = 0x08,  // == CharacterId::GHOST_2
    SCENARIO_MOG = 0x0D,  // == CharacterId::SCENARIO_MOG
    WEDGE        = 0x0E,  // == CharacterId::WEDGE
    BANON        = 0x0E,  // == CharacterId::BANON
    MADUIN       = 0x0E,  // == CharacterId::MADUIN
    VICKS        = 0x0F,  // == CharacterId::VICKS
    LEO          = 0x0F,  // == CharacterId::LEO
    KEFKA        = 0x0F,  // == CharacterId::KEFKA
    NPC_1        = 0x10,
    NPC_2        = 0x11,
    NPC_3        = 0x12,
    NPC_4        = 0x13,
    NPC_5        = 0x14,
    NPC_6        = 0x15,
    NPC_7        = 0x16,
    NPC_8        = 0x17,
    NPC_9        = 0x18,
    NPC_10       = 0x19,
    NPC_11       = 0x1A,
    NPC_12       = 0x1B,
    NPC_13       = 0x1C,
    NPC_14       = 0x1D,
    NPC_15       = 0x1E,
    NPC_16       = 0x1F,
    NPC_17       = 0x20,
    NPC_18       = 0x21,
    NPC_19       = 0x22,
    NPC_20       = 0x23,
    NPC_21       = 0x24,
    NPC_22       = 0x25,
    NPC_23       = 0x26,
    NPC_24       = 0x27,
    NPC_25       = 0x28,
    NPC_26       = 0x29,
    NPC_27       = 0x2A,
    NPC_28       = 0x2B,
    NPC_29       = 0x2C,
    NPC_30       = 0x2D,
    NPC_31       = 0x2E,
    NPC_32       = 0x2F,
    CAMERA       = 0x30,
    SLOT_1       = 0x31,
    SLOT_2       = 0x32,
    SLOT_3       = 0x33,
    SLOT_4       = 0x34,
};

}  // namespace ostinato
