// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (file-scope constants)
//
// The ceilings the game counts against. Each is a 24-bit quantity
// in the original, read a byte at a time; a counter that reaches
// its limit stops there rather than wrapping.
#pragma once

#include <cstdint>

namespace ostinato {

// The most gil the party can hold.
inline constexpr std::uint32_t kMaxGil = 9999999;

// The most steps the step counter records.
inline constexpr std::uint32_t kMaxSteps = 9999999;

// The most experience a character can accumulate.
inline constexpr std::uint32_t kMaxExperience = 15000000;

}  // namespace ostinato
