// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum ITEM_TYPE)
#pragma once

#include <cstdint>

namespace ostinato {

enum class ItemType : std::uint8_t {
    TOOL       = 0x00,
    WEAPON     = 0x01,
    ARMOR      = 0x02,
    SHIELD     = 0x03,
    HELMET     = 0x04,
    RELIC      = 0x05,
    CONSUMABLE = 0x06,
};

}  // namespace ostinato
