// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum ITEM_USAGE)
#pragma once

#include <cstdint>

namespace ostinato {

enum class ItemUsage : std::uint8_t {
    THROW  = 0x10,
    BATTLE = 0x20,
    MENU   = 0x40,
};

}  // namespace ostinato
