// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum CHAR_LEVEL_MOD)
#pragma once

#include <cstdint>

namespace ostinato {

enum class LevelMod : std::uint8_t {
    NORMAL    = 0x00,
    HIGH      = 0x04,
    VERY_HIGH = 0x08,
    LOW       = 0x0C,
    MASK      = 0x0C,
};

}  // namespace ostinato
