// AUTO-GENERATED by tools/asm_parser/parse_npc_prop.py — DO NOT EDIT.
// Regenerate from original-src (pinned at 1ea47b5); hand edits will be lost.
// Source: original-src/include/gfx/map_sprite_pal.inc  (ca65 .enum MAP_SPRITE_PAL)
#pragma once

#include <cstdint>

// A field NPC's palette (npc_prop byte 2 bits 2-4). Eight base palettes
// (0-7); the many aliases name the per-sprite default a palette-less
// set_npc_gfx picks (LOCKE = MERCHANT = BROWN_SOLDIER = 1, etc.).
namespace ostinato {

enum class MapSpritePal : std::uint8_t {
    EDGAR_SABIN_CELES       = 0x00,
    EDGAR                   = EDGAR_SABIN_CELES,
    SABIN                   = EDGAR_SABIN_CELES,
    CELES                   = EDGAR_SABIN_CELES,
    IMP                     = EDGAR_SABIN_CELES,
    LEO                     = EDGAR_SABIN_CELES,
    GHOST                   = EDGAR_SABIN_CELES,
    GREEN_SOLDIER           = EDGAR_SABIN_CELES,
    LOCKE                   = 0x01,
    MERCHANT                = LOCKE,
    BROWN_SOLDIER           = LOCKE,
    TERRA                   = 0x02,
    STRAGO_RELM_GAU_GOGO    = 0x03,
    STRAGO                  = STRAGO_RELM_GAU_GOGO,
    RELM                    = STRAGO_RELM_GAU_GOGO,
    GAU                     = STRAGO_RELM_GAU_GOGO,
    GOGO                    = STRAGO_RELM_GAU_GOGO,
    BANON                   = STRAGO_RELM_GAU_GOGO,
    KEFKA                   = STRAGO_RELM_GAU_GOGO,
    GESTAHL                 = STRAGO_RELM_GAU_GOGO,
    CYAN_SHADOW_SETZER      = 0x04,
    CYAN                    = CYAN_SHADOW_SETZER,
    SHADOW                  = CYAN_SHADOW_SETZER,
    SETZER                  = CYAN_SHADOW_SETZER,
    MOG_UMARO               = 0x05,
    MOG                     = MOG_UMARO,
    UMARO                   = MOG_UMARO,
    RAINBOW                 = 0x06,
    VEHICLE                 = 0x07,
    ESPER_TERRA             = 0x08,
    EDGAR_SABIN_CELES_ALT   = 0x09,
    MACHINERY_1             = 0x0A,
    RAFT                    = 0x0B,
    MACHINERY_2             = 0x0C,
    GUARDIAN                = 0x0D,
    SEALED_GATE             = 0x0E,
    VECTOR_CRANE            = 0x0F,
    STATUE_SMOKE            = 0x10,
    TREASURE_CHEST          = 0x11,
    CHADARNOOK              = 0x12,
    ROCK                    = 0x13,
    FALCON                  = 0x14,
    ODIN                    = 0x15,
    KEFKAS_TOWER_PARALLAX_1 = 0x16,
    KEFKAS_TOWER_PARALLAX_2 = 0x17,
    KEFKAS_TOWER_PARALLAX_3 = 0x18,
    DADALUMA                = 0x19,
    GREEN_MAGICITE_SMOKE    = 0x1A,
    UNUSED_27               = 0x1B,
    UNUSED_28               = 0x1C,
    AIRSHIP_PARALLAX        = 0x1D,
    UNUSED_30               = 0x1E,
    UNUSED_31               = 0x1F,
};

}  // namespace ostinato
