// AUTO-GENERATED by tools/asm_parser/parse_npc_prop.py — DO NOT EDIT.
// Regenerate from original-src (pinned at 1ea47b5); hand edits will be lost.
// Source: original-src/include/event/npc_prop.inc  (ca65 .enum NPC_ANIM_FRAME)
#pragma once

#include <cstdint>

// An animated NPC's frame mode (npc_prop byte 8 bits 5-7). A nonzero value
// marks the record as animated. The value is the packed field.
namespace ostinato {

enum class NpcAnimFrame : std::uint8_t {
    DEFAULT     = 0x00,
    NONE        = 0x20,
    SPECIAL     = 0x40,
    KNOCKED_OUT = 0x60,
};

}  // namespace ostinato
