// AUTO-GENERATED by tools/asm_parser/parse_npc_prop.py — DO NOT EDIT.
// Regenerate from original-src (pinned at 1ea47b5); hand edits will be lost.
// Source: original-src/include/event/npc_prop.inc  (ca65 .enum NPC_ANIM_TYPE)
#pragma once

#include <cstdint>

// How an animated NPC cycles frames (npc_prop byte 8 bits 0-1).
namespace ostinato {

enum class NpcAnimType : std::uint8_t {
    ONE_FRAME   = 0x00,
    H_FLIP      = 0x01,
    TWO_FRAMES  = 0x02,
    FOUR_FRAMES = 0x03,
};

}  // namespace ostinato
