// AUTO-GENERATED by tools/asm_parser/parse_npc_prop.py — DO NOT EDIT.
// Regenerate from original-src (pinned at 1ea47b5); hand edits will be lost.
// Source: original-src/include/event/npc_prop.inc  (ca65 .enum NPC_REACT)
#pragma once

#include <cstdint>

// Whether an NPC turns to face the player when activated (npc_prop byte 8
// bit 2). The value is the packed bit.
namespace ostinato {

enum class NpcReact : std::uint8_t {
    FACE_PLAYER = 0x00,
    NONE        = 0x04,
};

}  // namespace ostinato
