// AUTO-GENERATED by tools/asm_parser/parse_npc_prop.py — DO NOT EDIT.
// Regenerate from original-src (pinned at 1ea47b5); hand edits will be lost.
// Source: original-src/include/event/npc_prop.inc  (ca65 .enum NPC_LAYER_PRIORITY)
#pragma once

#include <cstdint>

// Sprite-vs-background layer priority (npc_prop byte 8 bits 3-4). The
// value is the packed field (already shifted into bits 3-4).
namespace ostinato {

enum class NpcLayerPriority : std::uint8_t {
    DEFAULT         = 0x00,
    TOP_SPRITE_ONLY = 0x08,
    FOREGROUND      = 0x10,
    BACKGROUND      = 0x18,
};

}  // namespace ostinato
