// AUTO-GENERATED by tools/asm_parser/parse_npc_prop.py — DO NOT EDIT.
// Regenerate from original-src (pinned at 1ea47b5); hand edits will be lost.
// Source: original-src/include/event/npc_prop.inc  (ca65 .enum NPC_MOVEMENT)
#pragma once

#include <cstdint>

// An NPC's autonomous movement behaviour (npc_prop byte 7 bits 0-3).
namespace ostinato {

enum class NpcMovement : std::uint8_t {
    NONE   = 0x00,
    SCRIPT = 0x01,
    PLAYER = 0x02,
    RANDOM = 0x03,
    ACTIVE = 0x04,
};

}  // namespace ostinato
