// AUTO-GENERATED by tools/asm_parser/parse_npc_prop.py — DO NOT EDIT.
// Regenerate from original-src (pinned at 1ea47b5); hand edits will be lost.
// Source: original-src/include/event/npc_prop.inc  (ca65 .enum NPC_MASTER_OFFSET_DIR)
#pragma once

#include <cstdint>

// Which way a special NPC's slave sprite is offset from its master
// (npc_prop byte 2 bit 0).
namespace ostinato {

enum class NpcMasterOffsetDir : std::uint8_t {
    RIGHT = 0x00,
    DOWN  = 0x01,
};

}  // namespace ostinato
