// AUTO-GENERATED by tools/asm_parser/parse_npc_prop.py — DO NOT EDIT.
// Regenerate from original-src (pinned at 1ea47b5); hand edits will be lost.
// Source: original-src/include/event/npc_prop.inc  (ca65 .enum NPC_SCROLL)
#pragma once

#include <cstdint>

// Which background layer an NPC scrolls with (npc_prop byte 2 bit 5).
// BG1 is the default; the value is the packed bit, not a logical 0/1.
namespace ostinato {

enum class NpcScroll : std::uint8_t {
    BG1 = 0x00,
    BG2 = 0x20,
};

}  // namespace ostinato
