// AUTO-GENERATED by tools/asm_parser/parse_npc_prop.py — DO NOT EDIT.
// Regenerate from original-src (pinned at 1ea47b5); hand edits will be lost.
// Source: original-src/include/event/npc_prop.inc  (ca65 .enum NPC_ANIM_SPEED)
#pragma once

#include <cstdint>

// An animated NPC's frame rate (npc_prop byte 7 bits 6-7, non-special
// animated records only). The value is the packed field.
namespace ostinato {

enum class NpcAnimSpeed : std::uint8_t {
    FASTEST = 0x00,
    FAST    = 0x40,
    MEDIUM  = 0x80,
    SLOW    = 0xC0,
};

}  // namespace ostinato
