// AUTO-GENERATED by tools/asm_parser/parse_npc_prop.py — DO NOT EDIT.
// Regenerate from original-src (pinned at 1ea47b5); hand edits will be lost.
// Source: original-src/include/event/npc_prop.inc  (ca65 .enum NPC_SPRITE_PRIORITY)
#pragma once

#include <cstdint>

// Sprite-vs-sprite draw priority (npc_prop byte 7 bits 4-5). The value is
// the packed field (already shifted into bits 4-5).
namespace ostinato {

enum class NpcSpritePriority : std::uint8_t {
    NORMAL = 0x00,
    HIGH   = 0x10,
    LOW    = 0x20,
};

}  // namespace ostinato
