// AUTO-GENERATED by tools/asm_parser/parse_blitz_code.py
// Source: original-src/include/hardware.inc (JOY_* button masks)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_blitz_code.py \
//       --source-root  original-src
//
// The twelve inputs of the game's controller. Each enumerator is the
// input's bit in a 16-bit button mask, so a set of inputs is the OR
// of its members.
#pragma once

#include <cstdint>

namespace ostinato {

enum class PadInput : std::uint16_t {
    A      = 0x0080,
    X      = 0x0040,
    L      = 0x0020,
    R      = 0x0010,
    B      = 0x8000,
    Y      = 0x4000,
    SELECT = 0x2000,
    START  = 0x1000,
    UP     = 0x0800,
    DOWN   = 0x0400,
    LEFT   = 0x0200,
    RIGHT  = 0x0100,
};

}  // namespace ostinato
