// AUTO-GENERATED by tools/asm_parser/parse_rom_regions.py
// Source: tools/extract_assets.py:323-331 (the CRC32 branches)
// Source: cfg/ff6-en.cfg (the ROM bank extent)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_rom_regions.py \
//       --source-root original-src --repo-root .

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

#include "ostinato/game_version.h"

namespace ostinato {

// The size of a headerless image. Every supported revision is this
// long, so a file of any other size is not one of them.
inline constexpr std::size_t kRomSizeBytes = 3145728;

// Some dumps carry a copier header ahead of the image. It is not
// part of the cartridge and is dropped before anything reads or
// identifies the bytes.
inline constexpr std::size_t kCopierHeaderBytes = 512;

// One supported revision and the CRC32 of its headerless image.
struct RomIdentityEntry {
    GameVersion   version;
    std::uint32_t crc32;
};

// The revisions this port accepts, in GameVersion order.
inline constexpr std::array<RomIdentityEntry, 3>
kRomIdentities = {{
    { .version = GameVersion::JP_1_0, .crc32 = 0x45EF5AC8 },
    { .version = GameVersion::US_1_0, .crc32 = 0xA27F1C7A },
    { .version = GameVersion::US_1_1, .crc32 = 0xC0FA0464 },
}};

}  // namespace ostinato
