// AUTO-GENERATED by tools/asm_parser/parse_rom_regions.py
// Source: tools/rip_list_{en,jp}.json (the asset tables extract_assets.py walks)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_rom_regions.py \
//       --source-root original-src --repo-root .

#pragma once

#include <cstddef>
#include <cstdint>

// Every content family the cartridge holds. The id names WHAT a
// family is; where it lives differs per language, so an address
// comes from romRegion(asset, language) (src/data/rom_regions.h)
// rather than from the id itself.
//
// A family is identified by the file the upstream rip writes for
// it, so a graphics blob and its palette are separate ids even
// where they share a name. Ids are dense and stable in the order
// below; nothing persists them, so the order is free to grow.
namespace ostinato {

enum class RomAsset : std::uint8_t {
    // The script: name tables, dialogue banks, descriptions, and the
    // DTE pair table. Every one is language-specific.
    ATTACK_MSG,
    ATTACK_NAME,
    BATTLE_CMD_NAME,
    BATTLE_DLG,
    BLITZ_DESC,
    BUSHIDO_DESC,
    BUSHIDO_NAME,
    CHAR_NAME,
    DANCE_NAME,
    DLG1,
    DLG2,
    MTE_TBL,
    DTE_TBL,
    GENJU_ATTACK_DESC,
    GENJU_ATTACK_NAME,
    GENJU_BONUS_DESC,
    GENJU_BONUS_NAME,
    GENJU_NAME,
    ITEM_DESC,
    ITEM_NAME,
    ITEM_TYPE_NAME,
    LORE_DESC,
    MAGIC_DESC,
    MAGIC_NAME,
    MAP_TITLE,
    MONSTER_DLG,
    MONSTER_NAME,
    MONSTER_SPECIAL_NAME,
    RARE_ITEM_DESC,
    RARE_ITEM_NAME,
    STATUS_NAME,
    CHAR_TITLE,

    // Graphics, palettes, tile sheets, sound samples, and the numeric
    // tables the game reads directly.
    AIRSHIP1,
    AIRSHIP2,
    ATTACK_GFX_2BPP,
    ATTACK_GFX_3BPP,
    ATTACK_MODE7_GFX,
    ATTACK_2BPP,
    ATTACK_3BPP,
    ATTACK_MODE7_TILEMAP,
    ATTACK_PAL,
    BATTLE_BG_GFX,
    BATTLE_BG_TILES,
    BATTLE_BG_PAL,
    BATTLE_CHAR_PAL,
    BATTLE_FONT_PAL,
    CREDITS,
    DEBUG_FONT,
    ENDING_AIRSHIP,
    ENDING_FONT,
    ENDING1,
    ENDING2,
    ENDING3,
    ENDING4,
    ENDING5,
    FLOATING_CONT,
    FONT_PAL,
    SMALL_FONT,
    LARGE_FONT,
    MAGITEK_TRAIN_GFX,
    MAGITEK_TRAIN_PAL,
    MAP_ANIM,
    MAP_ANIM_GFX_BG3,
    MAP_GFX,
    MAP_GFX_BG3,
    MAP_PAL,
    MAP_PAL_ANIM,
    MAP_SPRITE_GFX,
    MAP_SPRITE_PAL,
    MENU_PAL,
    MENU_SPRITE,
    MINIMAP_1,
    MINIMAP_2,
    MONSTER_GFX_TRIMMED,
    MONSTER_STENCIL_SMALL,
    MONSTER_STENCIL_LARGE,
    MONSTER_GFX_PAL,
    MAP_OVERLAY,
    PORTRAIT_GFX,
    PORTRAIT_PAL,
    RUIN_CUTSCENE,
    SLOT,
    STATUS,
    THE_END_1,
    THE_END_2,
    THE_END,
    TITLE_OPENING,
    VECTOR_APPROACH_GFX,
    VECTOR_APPROACH_PAL,
    VECTOR_APPROACH_TILEMAP,
    VEHICLE,
    WINDOW_GFX,
    WINDOW_PAL,
    WORLD_BACKDROP_GFX,
    WORLD_BACKDROP_TILEMAP,
    WORLD_1_BG_PAL,
    WORLD_2_BG_PAL,
    WORLD_3,
    WORLD_ESPER_TERRA,
    WORLD_CHOCO_1,
    WORLD_CHOCO_2,
    WORLD_1_BG_GFX,
    WORLD_2_BG_GFX,
    WORLD_3_BG,
    WORLD_ANIM_SPRITE,
    WORLD_MISC_SPRITE,
    WORLD_1_SPRITE,
    WORLD_2_SPRITE,
    ATTACK_GFX_PROP,
    BATTLE_MAGIC_POINTS,
    MONSTER_PROP,
    MONSTER_SPECIAL_ANIM,
    BATTLE_MONSTERS,
    BATTLE_PROP,
    COND_BATTLE,
    INIT_NPC_SWITCH,
    EVENT_BATTLE_GROUP,
    RAND_BATTLE_GROUP,
    SUB_BATTLE_GROUP,
    SUB_BATTLE_RATE,
    WORLD_BATTLE_GROUP,
    WORLD_BATTLE_RATE,
    RNG_TBL,
    CUTSCENE,
    ITEM_PROP,
    MAGITEK_TRAIN_TILES,
    WORLD_1_MOD,
    WORLD_2_MOD,
    WORLD_MOD_TILES,
    MAP_PROP,
    ATTACK_ANIM_PROP,
    MONSTER_ALIGN,
    MONSTER_ATTACK_ANIM_PROP,
    ITEM_JUMP_THROW_ANIM,
    WEAPON_ANIM_PROP,
    MAP_PAL_ANIM_PROP,
    MAP_PARALLAX,
    MAP_TILE_PROP,
    MAP_TILESET,
    OVERLAY_PROP,
    OVERLAY_TILEMAP,
    SUB_TILEMAP,
    WORLD_1_TILEMAP,
    WORLD_2_TILEMAP,
    WORLD_3_TILEMAP,
    MAGIC_PROP,
    METAMORPH_PROP,
    SHOP_PROP,
    SAMPLE_BRR,
    SFX_BRR,

    // Pointer-indexed arrays: a table of offsets followed by the
    // variable-length records it addresses.
    ATTACK_ANIM_FRAMES,
    ATTACK_ANIM_SCRIPT,
    BATTLE_EVENT_SCRIPT,
    LONG_ENTRANCE,
    SHORT_ENTRANCE,
    TREASURE_PROP,
};

// How many families there are. The region table's asset column
// never exceeds this.
inline constexpr std::size_t kRomAssetCount = 156;

}  // namespace ostinato
