// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum CHAR_RUN_FACTOR)
#pragma once

#include <cstdint>

namespace ostinato {

enum class RunFactor : std::uint8_t {
    HIGH     = 0x00,
    NORMAL   = 0x01,
    LOW      = 0x02,
    VERY_LOW = 0x03,
    MASK     = 0x03,
};

}  // namespace ostinato
