// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum TARGET)
#pragma once

#include <cstdint>

namespace ostinato {

enum class TargetFlags : std::uint8_t {
    MANUAL       = 0x01,
    ONE_SIDE     = 0x02,
    INIT_MASK    = 0x0C,
    INIT_SINGLE  = 0x00,
    INIT_ALL     = 0x04,
    INIT_GROUP   = 0x08,
    INIT_HALF    = 0x0C,
    AUTO_CONFIRM = 0x10,
    MULTI_TARGET = 0x20,
    ENEMY        = 0x40,
    ROULETTE     = 0x80,
    SELF         = 0x02,
    MENU         = 0xFF,
};

}  // namespace ostinato
