// AUTO-GENERATED by tools/asm_parser/parse_train_data.py — DO NOT EDIT BY HAND
// Source: world/train_script.asm:535 (chrset, ROM ee/2a92)
// Regenerate via:
//   python3 tools/asm_parser/parse_train_data.py \
//       --source-root original-src --repo-root .
#pragma once

#include <cstdint>

namespace ostinato {

// Which set of tunnel scenery the Magitek train runs through over a
// script step. The script's background byte picks one of these, and
// the curve it names supplies one tile arrangement per frame.
enum class TrainBackgroundType : std::uint8_t {
    PIPES_MORE_BEAMS        =  0,  // pipes w/ more beams
    PIPES_FEWER_BEAMS       =  1,  // pipes w/ fewer beams
    NO_PIPES                =  2,  // no pipes
    SPLIT_TRACK_MORE_WALLS  =  3,  // split track w/ more walls
    SPLIT_TRACK_FEWER_WALLS =  4,  // split track w/ fewer walls
};

}  // namespace ostinato
