// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Source: original-src/include/const.inc  (ca65 .enum WEAPON_FLAG)
#pragma once

#include <cstdint>

namespace ostinato {

enum class WeaponFlags : std::uint8_t {
    SWDTECH  = 0x02,
    BACK_ROW = 0x20,
    TWO_HAND = 0x40,
    RUNIC    = 0x80,
};

}  // namespace ostinato
