// AUTO-GENERATED by tools/asm_parser/parse_world_anim.py
// Source: world/world_anim.asm (the frame labels and their group headings)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_world_anim.py \
//       --source-root original-src --repo-root .

#pragma once

#include <cstddef>
#include <cstdint>

// Which world-map animation frame to draw.
//
// A frame is one arrangement of hardware sprites — the airship seen
// from a particular angle, a step of the chocobo's gait, the party
// leader facing left. The arrangements themselves live in the
// cartridge (RomAsset::WORLD_ANIM_FRAMES); this names them.
//
// The names are positions, not descriptions. The cartridge labels
// groups of frames and never an individual one, so naming each
// frame would be inventing meaning the game does not state. The
// group headings ride along as comments, and better names are
// welcome once the drawing code makes each frame's use plain.
// They are quoted as the cartridge source writes them, so any
// frame number inside a heading is hexadecimal while the
// enumerators here count in decimal.
//
// FRAME_0 is the blank frame: it stores nothing, and both world draw
// routines skip an object showing it (world/sprite.asm:423-489,
// :495-554).
namespace ostinato {

enum class WorldAnimFrameId : std::uint8_t {
    // no animation
    FRAME_0 = 0,

    // airship
    FRAME_1 = 1,
    FRAME_2 = 2,
    FRAME_3 = 3,
    FRAME_4 = 4,
    FRAME_5 = 5,
    FRAME_6 = 6,
    FRAME_7 = 7,
    FRAME_8 = 8,
    FRAME_9 = 9,
    FRAME_10 = 10,
    FRAME_11 = 11,
    FRAME_12 = 12,
    FRAME_13 = 13,
    FRAME_14 = 14,
    FRAME_15 = 15,
    FRAME_16 = 16,
    FRAME_17 = 17,
    FRAME_18 = 18,

    // chocobo
    FRAME_19 = 19,
    FRAME_20 = 20,
    FRAME_21 = 21,
    FRAME_22 = 22,
    FRAME_23 = 23,
    FRAME_24 = 24,

    // chocobo (turning right)
    FRAME_25 = 25,
    FRAME_26 = 26,
    FRAME_27 = 27,
    FRAME_28 = 28,
    FRAME_29 = 29,
    FRAME_30 = 30,

    // chocobo (turning left)
    FRAME_31 = 31,
    FRAME_32 = 32,
    FRAME_33 = 33,
    FRAME_34 = 34,
    FRAME_35 = 35,
    FRAME_36 = 36,

    // chocobo (not moving)
    FRAME_37 = 37,

    // character
    FRAME_38 = 38,
    FRAME_39 = 39,
    FRAME_40 = 40,
    FRAME_41 = 41,

    // character (bottom sprites transparent)
    FRAME_42 = 42,
    FRAME_43 = 43,
    FRAME_44 = 44,
    FRAME_45 = 45,
    FRAME_46 = 46,
    FRAME_47 = 47,
    FRAME_48 = 48,
    FRAME_49 = 49,
    FRAME_50 = 50,
    FRAME_51 = 51,
    FRAME_52 = 52,
    FRAME_53 = 53,
    FRAME_54 = 54,

    // ship
    FRAME_55 = 55,
    FRAME_56 = 56,
    FRAME_57 = 57,
    FRAME_58 = 58,
    FRAME_59 = 59,
    FRAME_60 = 60,
    FRAME_61 = 61,
    FRAME_62 = 62,

    // flashing arrows for serpent trench
    FRAME_63 = 63,
    FRAME_64 = 64,
    FRAME_65 = 65,
    FRAME_66 = 66,
    FRAME_67 = 67,
    FRAME_68 = 68,

    // blackjack (grounded)
    FRAME_69 = 69,
    FRAME_70 = 70,
    FRAME_71 = 71,
    FRAME_72 = 72,

    // dismounting chocobo
    FRAME_73 = 73,
    FRAME_74 = 74,
    FRAME_75 = 75,
    FRAME_76 = 76,

    // blackjack lifting off (2nd frame with $47)
    FRAME_77 = 77,

    // esper terra
    FRAME_78 = 78,
    FRAME_79 = 79,
    FRAME_80 = 80,
    FRAME_81 = 81,
    FRAME_82 = 82,
    FRAME_83 = 83,
    FRAME_84 = 84,
    FRAME_85 = 85,

    // smoking airship
    FRAME_86 = 86,
    FRAME_87 = 87,
    FRAME_88 = 88,
    FRAME_89 = 89,
    FRAME_90 = 90,
    FRAME_91 = 91,
    FRAME_92 = 92,
    FRAME_93 = 93,
    FRAME_94 = 94,

    // bird
    FRAME_95 = 95,
    FRAME_96 = 96,
    FRAME_97 = 97,

    // falcon (grounded)
    FRAME_98 = 98,
    FRAME_99 = 99,
    FRAME_100 = 100,
    FRAME_101 = 101,

    // falcon lifting off (2nd frame with $64)
    FRAME_102 = 102,
    FRAME_103 = 103,
    FRAME_104 = 104,
    FRAME_105 = 105,
    FRAME_106 = 106,
    FRAME_107 = 107,
};

// How many frames there are.
inline constexpr std::size_t kWorldAnimFrameCount = 108;

}  // namespace ostinato
