// AUTO-GENERATED by tools/asm_parser/parse_battle_cmd_prop.py — DO NOT EDIT.
// (original-src pinned at 1ea47b5) — DO NOT EDIT BY HAND.
#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// Ground-truth BattleCmdProp rows, all 32 ROM slots (.index = raw
// position, .bytes = the two ROM bytes: [0] command flags, [1] target
// flags). Slots 30/31 ($1E/$1F) are the unused NONE/MENU padding.
struct ExpectedBattleCmdProp {
    std::uint8_t index;
    std::array<std::uint8_t, 2> bytes;
};

inline constexpr std::array<ExpectedBattleCmdProp, 32> kExpectedBattleCmdProp = {{
    { .index =  0, .bytes = { 0x0F, 0x41 } },
    { .index =  1, .bytes = { 0x07, 0xFF } },
    { .index =  2, .bytes = { 0x07, 0xFF } },
    { .index =  3, .bytes = { 0x00, 0x02 } },
    { .index =  4, .bytes = { 0x04, 0x02 } },
    { .index =  5, .bytes = { 0x0B, 0x43 } },
    { .index =  6, .bytes = { 0x0B, 0x43 } },
    { .index =  7, .bytes = { 0x03, 0xFF } },
    { .index =  8, .bytes = { 0x03, 0xFF } },
    { .index =  9, .bytes = { 0x03, 0xFF } },
    { .index = 10, .bytes = { 0x03, 0xFF } },
    { .index = 11, .bytes = { 0x03, 0x02 } },
    { .index = 12, .bytes = { 0x03, 0xFF } },
    { .index = 13, .bytes = { 0x03, 0x43 } },
    { .index = 14, .bytes = { 0x01, 0x43 } },
    { .index = 15, .bytes = { 0x03, 0xFF } },
    { .index = 16, .bytes = { 0x0B, 0xFF } },
    { .index = 17, .bytes = { 0x00, 0x02 } },
    { .index = 18, .bytes = { 0x05, 0x02 } },
    { .index = 19, .bytes = { 0x03, 0xFF } },
    { .index = 20, .bytes = { 0x04, 0xFF } },
    { .index = 21, .bytes = { 0x04, 0xFF } },
    { .index = 22, .bytes = { 0x05, 0x43 } },
    { .index = 23, .bytes = { 0x07, 0xFF } },
    { .index = 24, .bytes = { 0x03, 0x6A } },
    { .index = 25, .bytes = { 0x03, 0xFF } },
    { .index = 26, .bytes = { 0x06, 0x2E } },
    { .index = 27, .bytes = { 0x06, 0x6E } },
    { .index = 28, .bytes = { 0x01, 0x43 } },
    { .index = 29, .bytes = { 0x0A, 0xFF } },
    { .index = 30, .bytes = { 0x00, 0xFF } },
    { .index = 31, .bytes = { 0x00, 0xFF } },
}};

}  // namespace ostinato::test
