// AUTO-GENERATED by tools/asm_parser/parse_battle_bg.py
// Source: src/gfx/battle_bg.asm (BattleBGProp, 56 records x 6 bytes,
//         ROM $E7/0000)
// Source: include/gfx/battle_bg.inc (BATTLE_BG / BATTLE_BG_GFX /
//         BATTLE_BG_TILES / BATTLE_BG_PAL values)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_battle_bg.py \
//       --source-root  original-src

// Test fixture for tests/test_battle_backgrounds.cpp — the
// ground-truth record bytes. The full-corpus test asserts, per
// entry: fixture id == position, table id enumerator == position,
// and a 6-byte memcmp of the packed record against
// src/data/generated/battle_bg_prop_data.inc's row.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 6-byte BattleBGProp record; field names and order mirror
// battle_bg.asm:31-36. Values are the exact ROM bytes with every upstream
// symbol resolved and the bit-7 flags folded in — deliberately independent
// of the enum-symbol rows in battle_bg_prop_data.inc, so symbol/value
// drift in either artifact fails the full-corpus byte-equivalence test.
struct ExpectedBattleBackgroundRecord {
    std::uint8_t graphics1;  // BATTLE_BG_GFX | bit 7: 128-tile form
    std::uint8_t graphics2;  // BATTLE_BG_GFX
    std::uint8_t graphics3;  // BATTLE_BG_GFX
    std::uint8_t tilemap1;   // BATTLE_BG_TILES
    std::uint8_t tilemap2;   // BATTLE_BG_TILES (unused by the loader)
    std::uint8_t palette;    // BATTLE_BG_PAL | bit 7: wavy HDMA effect
};
static_assert(sizeof(ExpectedBattleBackgroundRecord) == 6,
              "fixture record must stay byte-identical to a ROM "
              "BattleBGProp record");

// One fixture entry: the record's identity as a typed field (raw decimal
// index — the fixture stays independent of the port's BattleBackgroundId
// header) alongside the raw record bytes.
struct ExpectedBattleBackgroundEntry {
    std::uint8_t id;
    ExpectedBattleBackgroundRecord record;
};

inline constexpr std::array<ExpectedBattleBackgroundEntry, 56>
    kExpectedBattleBackgroundEntries = {{  // ROM BattleBGProp
    { .id =  0,  // $00 FIELD_WOB
      .record = { .graphics1 = 0x12, .graphics2 = 0x13, .graphics3 = 0x14,
                  .tilemap1 = 0x00, .tilemap2 = 0x00, .palette = 0x00 } },
    { .id =  1,  // $01 FOREST_WOR
      .record = { .graphics1 = 0x9A, .graphics2 = 0xFF, .graphics3 = 0x19,
                  .tilemap1 = 0x0C, .tilemap2 = 0x0C, .palette = 0x31 } },
    { .id =  2,  // $02 DESERT_WOB
      .record = { .graphics1 = 0x18, .graphics2 = 0x1D, .graphics3 = 0xFF,
                  .tilemap1 = 0x0B, .tilemap2 = 0x0B, .palette = 0x8B } },
    { .id =  3,  // $03 FOREST_WOB
      .record = { .graphics1 = 0x9A, .graphics2 = 0xFF, .graphics3 = 0x19,
                  .tilemap1 = 0x0C, .tilemap2 = 0x0C, .palette = 0x0C } },
    { .id =  4,  // $04 ZOZO_INT
      .record = { .graphics1 = 0xB0, .graphics2 = 0xFF, .graphics3 = 0x2F,
                  .tilemap1 = 0x21, .tilemap2 = 0x21, .palette = 0x23 } },
    { .id =  5,  // $05 FIELD_WOR
      .record = { .graphics1 = 0x12, .graphics2 = 0x14, .graphics3 = 0x1B,
                  .tilemap1 = 0x0D, .tilemap2 = 0x0D, .palette = 0x0D } },
    { .id =  6,  // $06 VELDT
      .record = { .graphics1 = 0x12, .graphics2 = 0x14, .graphics3 = 0x1C,
                  .tilemap1 = 0x0E, .tilemap2 = 0x0E, .palette = 0x0E } },
    { .id =  7,  // $07 CLOUDS
      .record = { .graphics1 = 0x37, .graphics2 = 0x38, .graphics3 = 0xFF,
                  .tilemap1 = 0x1F, .tilemap2 = 0x1F, .palette = 0x26 } },
    { .id =  8,  // $08 NARSHE_EXT
      .record = { .graphics1 = 0xFF, .graphics2 = 0x00, .graphics3 = 0x01,
                  .tilemap1 = 0x01, .tilemap2 = 0x01, .palette = 0x01 } },
    { .id =  9,  // $09 NARSHE_CAVES_1
      .record = { .graphics1 = 0x91, .graphics2 = 0xFF, .graphics3 = 0x09,
                  .tilemap1 = 0x02, .tilemap2 = 0x02, .palette = 0x02 } },
    { .id = 10,  // $0A CAVES
      .record = { .graphics1 = 0x91, .graphics2 = 0xFF, .graphics3 = 0x09,
                  .tilemap1 = 0x03, .tilemap2 = 0x03, .palette = 0x03 } },
    { .id = 11,  // $0B MOUNTAINS_EXT
      .record = { .graphics1 = 0x8B, .graphics2 = 0xFF, .graphics3 = 0x03,
                  .tilemap1 = 0x04, .tilemap2 = 0x04, .palette = 0x04 } },
    { .id = 12,  // $0C MOUNTAINS_INT
      .record = { .graphics1 = 0x8C, .graphics2 = 0xFF, .graphics3 = 0x04,
                  .tilemap1 = 0x05, .tilemap2 = 0x05, .palette = 0x05 } },
    { .id = 13,  // $0D RIVER
      .record = { .graphics1 = 0x8D, .graphics2 = 0xFF, .graphics3 = 0x05,
                  .tilemap1 = 0x06, .tilemap2 = 0x06, .palette = 0x06 } },
    { .id = 14,  // $0E IMP_CAMP
      .record = { .graphics1 = 0x8E, .graphics2 = 0xFF, .graphics3 = 0x06,
                  .tilemap1 = 0x07, .tilemap2 = 0x07, .palette = 0x07 } },
    { .id = 15,  // $0F TRAIN_EXT
      .record = { .graphics1 = 0x15, .graphics2 = 0x0A, .graphics3 = 0x07,
                  .tilemap1 = 0x08, .tilemap2 = 0x08, .palette = 0x08 } },
    { .id = 16,  // $10 TRAIN_INT
      .record = { .graphics1 = 0x90, .graphics2 = 0xFF, .graphics3 = 0x08,
                  .tilemap1 = 0x09, .tilemap2 = 0x09, .palette = 0x09 } },
    { .id = 17,  // $11 NARSHE_CAVES_2
      .record = { .graphics1 = 0x91, .graphics2 = 0xFF, .graphics3 = 0x09,
                  .tilemap1 = 0x03, .tilemap2 = 0x03, .palette = 0x02 } },
    { .id = 18,  // $12 SNOWFIELDS
      .record = { .graphics1 = 0x12, .graphics2 = 0x13, .graphics3 = 0x14,
                  .tilemap1 = 0x0F, .tilemap2 = 0x0F, .palette = 0x0F } },
    { .id = 19,  // $13 TOWN_EXT
      .record = { .graphics1 = 0xFF, .graphics2 = 0x00, .graphics3 = 0x01,
                  .tilemap1 = 0x10, .tilemap2 = 0x10, .palette = 0x10 } },
    { .id = 20,  // $14 IMP_CASTLE
      .record = { .graphics1 = 0xA8, .graphics2 = 0xFF, .graphics3 = 0x1E,
                  .tilemap1 = 0x11, .tilemap2 = 0x11, .palette = 0x11 } },
    { .id = 21,  // $15 FLOATING_ISLAND
      .record = { .graphics1 = 0xA9, .graphics2 = 0xFF, .graphics3 = 0x1F,
                  .tilemap1 = 0x12, .tilemap2 = 0x12, .palette = 0x12 } },
    { .id = 22,  // $16 KEFKAS_TOWER_EXT
      .record = { .graphics1 = 0xAA, .graphics2 = 0xFF, .graphics3 = 0x20,
                  .tilemap1 = 0x13, .tilemap2 = 0x13, .palette = 0x13 } },
    { .id = 23,  // $17 OPERA_STAGE
      .record = { .graphics1 = 0xAB, .graphics2 = 0xFF, .graphics3 = 0x21,
                  .tilemap1 = 0x14, .tilemap2 = 0x14, .palette = 0x14 } },
    { .id = 24,  // $18 OPERA_CATWALK
      .record = { .graphics1 = 0xAB, .graphics2 = 0xFF, .graphics3 = 0x22,
                  .tilemap1 = 0x15, .tilemap2 = 0x15, .palette = 0x15 } },
    { .id = 25,  // $19 BURNING_BUILDING
      .record = { .graphics1 = 0xAC, .graphics2 = 0xFF, .graphics3 = 0x23,
                  .tilemap1 = 0x16, .tilemap2 = 0x16, .palette = 0x96 } },
    { .id = 26,  // $1A CASTLE_INT
      .record = { .graphics1 = 0x24, .graphics2 = 0xFF, .graphics3 = 0xFF,
                  .tilemap1 = 0x17, .tilemap2 = 0x17, .palette = 0x17 } },
    { .id = 27,  // $1B MAGITEK_LAB
      .record = { .graphics1 = 0xA7, .graphics2 = 0xFF, .graphics3 = 0x25,
                  .tilemap1 = 0x18, .tilemap2 = 0x18, .palette = 0x18 } },
    { .id = 28,  // $1C COLOSSEUM
      .record = { .graphics1 = 0x14, .graphics2 = 0x16, .graphics3 = 0xFF,
                  .tilemap1 = 0x19, .tilemap2 = 0x19, .palette = 0x19 } },
    { .id = 29,  // $1D MAGITEK_FACTORY
      .record = { .graphics1 = 0xA7, .graphics2 = 0xFF, .graphics3 = 0x25,
                  .tilemap1 = 0x24, .tilemap2 = 0x24, .palette = 0x18 } },
    { .id = 30,  // $1E VILLAGE_EXT
      .record = { .graphics1 = 0xFF, .graphics2 = 0x00, .graphics3 = 0x01,
                  .tilemap1 = 0x1B, .tilemap2 = 0x1B, .palette = 0x1B } },
    { .id = 31,  // $1F WATERFALL
      .record = { .graphics1 = 0x3C, .graphics2 = 0x00, .graphics3 = 0x00,
                  .tilemap1 = 0x1C, .tilemap2 = 0x1C, .palette = 0x1C } },
    { .id = 32,  // $20 OWZERS_HOUSE
      .record = { .graphics1 = 0xB0, .graphics2 = 0xFF, .graphics3 = 0x2F,
                  .tilemap1 = 0x1D, .tilemap2 = 0x1D, .palette = 0x2B } },
    { .id = 33,  // $21 TRAIN_TRACKS
      .record = { .graphics1 = 0x9A, .graphics2 = 0xFF, .graphics3 = 0x19,
                  .tilemap1 = 0x1E, .tilemap2 = 0x1E, .palette = 0x1E } },
    { .id = 34,  // $22 SEALED_GATE
      .record = { .graphics1 = 0xB3, .graphics2 = 0xFF, .graphics3 = 0x34,
                  .tilemap1 = 0x1A, .tilemap2 = 0x1A, .palette = 0x1A } },
    { .id = 35,  // $23 UNDERWATER
      .record = { .graphics1 = 0x8B, .graphics2 = 0xFF, .graphics3 = 0x32,
                  .tilemap1 = 0x23, .tilemap2 = 0x23, .palette = 0xA4 } },
    { .id = 36,  // $24 ZOZO
      .record = { .graphics1 = 0xB5, .graphics2 = 0xFF, .graphics3 = 0x36,
                  .tilemap1 = 0x25, .tilemap2 = 0x25, .palette = 0x25 } },
    { .id = 37,  // $25 AIRSHIP_CENTER
      .record = { .graphics1 = 0x37, .graphics2 = 0x38, .graphics3 = 0x39,
                  .tilemap1 = 0x26, .tilemap2 = 0x26, .palette = 0x26 } },
    { .id = 38,  // $26 DARILLS_TOMB
      .record = { .graphics1 = 0x3A, .graphics2 = 0x48, .graphics3 = 0x3B,
                  .tilemap1 = 0x27, .tilemap2 = 0x27, .palette = 0x27 } },
    { .id = 39,  // $27 CASTLE_EXT
      .record = { .graphics1 = 0xAE, .graphics2 = 0xFF, .graphics3 = 0x26,
                  .tilemap1 = 0x28, .tilemap2 = 0x28, .palette = 0x28 } },
    { .id = 40,  // $28 KEFKAS_TOWER_INT
      .record = { .graphics1 = 0xAA, .graphics2 = 0xFF, .graphics3 = 0x20,
                  .tilemap1 = 0x29, .tilemap2 = 0x29, .palette = 0x29 } },
    { .id = 41,  // $29 AIRSHIP_WOR
      .record = { .graphics1 = 0x37, .graphics2 = 0x38, .graphics3 = 0x39,
                  .tilemap1 = 0x30, .tilemap2 = 0x30, .palette = 0x33 } },
    { .id = 42,  // $2A FIRE_CAVES
      .record = { .graphics1 = 0x91, .graphics2 = 0xFF, .graphics3 = 0x09,
                  .tilemap1 = 0x03, .tilemap2 = 0x03, .palette = 0x21 } },
    { .id = 43,  // $2B TOWN_INT
      .record = { .graphics1 = 0xB0, .graphics2 = 0xFF, .graphics3 = 0x2F,
                  .tilemap1 = 0x21, .tilemap2 = 0x21, .palette = 0x22 } },
    { .id = 44,  // $2C MAGITEK_TRAIN
      .record = { .graphics1 = 0x47, .graphics2 = 0x46, .graphics3 = 0x00,
                  .tilemap1 = 0x2D, .tilemap2 = 0x2D, .palette = 0x2F } },
    { .id = 45,  // $2D FANATICS_TOWER
      .record = { .graphics1 = 0xB5, .graphics2 = 0xFF, .graphics3 = 0x45,
                  .tilemap1 = 0x0A, .tilemap2 = 0x0A, .palette = 0x0A } },
    { .id = 46,  // $2E CYANS_DREAM
      .record = { .graphics1 = 0x49, .graphics2 = 0x4A, .graphics3 = 0x00,
                  .tilemap1 = 0x2F, .tilemap2 = 0x2F, .palette = 0xB2 } },
    { .id = 47,  // $2F DESERT_WOR
      .record = { .graphics1 = 0x18, .graphics2 = 0x1D, .graphics3 = 0xFF,
                  .tilemap1 = 0x0B, .tilemap2 = 0x0B, .palette = 0xB4 } },
    { .id = 48,  // $30 AIRSHIP_WOB
      .record = { .graphics1 = 0x37, .graphics2 = 0x38, .graphics3 = 0x39,
                  .tilemap1 = 0x30, .tilemap2 = 0x30, .palette = 0x26 } },
    { .id = 49,  // $31 BATTLE_BG_31
      .record = { .graphics1 = 0x00, .graphics2 = 0x01, .graphics3 = 0x02,
                  .tilemap1 = 0x00, .tilemap2 = 0x00, .palette = 0x00 } },
    { .id = 50,  // $32 GHOST_TRAIN
      .record = { .graphics1 = 0x8F, .graphics2 = 0xFF, .graphics3 = 0x31,
                  .tilemap1 = 0x22, .tilemap2 = 0x22, .palette = 0x00 } },
    { .id = 51,  // $33 FINAL_BATTLE_1
      .record = { .graphics1 = 0x3D, .graphics2 = 0x3E, .graphics3 = 0xFF,
                  .tilemap1 = 0x2A, .tilemap2 = 0x2A, .palette = 0x2C } },
    { .id = 52,  // $34 FINAL_BATTLE_2
      .record = { .graphics1 = 0x3F, .graphics2 = 0x40, .graphics3 = 0xFF,
                  .tilemap1 = 0x2B, .tilemap2 = 0x2B, .palette = 0x2D } },
    { .id = 53,  // $35 FINAL_BATTLE_3
      .record = { .graphics1 = 0x41, .graphics2 = 0x42, .graphics3 = 0xFF,
                  .tilemap1 = 0x2C, .tilemap2 = 0x2C, .palette = 0x2E } },
    { .id = 54,  // $36 FINAL_BATTLE_4
      .record = { .graphics1 = 0x43, .graphics2 = 0x44, .graphics3 = 0xFF,
                  .tilemap1 = 0x2E, .tilemap2 = 0x2E, .palette = 0x30 } },
    { .id = 55,  // $37 TENTACLES
      .record = { .graphics1 = 0x2D, .graphics2 = 0x24, .graphics3 = 0xFF,
                  .tilemap1 = 0x20, .tilemap2 = 0x20, .palette = 0xA0 } },
}};

}  // namespace ostinato::test
