// AUTO-GENERATED by tools/asm_parser/parse_blitz_code.py
// Source: src/btlgfx/btlgfx_main.asm (BlitzCode, 8 records x 12 bytes,
//         ROM $C4/7A40; BlitzButtonMaskTbl, 15 words, ROM $C1/6F67)
// Source: include/btlgfx/blitz_code.inc (BLITZ_CODE),
//         include/hardware.inc (JOY_*), include/const.inc (ATTACK)
// (original-src pinned at 1ea47b5; both tables cross-checked against the
// vanilla ROM over their whole extent)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_blitz_code.py \
//       --source-root  original-src

// Test fixture for tests/test_blitz_codes.cpp — the ground-truth
// bytes of both blitz tables.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 12-byte blitz record (btlgfx_main.asm:17012-17015): the eleven
// input bytes, NONE-padded, then the input count doubled. Deliberately
// independent of the typed rows in blitz_code_data.inc, so drift in
// either artifact fails the full-corpus comparison.
struct ExpectedBlitzCode {
    std::uint8_t inputs[11];
    std::uint8_t doubledInputCount;
};
static_assert(sizeof(ExpectedBlitzCode) == 12,
              "fixture record must stay identical to a ROM blitz record");

// One fixture entry: the blitz's position (raw decimal — the fixture
// stays independent of the port's AttackId header) and its record.
struct ExpectedBlitzCodeEntry {
    std::uint8_t id;
    ExpectedBlitzCode record;
};

// One mask word: the BLITZ_CODE value it belongs to and the word itself.
struct ExpectedBlitzButtonMask {
    std::uint8_t input;
    std::uint16_t mask;
};

inline constexpr std::array<ExpectedBlitzCodeEntry, 8>
    kExpectedBlitzCodes = {{
    { .id = 0, .record = { .inputs = { 14, 10, 14,  1,  0,  0,  0,  0,  0,  0,  0 }, .doubledInputCount = 8 } },
    { .id = 1, .record = { .inputs = {  8,  7, 14,  1,  0,  0,  0,  0,  0,  0,  0 }, .doubledInputCount = 8 } },
    { .id = 2, .record = { .inputs = {  3,  4,  8, 12,  1,  0,  0,  0,  0,  0,  0 }, .doubledInputCount = 10 } },
    { .id = 3, .record = { .inputs = { 14,  7,  8,  9, 10,  1,  0,  0,  0,  0,  0 }, .doubledInputCount = 12 } },
    { .id = 4, .record = { .inputs = {  6,  5,  6,  5,  3,  4,  1,  0,  0,  0,  0 }, .doubledInputCount = 14 } },
    { .id = 5, .record = { .inputs = { 12, 11, 10,  9,  8,  7, 14,  1,  0,  0,  0 }, .doubledInputCount = 16 } },
    { .id = 6, .record = { .inputs = {  6,  5,  3,  4, 10, 14,  1,  0,  0,  0,  0 }, .doubledInputCount = 14 } },
    { .id = 7, .record = { .inputs = { 14, 13, 12, 11, 10,  9,  8,  7, 14,  1,  0 }, .doubledInputCount = 20 } },
}};

inline constexpr std::array<ExpectedBlitzButtonMask, 15>
    kExpectedBlitzButtonMasks = {{
    { .input =  0, .mask = 0xFFFF },
    { .input =  1, .mask = 0x0080 },
    { .input =  2, .mask = 0x8000 },
    { .input =  3, .mask = 0x0040 },
    { .input =  4, .mask = 0x4000 },
    { .input =  5, .mask = 0x0020 },
    { .input =  6, .mask = 0x0010 },
    { .input =  7, .mask = 0x0600 },
    { .input =  8, .mask = 0x0400 },
    { .input =  9, .mask = 0x0500 },
    { .input = 10, .mask = 0x0100 },
    { .input = 11, .mask = 0x0900 },
    { .input = 12, .mask = 0x0800 },
    { .input = 13, .mask = 0x0A00 },
    { .input = 14, .mask = 0x0200 },
}};

}  // namespace ostinato::test
