// AUTO-GENERATED by tools/asm_parser/parse_char_ai.py
// Source: src/btlgfx/char_ai.asm (CharAI, 24 records x 24 bytes,
//         ROM $D0/FD00)
// Source: include/btlgfx/char_ai.inc (CHAR_AI + the two flag sets)
// Source: include/const.inc, include/gfx/battle_bg.inc,
//         include/sound/song_script.inc (CHAR_PROP / CHAR_GFX /
//         MONSTER / BATTLE_BG / SONG values)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_char_ai.py \
//       --source-root  original-src

// Test fixture for tests/test_char_ai.cpp — the ground-truth record
// bytes. The full-corpus test asserts, per entry: fixture id ==
// position, table id enumerator == position, and a 24-byte memcmp
// of the packed record against
// src/data/generated/char_ai_data.inc's row.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 24-byte CharAI record; field names and order mirror
// char_ai.asm:14-31. Values are the exact ROM bytes with every upstream
// symbol resolved and the flag bits folded in — deliberately independent
// of the symbol rows in char_ai_data.inc, so symbol/value drift in either
// artifact fails the full-corpus byte-equivalence test.
struct ExpectedCharAiSlot {
    std::uint8_t character;  // CHAR_PROP | enemy bit 6 | not-in-party bit 7
    std::uint8_t graphics;   // CHAR_GFX ($FF = default for the character)
    std::uint8_t aiScript;   // monster a.i. script, low byte
    std::uint8_t x, y;       // position, doubled by the consumer
};
static_assert(sizeof(ExpectedCharAiSlot) == 5,
              "fixture slot must stay identical to a ROM slot");

struct ExpectedCharAiRecord {
    std::uint8_t flags;      // hide names bit 0 | hide party bit 7
    std::uint8_t background; // BATTLE_BG ($FF = keep the default)
    std::uint8_t targets;    // valid monster target slots
    std::uint8_t song;       // SONG ($FF = the default battle song)
    ExpectedCharAiSlot slots[4];
};
static_assert(sizeof(ExpectedCharAiRecord) == 24,
              "fixture record must stay identical to a ROM CharAI record");

// One fixture entry: the record's identity as a typed field (raw decimal
// index — the fixture stays independent of the port's CharAiId header)
// alongside the raw record bytes.
struct ExpectedCharAiEntry {
    std::uint8_t id;
    ExpectedCharAiRecord record;
};

inline constexpr std::array<ExpectedCharAiEntry, 24>
    kExpectedCharAiEntries = {{  // ROM CharAI
    { .id =  0,  // $00 NONE
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                  } } },
    { .id =  1,  // $01 SHADOW_COLOSSEUM
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0x07,
                  .slots = {
                      { .character = 0x43, .graphics = 0x03, .aiScript = 0x7E, .x =  40, .y =  48 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                  } } },
    { .id =  2,  // $02 TERRA_FLASHBACK
      .record = { .flags = 0x81, .background = 0x19, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0xA9, .graphics = 0x15, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0x00, .graphics = 0xFF, .aiScript = 0x6E, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                  } } },
    { .id =  3,  // $03 VARGAS
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFE, .song = 0xFF,
                  .slots = {
                      { .character = 0x85, .graphics = 0xFF, .aiScript = 0xFF, .x =  60, .y = 108 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                  } } },
    { .id =  4,  // $04 KEFKA_IMP_CAMP_1
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x69, .graphics = 0x15, .aiScript = 0x6F, .x =  32, .y =  48 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id =  5,  // $05 CYAN_IMP_CAMP_1
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x02, .graphics = 0x02, .aiScript = 0x70, .x =  80, .y =  48 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id =  6,  // $06 CYAN_IMP_CAMP_2
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x02, .graphics = 0x02, .aiScript = 0x70, .x =  80, .y =  48 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id =  7,  // $07 PIRANHA
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id =  8,  // $08 UNUSED_08
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x6A, .graphics = 0x15, .aiScript = 0x6F, .x =  32, .y =  44 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id =  9,  // $09 UNUSED_09
      .record = { .flags = 0x80, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x29, .graphics = 0x15, .aiScript = 0xFF, .x = 100, .y = 100 },
                      { .character = 0x00, .graphics = 0x00, .aiScript = 0xFF, .x =  32, .y =  60 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 10,  // $0A GAU_VELDT
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0xCB, .graphics = 0x0B, .aiScript = 0x72, .x =  48, .y =  52 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 11,  // $0B UNUSED_0B
      .record = { .flags = 0x81, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x00, .graphics = 0x00, .aiScript = 0xFF, .x =  60, .y = 100 },
                      { .character = 0x01, .graphics = 0x01, .aiScript = 0xFF, .x =  60, .y = 100 },
                      { .character = 0x06, .graphics = 0x06, .aiScript = 0xFF, .x =  60, .y = 100 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 12,  // $0C SEALED_GATE_1
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x6A, .graphics = 0x15, .aiScript = 0x74, .x = 100, .y =  44 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 13,  // $0D SEALED_GATE_2
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x6A, .graphics = 0x15, .aiScript = 0xFF, .x = 100, .y =  48 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 14,  // $0E BLACKJACK_ESPERS
      .record = { .flags = 0x80, .background = 0xFF, .targets = 0xFF, .song = 0x1F,
                  .slots = {
                      { .character = 0x00, .graphics = 0x00, .aiScript = 0xFF, .x =  60, .y = 100 },
                      { .character = 0x01, .graphics = 0x01, .aiScript = 0xFF, .x =  60, .y = 100 },
                      { .character = 0x09, .graphics = 0x09, .aiScript = 0xFF, .x =  60, .y = 100 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 15,  // $0F ULTROS_RELM
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x88, .graphics = 0x08, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 16,  // $10 ESPERS
      .record = { .flags = 0x81, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x00, .graphics = 0x00, .aiScript = 0xFF, .x = 100, .y = 100 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 17,  // $11 BLITZ_TUTORIAL
      .record = { .flags = 0x81, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x00, .graphics = 0x15, .aiScript = 0xFF, .x =  64, .y =  88 },
                      { .character = 0x01, .graphics = 0x0E, .aiScript = 0xFF, .x =  92, .y =  80 },
                      { .character = 0x02, .graphics = 0x0E, .aiScript = 0xFF, .x =  40, .y =  84 },
                      { .character = 0x03, .graphics = 0x0E, .aiScript = 0xFF, .x = 100, .y = 100 },
                  } } },
    { .id = 18,  // $12 KEFKA_ESPER
      .record = { .flags = 0x81, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x2B, .graphics = 0x15, .aiScript = 0xFF, .x =  92, .y =  44 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 19,  // $13 KEFKA_GESTAHL
      .record = { .flags = 0x81, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x00, .graphics = 0x15, .aiScript = 0xFF, .x =  88, .y =  84 },
                      { .character = 0x01, .graphics = 0x16, .aiScript = 0xFF, .x =  48, .y =  84 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 20,  // $14 KEFKA_LEO
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x80, .graphics = 0x15, .aiScript = 0xFF, .x =  60, .y = 100 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 21,  // $15 UNUSED_15
      .record = { .flags = 0x80, .background = 0xFF, .targets = 0xFF, .song = 0xFF,
                  .slots = {
                      { .character = 0x29, .graphics = 0x15, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0xFF, .aiScript = 0xFF, .x = 255, .y = 255 },
                  } } },
    { .id = 22,  // $16 UNUSED_16
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFE, .song = 0xFF,
                  .slots = {
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                  } } },
    { .id = 23,  // $17 UNUSED_17
      .record = { .flags = 0x00, .background = 0xFF, .targets = 0xFE, .song = 0xFF,
                  .slots = {
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                      { .character = 0xFF, .graphics = 0x00, .aiScript = 0x00, .x = 255, .y = 255 },
                  } } },
}};

}  // namespace ostinato::test
