// AUTO-GENERATED by tools/asm_parser/parse_char_prop.py
// Source: src/field/char_prop.asm (CharProp, 64 records x 22 bytes)
// Source: include/const.inc (BATTLE_CMD / ITEM / CHAR_RUN_FACTOR /
//         CHAR_LEVEL_MOD / CHAR_PROP_FIXED_EQUIP / CHAR_PROP values)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_char_prop.py \
//       --source-root  original-src \
//       --inc-out      src/data/generated/char_prop_data.inc \
//       --fixture-out  tests/fixtures/char_prop_expected.h

// Test fixture for tests/test_character_base.cpp — the ground-truth
// record bytes. The full-corpus test memcmp-checks every
// CharacterBaseStats row (src/data/generated/char_prop_data.inc)
// against this table, record by record. Each record is labeled
// // [$NN] CHAR_PROP_NAME as in the .inc.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 22-byte char_prop record; field names and order mirror the
// end_char_prop byte emitter. Values are the exact ROM bytes with every
// upstream symbol resolved — deliberately independent of the enum-symbol
// rows in char_prop_data.inc, so symbol/value drift in either artifact
// fails the full-corpus byte-equivalence test.
struct ExpectedCharacterRecord {
    std::uint8_t hp;
    std::uint8_t mp;
    std::uint8_t cmd1, cmd2, cmd3, cmd4;         // BATTLE_CMD bytes
    std::uint8_t strength, agility, stamina;
    std::uint8_t magicPower, battlePower;
    std::uint8_t defense, magicDefense;
    std::uint8_t evade, magicBlock;
    std::uint8_t weapon, shield, helmet, armor;  // ITEM bytes
    std::uint8_t relic1, relic2;                 // ITEM bytes
    std::uint8_t traits;  // run factor bits 0-1 | level mod bits 2-3 | fixed-equip bit 4
};
static_assert(sizeof(ExpectedCharacterRecord) == 22,
              "fixture record must stay byte-identical to a ROM char_prop record");

inline constexpr std::array<ExpectedCharacterRecord, 64> kExpectedCharacterRecords = {{  // ROM CharProp
    // [$00] TERRA
    { .hp = 0x28, .mp = 0x10,
      .cmd1 = 0x00, .cmd2 = 0x03, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x1F, .agility = 0x21, .stamina = 0x1C, .magicPower = 0x27, .battlePower = 0x0C,
      .defense = 0x2A, .magicDefense = 0x21, .evade = 0x05, .magicBlock = 0x07,
      .weapon = 0x01, .shield = 0x5A, .helmet = 0x69, .armor = 0x84,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x01 },
    // [$01] LOCKE
    { .hp = 0x30, .mp = 0x07,
      .cmd1 = 0x00, .cmd2 = 0x05, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x25, .agility = 0x28, .stamina = 0x1F, .magicPower = 0x1C, .battlePower = 0x0E,
      .defense = 0x2E, .magicDefense = 0x17, .evade = 0x0F, .magicBlock = 0x02,
      .weapon = 0x00, .shield = 0xFF, .helmet = 0x69, .armor = 0x84,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x04 },
    // [$02] CYAN
    { .hp = 0x35, .mp = 0x05,
      .cmd1 = 0x00, .cmd2 = 0x07, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x28, .agility = 0x1C, .stamina = 0x21, .magicPower = 0x19, .battlePower = 0x19,
      .defense = 0x30, .magicDefense = 0x14, .evade = 0x06, .magicBlock = 0x01,
      .weapon = 0x2B, .shield = 0x5A, .helmet = 0x69, .armor = 0x84,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x06 },
    // [$03] SHADOW
    { .hp = 0x33, .mp = 0x06,
      .cmd1 = 0x00, .cmd2 = 0x08, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x27, .agility = 0x26, .stamina = 0x1E, .magicPower = 0x21, .battlePower = 0x17,
      .defense = 0x2F, .magicDefense = 0x19, .evade = 0x1C, .magicBlock = 0x09,
      .weapon = 0x25, .shield = 0xFF, .helmet = 0xFF, .armor = 0x8A,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x00 },
    // [$04] EDGAR
    { .hp = 0x31, .mp = 0x06,
      .cmd1 = 0x00, .cmd2 = 0x09, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x27, .agility = 0x1E, .stamina = 0x22, .magicPower = 0x1D, .battlePower = 0x14,
      .defense = 0x32, .magicDefense = 0x16, .evade = 0x04, .magicBlock = 0x01,
      .weapon = 0x0A, .shield = 0x5A, .helmet = 0x69, .armor = 0x84,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x05 },
    // [$05] SABIN
    { .hp = 0x3A, .mp = 0x03,
      .cmd1 = 0x00, .cmd2 = 0x0A, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x2F, .agility = 0x25, .stamina = 0x27, .magicPower = 0x1C, .battlePower = 0x1A,
      .defense = 0x35, .magicDefense = 0x15, .evade = 0x0C, .magicBlock = 0x04,
      .weapon = 0x53, .shield = 0xFF, .helmet = 0x69, .armor = 0x86,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x05 },
    // [$06] CELES
    { .hp = 0x2C, .mp = 0x0F,
      .cmd1 = 0x00, .cmd2 = 0x0B, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x22, .agility = 0x22, .stamina = 0x1F, .magicPower = 0x24, .battlePower = 0x10,
      .defense = 0x2C, .magicDefense = 0x1F, .evade = 0x07, .magicBlock = 0x09,
      .weapon = 0xFF, .shield = 0xFF, .helmet = 0x6A, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x01 },
    // [$07] STRAGO
    { .hp = 0x23, .mp = 0x0D,
      .cmd1 = 0x00, .cmd2 = 0x0C, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x1C, .agility = 0x19, .stamina = 0x13, .magicPower = 0x22, .battlePower = 0x0A,
      .defense = 0x21, .magicDefense = 0x1B, .evade = 0x06, .magicBlock = 0x07,
      .weapon = 0x34, .shield = 0x5C, .helmet = 0x6B, .armor = 0x85,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x06 },
    // [$08] RELM
    { .hp = 0x25, .mp = 0x12,
      .cmd1 = 0x00, .cmd2 = 0x0D, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x1A, .agility = 0x22, .stamina = 0x16, .magicPower = 0x2C, .battlePower = 0x0B,
      .defense = 0x23, .magicDefense = 0x1E, .evade = 0x0D, .magicBlock = 0x09,
      .weapon = 0x3D, .shield = 0x5C, .helmet = 0x6B, .armor = 0x88,
      .relic1 = 0xDB, .relic2 = 0xFF, .traits = 0x00 },
    // [$09] SETZER
    { .hp = 0x2E, .mp = 0x09,
      .cmd1 = 0x00, .cmd2 = 0x0F, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x24, .agility = 0x20, .stamina = 0x20, .magicPower = 0x1D, .battlePower = 0x12,
      .defense = 0x30, .magicDefense = 0x1A, .evade = 0x09, .magicBlock = 0x01,
      .weapon = 0x4D, .shield = 0x5C, .helmet = 0x6E, .armor = 0x89,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x01 },
    // [$0A] MOG
    { .hp = 0x27, .mp = 0x10,
      .cmd1 = 0x00, .cmd2 = 0x13, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x1D, .agility = 0x24, .stamina = 0x1A, .magicPower = 0x23, .battlePower = 0x10,
      .defense = 0x34, .magicDefense = 0x24, .evade = 0x0A, .magicBlock = 0x0C,
      .weapon = 0x1D, .shield = 0x5C, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x08 },
    // [$0B] GAU
    { .hp = 0x2D, .mp = 0x0A,
      .cmd1 = 0x10, .cmd2 = 0x11, .cmd3 = 0x02, .cmd4 = 0x01,
      .strength = 0x2C, .agility = 0x26, .stamina = 0x24, .magicPower = 0x22, .battlePower = 0x63,
      .defense = 0x2C, .magicDefense = 0x22, .evade = 0x15, .magicBlock = 0x12,
      .weapon = 0xFF, .shield = 0xFF, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x04 },
    // [$0C] GOGO
    { .hp = 0x24, .mp = 0x0C,
      .cmd1 = 0x12, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0xFF,
      .strength = 0x19, .agility = 0x1E, .stamina = 0x14, .magicPower = 0x1A, .battlePower = 0x0D,
      .defense = 0x27, .magicDefense = 0x19, .evade = 0x0A, .magicBlock = 0x06,
      .weapon = 0x01, .shield = 0x5C, .helmet = 0x6B, .armor = 0x89,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x05 },
    // [$0D] UMARO
    { .hp = 0x3C, .mp = 0x00,
      .cmd1 = 0xFF, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0xFF,
      .strength = 0x39, .agility = 0x21, .stamina = 0x2E, .magicPower = 0x25, .battlePower = 0x2F,
      .defense = 0x59, .magicDefense = 0x44, .evade = 0x08, .magicBlock = 0x05,
      .weapon = 0x4A, .shield = 0xFF, .helmet = 0xFF, .armor = 0xA2,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x02 },
    // [$0E] BANON
    { .hp = 0x2E, .mp = 0x10,
      .cmd1 = 0x00, .cmd2 = 0x1A, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x0A, .agility = 0x18, .stamina = 0x0B, .magicPower = 0x20, .battlePower = 0x06,
      .defense = 0x38, .magicDefense = 0x33, .evade = 0x24, .magicBlock = 0x20,
      .weapon = 0x3B, .shield = 0xFF, .helmet = 0x6D, .armor = 0x88,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x1F },
    // [$0F] LEO
    { .hp = 0x32, .mp = 0x0A,
      .cmd1 = 0x00, .cmd2 = 0x1B, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x34, .agility = 0x26, .stamina = 0x29, .magicPower = 0x24, .battlePower = 0x3C,
      .defense = 0x3F, .magicDefense = 0x29, .evade = 0x16, .magicBlock = 0x15,
      .weapon = 0x14, .shield = 0x5E, .helmet = 0x76, .armor = 0x8F,
      .relic1 = 0xC4, .relic2 = 0xD3, .traits = 0x1A },
    // [$10] GHOST_1
    { .hp = 0x1A, .mp = 0x01,
      .cmd1 = 0x00, .cmd2 = 0x1C, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x0E, .agility = 0x0F, .stamina = 0x0A, .magicPower = 0x1E, .battlePower = 0x16,
      .defense = 0x42, .magicDefense = 0x34, .evade = 0x00, .magicBlock = 0x00,
      .weapon = 0xFF, .shield = 0xFF, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xDD, .relic2 = 0xFF, .traits = 0x14 },
    // [$11] GHOST_2
    { .hp = 0x14, .mp = 0x01,
      .cmd1 = 0x00, .cmd2 = 0x1C, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x04, .agility = 0x08, .stamina = 0x02, .magicPower = 0x0F, .battlePower = 0x0A,
      .defense = 0x11, .magicDefense = 0x0B, .evade = 0x00, .magicBlock = 0x00,
      .weapon = 0xFF, .shield = 0xFF, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xDD, .relic2 = 0xFF, .traits = 0x1E },
    // [$12] KUPEK
    { .hp = 0x32, .mp = 0x09,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x12, .agility = 0x0B, .stamina = 0x0C, .magicPower = 0x21, .battlePower = 0x23,
      .defense = 0x2F, .magicDefense = 0x1B, .evade = 0x07, .magicBlock = 0x05,
      .weapon = 0x1D, .shield = 0x5A, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x17 },
    // [$13] KUPOP
    { .hp = 0x36, .mp = 0x09,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x12, .agility = 0x0E, .stamina = 0x0C, .magicPower = 0x21, .battlePower = 0x01,
      .defense = 0x26, .magicDefense = 0x1A, .evade = 0x07, .magicBlock = 0x05,
      .weapon = 0x46, .shield = 0x5A, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x13 },
    // [$14] KUMAMA
    { .hp = 0x30, .mp = 0x09,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x12, .agility = 0x0E, .stamina = 0x0C, .magicPower = 0x21, .battlePower = 0x01,
      .defense = 0x2A, .magicDefense = 0x21, .evade = 0x07, .magicBlock = 0x05,
      .weapon = 0x54, .shield = 0x5A, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x13 },
    // [$15] KUKU
    { .hp = 0x40, .mp = 0x09,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x11, .agility = 0x0E, .stamina = 0x0C, .magicPower = 0x21, .battlePower = 0x0B,
      .defense = 0x28, .magicDefense = 0x20, .evade = 0x07, .magicBlock = 0x05,
      .weapon = 0x44, .shield = 0x5A, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x1F },
    // [$16] KUTAN
    { .hp = 0x37, .mp = 0x09,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x10, .agility = 0x0E, .stamina = 0x0C, .magicPower = 0x21, .battlePower = 0x0B,
      .defense = 0x2C, .magicDefense = 0x1D, .evade = 0x07, .magicBlock = 0x05,
      .weapon = 0x0A, .shield = 0x5A, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x13 },
    // [$17] KUPAN
    { .hp = 0x33, .mp = 0x09,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x14, .agility = 0x0E, .stamina = 0x0C, .magicPower = 0x21, .battlePower = 0x15,
      .defense = 0x2D, .magicDefense = 0x1E, .evade = 0x07, .magicBlock = 0x05,
      .weapon = 0x45, .shield = 0x5A, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x17 },
    // [$18] KUSHU
    { .hp = 0x34, .mp = 0x09,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x18, .agility = 0x0E, .stamina = 0x0C, .magicPower = 0x21, .battlePower = 0x1B,
      .defense = 0x29, .magicDefense = 0x1F, .evade = 0x07, .magicBlock = 0x05,
      .weapon = 0x3D, .shield = 0x5A, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x17 },
    // [$19] KURIN
    { .hp = 0x35, .mp = 0x09,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x13, .agility = 0x0E, .stamina = 0x0C, .magicPower = 0x21, .battlePower = 0x14,
      .defense = 0x29, .magicDefense = 0x1F, .evade = 0x07, .magicBlock = 0x05,
      .weapon = 0x1D, .shield = 0x5A, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x13 },
    // [$1A] KURU
    { .hp = 0x32, .mp = 0x09,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x11, .agility = 0x0E, .stamina = 0x0C, .magicPower = 0x21, .battlePower = 0x2C,
      .defense = 0x1B, .magicDefense = 0x13, .evade = 0x07, .magicBlock = 0x05,
      .weapon = 0x0A, .shield = 0x5A, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x13 },
    // [$1B] KAMOG
    { .hp = 0x35, .mp = 0x09,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x14, .agility = 0x0E, .stamina = 0x0C, .magicPower = 0x21, .battlePower = 0x0B,
      .defense = 0x28, .magicDefense = 0x21, .evade = 0x07, .magicBlock = 0x05,
      .weapon = 0x47, .shield = 0x5A, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x17 },
    // [$1C] SCENARIO_MOG
    { .hp = 0x0C, .mp = 0x22,
      .cmd1 = 0xFF, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0xFF,
      .strength = 0x0C, .agility = 0x0C, .stamina = 0x0C, .magicPower = 0x0C, .battlePower = 0x0C,
      .defense = 0x0C, .magicDefense = 0x0C, .evade = 0x0C, .magicBlock = 0x0C,
      .weapon = 0xFF, .shield = 0xFF, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x1B },
    // [$1D] TERRA_INTRO  (empty)
    {},
    // [$1E] MADUIN
    { .hp = 0x0A, .mp = 0x0A,
      .cmd1 = 0xFF, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0xFF,
      .strength = 0x1E, .agility = 0x1E, .stamina = 0x1E, .magicPower = 0x1E, .battlePower = 0x1E,
      .defense = 0x1E, .magicDefense = 0x1E, .evade = 0x1E, .magicBlock = 0x1E,
      .weapon = 0xFF, .shield = 0xFF, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xE6, .relic2 = 0xFF, .traits = 0x00 },
    // [$1F] SHADOW_COLOSSEUM
    { .hp = 0x33, .mp = 0x06,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0x02, .cmd4 = 0xFF,
      .strength = 0x28, .agility = 0x28, .stamina = 0x1E, .magicPower = 0x23, .battlePower = 0x19,
      .defense = 0x31, .magicDefense = 0x1B, .evade = 0x1E, .magicBlock = 0x0C,
      .weapon = 0x27, .shield = 0x5C, .helmet = 0x74, .armor = 0x8A,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x04 },
    // [$20] WEDGE
    { .hp = 0x44, .mp = 0x00,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x28, .agility = 0x23, .stamina = 0x2E, .magicPower = 0x1D, .battlePower = 0x18,
      .defense = 0x4D, .magicDefense = 0x32, .evade = 0x0F, .magicBlock = 0x00,
      .weapon = 0x0A, .shield = 0x5A, .helmet = 0x69, .armor = 0x84,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x1D },
    // [$21] VICKS
    { .hp = 0x46, .mp = 0x00,
      .cmd1 = 0x00, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0x01,
      .strength = 0x29, .agility = 0x24, .stamina = 0x2D, .magicPower = 0x1C, .battlePower = 0x1B,
      .defense = 0x4F, .magicDefense = 0x32, .evade = 0x0C, .magicBlock = 0x00,
      .weapon = 0x0A, .shield = 0x5A, .helmet = 0x69, .armor = 0x84,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x1D },
    // [$22] UNUSED_22  (empty)
    {},
    // [$23] UNUSED_23  (empty)
    {},
    // [$24] UNUSED_24  (empty)
    {},
    // [$25] UNUSED_25  (empty)
    {},
    // [$26] UNUSED_26  (empty)
    {},
    // [$27] UNUSED_27  (empty)
    {},
    // [$28] UNUSED_28  (empty)
    {},
    // [$29] KEFKA_1
    { .hp = 0x0E, .mp = 0x11,
      .cmd1 = 0xFF, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0xFF,
      .strength = 0x0E, .agility = 0x1A, .stamina = 0x12, .magicPower = 0x16, .battlePower = 0x07,
      .defense = 0x2A, .magicDefense = 0x24, .evade = 0x32, .magicBlock = 0x28,
      .weapon = 0x46, .shield = 0xFF, .helmet = 0x74, .armor = 0x89,
      .relic1 = 0xCA, .relic2 = 0xFF, .traits = 0x10 },
    // [$2A] KEFKA_2
    { .hp = 0xFF, .mp = 0x11,
      .cmd1 = 0xFF, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0xFF,
      .strength = 0x0F, .agility = 0x0F, .stamina = 0x0F, .magicPower = 0x0F, .battlePower = 0x0F,
      .defense = 0x32, .magicDefense = 0x32, .evade = 0x0A, .magicBlock = 0x0A,
      .weapon = 0x46, .shield = 0xFF, .helmet = 0x74, .armor = 0x89,
      .relic1 = 0xCA, .relic2 = 0xFF, .traits = 0x14 },
    // [$2B] KEFKA_3
    { .hp = 0x32, .mp = 0x32,
      .cmd1 = 0xFF, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0xFF,
      .strength = 0x50, .agility = 0x50, .stamina = 0x50, .magicPower = 0x50, .battlePower = 0x50,
      .defense = 0xB4, .magicDefense = 0xB4, .evade = 0x3C, .magicBlock = 0x3C,
      .weapon = 0x46, .shield = 0x67, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xCA, .relic2 = 0xFF, .traits = 0x14 },
    // [$2C] KEFKA_4
    { .hp = 0x16, .mp = 0x11,
      .cmd1 = 0xFF, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0xFF,
      .strength = 0x0F, .agility = 0x0F, .stamina = 0x0F, .magicPower = 0x0F, .battlePower = 0x0F,
      .defense = 0x32, .magicDefense = 0x32, .evade = 0x0A, .magicBlock = 0x0A,
      .weapon = 0x46, .shield = 0xFF, .helmet = 0x74, .armor = 0x89,
      .relic1 = 0xCA, .relic2 = 0xFF, .traits = 0x14 },
    // [$2D] KEFKA_5
    { .hp = 0x22, .mp = 0x11,
      .cmd1 = 0xFF, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0xFF,
      .strength = 0x0F, .agility = 0x0F, .stamina = 0x0F, .magicPower = 0x0F, .battlePower = 0x0F,
      .defense = 0x32, .magicDefense = 0x32, .evade = 0x0A, .magicBlock = 0x0A,
      .weapon = 0x46, .shield = 0xFF, .helmet = 0x74, .armor = 0x89,
      .relic1 = 0xCA, .relic2 = 0xFF, .traits = 0x14 },
    // [$2E] KEFKA_6
    { .hp = 0x0E, .mp = 0x11,
      .cmd1 = 0xFF, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0xFF,
      .strength = 0x0F, .agility = 0x0F, .stamina = 0x0F, .magicPower = 0x0F, .battlePower = 0x0F,
      .defense = 0x32, .magicDefense = 0x32, .evade = 0x0A, .magicBlock = 0x0A,
      .weapon = 0xFF, .shield = 0xFF, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x10 },
    // [$2F] KEFKA_7
    { .hp = 0x0E, .mp = 0x11,
      .cmd1 = 0xFF, .cmd2 = 0xFF, .cmd3 = 0xFF, .cmd4 = 0xFF,
      .strength = 0x0F, .agility = 0x0F, .stamina = 0x0F, .magicPower = 0x0F, .battlePower = 0x0F,
      .defense = 0x32, .magicDefense = 0x32, .evade = 0x0A, .magicBlock = 0x0A,
      .weapon = 0xFF, .shield = 0xFF, .helmet = 0xFF, .armor = 0xFF,
      .relic1 = 0xFF, .relic2 = 0xFF, .traits = 0x10 },
    // [$30] TORK  (empty)
    {},
    // [$31] JADE  (empty)
    {},
    // [$32] CUSTER  (empty)
    {},
    // [$33] FABIAN  (empty)
    {},
    // [$34] DRAKE  (empty)
    {},
    // [$35] SARA  (empty)
    {},
    // [$36] CASE  (empty)
    {},
    // [$37] SIELE  (empty)
    {},
    // [$38] RAY  (empty)
    {},
    // [$39] REIKER  (empty)
    {},
    // [$3A] LANCE  (empty)
    {},
    // [$3B] BOB  (empty)
    {},
    // [$3C] PEPPER  (empty)
    {},
    // [$3D] TAU  (empty)
    {},
    // [$3E] VICTOR  (empty)
    {},
    // [$3F] HO  (empty)
    {},
}};

}  // namespace ostinato::test
