// AUTO-GENERATED by tools/asm_parser/parse_colosseum.py
// Source: src/menu/colosseum.asm (ColosseumProp, ROM DF/B600,
//         256 make_colosseum_prop rows x 4 bytes; macro at
//         colosseum.asm:1189-1204, sole reader LoadColosseumProp at
//         colosseum.asm:833-846)
// Source: include/const.inc (MONSTER / ITEM values)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_colosseum.py \
//       --source-root  original-src \
//       --inc-out      src/data/generated/colosseum_prop_data.inc \
//       --fixture-out  tests/fixtures/colosseum_prop_expected.h

// Test fixture for tests/test_colosseum_wagers.cpp — the
// ground-truth record bytes. The full-corpus test asserts, per
// entry: fixture id == position, table id enumerator ==
// position, and a 4-byte memcmp of the packed record against
// src/data/generated/colosseum_prop_data.inc's row.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 4-byte ColosseumProp record; field names mirror the
// src/data/colosseum_wagers.h record layout. Values are the exact ROM
// bytes — deliberately independent of the typed-surface rows in
// colosseum_prop_data.inc, so resolution drift in either artifact fails
// the full-corpus byte-equivalence test.
struct ExpectedColosseumRecord {
    std::uint8_t monster;
    std::uint8_t unused40;
    std::uint8_t prize;
    std::uint8_t hidePrizeFlag;
};
static_assert(sizeof(ExpectedColosseumRecord) == 4,
              "fixture record must stay byte-identical to a ROM ColosseumProp record");

// One fixture entry: the record's identity as a typed field (raw decimal
// index — the fixture stays independent of the port's ItemId header)
// alongside the raw record bytes. Mirrors
// ostinato::ColosseumWagerEntry without depending on it.
struct ExpectedColosseumEntry {
    std::uint8_t id;
    ExpectedColosseumRecord record;
};

inline constexpr std::array<ExpectedColosseumEntry, 256> kExpectedColosseumEntries = {{  // ROM ColosseumProp
    { .id =   0,  // $00 DIRK
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =   1,  // $01 MITHRILKNIFE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =   2,  // $02 GUARDIAN
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =   3,  // $03 AIR_LANCET
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =   4,  // $04 THIEFKNIFE
      .record = { .monster = 0x7D, .unused40 = 0x40, .prize = 0xCF,
                  .hidePrizeFlag = 0x00 } },
    { .id =   5,  // $05 ASSASSIN
      .record = { .monster = 0x9C, .unused40 = 0x40, .prize = 0x07,
                  .hidePrizeFlag = 0x00 } },
    { .id =   6,  // $06 MAN_EATER
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =   7,  // $07 SWORDBREAKER
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =   8,  // $08 GRAEDUS
      .record = { .monster = 0xDC, .unused40 = 0x40, .prize = 0x00,
                  .hidePrizeFlag = 0x00 } },
    { .id =   9,  // $09 VALIANTKNIFE
      .record = { .monster = 0xFA, .unused40 = 0x40, .prize = 0x05,
                  .hidePrizeFlag = 0x00 } },
    { .id =  10,  // $0A MITHRILBLADE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  11,  // $0B REGAL_CUTLASS
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  12,  // $0C RUNE_EDGE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  13,  // $0D FLAME_SABRE
      .record = { .monster = 0xB7, .unused40 = 0x40, .prize = 0x17,
                  .hidePrizeFlag = 0x00 } },
    { .id =  14,  // $0E BLIZZARD
      .record = { .monster = 0xA1, .unused40 = 0x40, .prize = 0x17,
                  .hidePrizeFlag = 0x00 } },
    { .id =  15,  // $0F THUNDERBLADE
      .record = { .monster = 0x16, .unused40 = 0x40, .prize = 0x17,
                  .hidePrizeFlag = 0x00 } },
    { .id =  16,  // $10 EPEE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  17,  // $11 BREAK_BLADE
      .record = { .monster = 0x45, .unused40 = 0x40, .prize = 0x11,
                  .hidePrizeFlag = 0x00 } },
    { .id =  18,  // $12 DRAINER
      .record = { .monster = 0xA6, .unused40 = 0x40, .prize = 0x12,
                  .hidePrizeFlag = 0x00 } },
    { .id =  19,  // $13 ENHANCER
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  20,  // $14 CRYSTAL
      .record = { .monster = 0xF2, .unused40 = 0x40, .prize = 0x13,
                  .hidePrizeFlag = 0x00 } },
    { .id =  21,  // $15 FALCHION
      .record = { .monster = 0xBD, .unused40 = 0x40, .prize = 0x60,
                  .hidePrizeFlag = 0x00 } },
    { .id =  22,  // $16 SOUL_SABRE
      .record = { .monster = 0xC8, .unused40 = 0x40, .prize = 0x15,
                  .hidePrizeFlag = 0x00 } },
    { .id =  23,  // $17 OGRE_NIX
      .record = { .monster = 0x7F, .unused40 = 0x40, .prize = 0x16,
                  .hidePrizeFlag = 0x00 } },
    { .id =  24,  // $18 EXCALIBUR
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  25,  // $19 SCIMITAR
      .record = { .monster = 0x67, .unused40 = 0x40, .prize = 0x17,
                  .hidePrizeFlag = 0x00 } },
    { .id =  26,  // $1A ILLUMINA
      .record = { .monster = 0xA1, .unused40 = 0x40, .prize = 0x19,
                  .hidePrizeFlag = 0x00 } },
    { .id =  27,  // $1B RAGNAROK
      .record = { .monster = 0xF9, .unused40 = 0x40, .prize = 0x1A,
                  .hidePrizeFlag = 0xFF } },
    { .id =  28,  // $1C ATMA_WEAPON
      .record = { .monster = 0xE0, .unused40 = 0x40, .prize = 0x08,
                  .hidePrizeFlag = 0x00 } },
    { .id =  29,  // $1D MITHRIL_PIKE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  30,  // $1E TRIDENT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  31,  // $1F STOUT_SPEAR
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  32,  // $20 PARTISAN
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  33,  // $21 PEARL_LANCE
      .record = { .monster = 0xFC, .unused40 = 0x40, .prize = 0x31,
                  .hidePrizeFlag = 0x00 } },
    { .id =  34,  // $22 GOLD_LANCE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  35,  // $23 AURA_LANCE
      .record = { .monster = 0x9B, .unused40 = 0x40, .prize = 0x32,
                  .hidePrizeFlag = 0x00 } },
    { .id =  36,  // $24 IMP_HALBERD
      .record = { .monster = 0x85, .unused40 = 0x40, .prize = 0x80,
                  .hidePrizeFlag = 0x00 } },
    { .id =  37,  // $25 IMPERIAL
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  38,  // $26 KODACHI
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  39,  // $27 BLOSSOM
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  40,  // $28 HARDENED
      .record = { .monster = 0xBC, .unused40 = 0x40, .prize = 0x2F,
                  .hidePrizeFlag = 0x00 } },
    { .id =  41,  // $29 STRIKER
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0x29,
                  .hidePrizeFlag = 0xFF } },
    { .id =  42,  // $2A STUNNER
      .record = { .monster = 0x9C, .unused40 = 0x40, .prize = 0x31,
                  .hidePrizeFlag = 0x00 } },
    { .id =  43,  // $2B ASHURA
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  44,  // $2C KOTETSU
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  45,  // $2D FORGED
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  46,  // $2E TEMPEST
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  47,  // $2F MURASAME
      .record = { .monster = 0xF2, .unused40 = 0x40, .prize = 0x30,
                  .hidePrizeFlag = 0x00 } },
    { .id =  48,  // $30 AURA
      .record = { .monster = 0x7E, .unused40 = 0x40, .prize = 0x31,
                  .hidePrizeFlag = 0x00 } },
    { .id =  49,  // $31 STRATO
      .record = { .monster = 0xEC, .unused40 = 0x40, .prize = 0x21,
                  .hidePrizeFlag = 0x00 } },
    { .id =  50,  // $32 SKY_RENDER
      .record = { .monster = 0xA1, .unused40 = 0x40, .prize = 0x23,
                  .hidePrizeFlag = 0x00 } },
    { .id =  51,  // $33 HEAL_ROD
      .record = { .monster = 0x54, .unused40 = 0x40, .prize = 0x3C,
                  .hidePrizeFlag = 0x00 } },
    { .id =  52,  // $34 MITHRIL_ROD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  53,  // $35 FIRE_ROD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  54,  // $36 ICE_ROD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  55,  // $37 THUNDER_ROD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  56,  // $38 POISON_ROD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  57,  // $39 PEARL_ROD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  58,  // $3A GRAVITY_ROD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  59,  // $3B PUNISHER
      .record = { .monster = 0xC8, .unused40 = 0x40, .prize = 0x3A,
                  .hidePrizeFlag = 0x00 } },
    { .id =  60,  // $3C MAGUS_ROD
      .record = { .monster = 0x85, .unused40 = 0x40, .prize = 0x31,
                  .hidePrizeFlag = 0x00 } },
    { .id =  61,  // $3D CHOCOBO_BRSH
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  62,  // $3E DAVINCI_BRSH
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  63,  // $3F MAGICAL_BRSH
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  64,  // $40 RAINBOW_BRSH
      .record = { .monster = 0x9C, .unused40 = 0x40, .prize = 0x3A,
                  .hidePrizeFlag = 0x00 } },
    { .id =  65,  // $41 SHURIKEN
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  66,  // $42 NINJA_STAR
      .record = { .monster = 0xE2, .unused40 = 0x40, .prize = 0x43,
                  .hidePrizeFlag = 0x00 } },
    { .id =  67,  // $43 TACK_STAR
      .record = { .monster = 0xC8, .unused40 = 0x40, .prize = 0x48,
                  .hidePrizeFlag = 0x00 } },
    { .id =  68,  // $44 FLAIL
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  69,  // $45 FULL_MOON
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  70,  // $46 MORNING_STAR
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  71,  // $47 BOOMERANG
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  72,  // $48 RISING_SUN
      .record = { .monster = 0x85, .unused40 = 0x40, .prize = 0x4A,
                  .hidePrizeFlag = 0x00 } },
    { .id =  73,  // $49 HAWK_EYE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  74,  // $4A BONE_CLUB
      .record = { .monster = 0x9C, .unused40 = 0x40, .prize = 0x93,
                  .hidePrizeFlag = 0x00 } },
    { .id =  75,  // $4B SNIPER
      .record = { .monster = 0xF2, .unused40 = 0x40, .prize = 0x4A,
                  .hidePrizeFlag = 0x00 } },
    { .id =  76,  // $4C WING_EDGE
      .record = { .monster = 0x7E, .unused40 = 0x40, .prize = 0x4B,
                  .hidePrizeFlag = 0x00 } },
    { .id =  77,  // $4D CARDS
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  78,  // $4E DARTS
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  79,  // $4F DOOM_DARTS
      .record = { .monster = 0xC8, .unused40 = 0x40, .prize = 0x4A,
                  .hidePrizeFlag = 0x00 } },
    { .id =  80,  // $50 TRUMP
      .record = { .monster = 0x85, .unused40 = 0x40, .prize = 0x50,
                  .hidePrizeFlag = 0x00 } },
    { .id =  81,  // $51 DICE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  82,  // $52 FIXED_DICE
      .record = { .monster = 0xF7, .unused40 = 0x40, .prize = 0x57,
                  .hidePrizeFlag = 0x00 } },
    { .id =  83,  // $53 METALKNUCKLE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  84,  // $54 MITHRIL_CLAW
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  85,  // $55 KAISER
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  86,  // $56 POISON_CLAW
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  87,  // $57 FIRE_KNUCKLE
      .record = { .monster = 0x34, .unused40 = 0x40, .prize = 0x57,
                  .hidePrizeFlag = 0x00 } },
    { .id =  88,  // $58 DRAGON_CLAW
      .record = { .monster = 0x9C, .unused40 = 0x40, .prize = 0x4B,
                  .hidePrizeFlag = 0x00 } },
    { .id =  89,  // $59 TIGER_FANGS
      .record = { .monster = 0xD2, .unused40 = 0x40, .prize = 0x57,
                  .hidePrizeFlag = 0x00 } },
    { .id =  90,  // $5A BUCKLER
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  91,  // $5B HEAVY_SHLD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  92,  // $5C MITHRIL_SHLD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  93,  // $5D GOLD_SHLD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  94,  // $5E AEGIS_SHLD
      .record = { .monster = 0xF2, .unused40 = 0x40, .prize = 0x65,
                  .hidePrizeFlag = 0x00 } },
    { .id =  95,  // $5F DIAMOND_SHLD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id =  96,  // $60 FLAME_SHLD
      .record = { .monster = 0xFD, .unused40 = 0x40, .prize = 0x61,
                  .hidePrizeFlag = 0x00 } },
    { .id =  97,  // $61 ICE_SHLD
      .record = { .monster = 0xF6, .unused40 = 0x40, .prize = 0x60,
                  .hidePrizeFlag = 0x00 } },
    { .id =  98,  // $62 THUNDER_SHLD
      .record = { .monster = 0xBD, .unused40 = 0x40, .prize = 0x64,
                  .hidePrizeFlag = 0x00 } },
    { .id =  99,  // $63 CRYSTAL_SHLD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 100,  // $64 GENJI_SHLD
      .record = { .monster = 0x07, .unused40 = 0x40, .prize = 0x62,
                  .hidePrizeFlag = 0x00 } },
    { .id = 101,  // $65 TORTOISESHLD
      .record = { .monster = 0x16, .unused40 = 0x40, .prize = 0x83,
                  .hidePrizeFlag = 0x00 } },
    { .id = 102,  // $66 CURSED_SHLD
      .record = { .monster = 0xF9, .unused40 = 0x40, .prize = 0xC2,
                  .hidePrizeFlag = 0x00 } },
    { .id = 103,  // $67 PALADIN_SHLD
      .record = { .monster = 0xC1, .unused40 = 0x40, .prize = 0x68,
                  .hidePrizeFlag = 0x00 } },
    { .id = 104,  // $68 FORCE_SHLD
      .record = { .monster = 0x0D, .unused40 = 0x40, .prize = 0x82,
                  .hidePrizeFlag = 0x00 } },
    { .id = 105,  // $69 LEATHER_HAT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 106,  // $6A HAIR_BAND
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 107,  // $6B PLUMED_HAT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 108,  // $6C BERET
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 109,  // $6D MAGUS_HAT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 110,  // $6E BANDANA
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 111,  // $6F IRONHELMET
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 112,  // $70 CORONET
      .record = { .monster = 0xB7, .unused40 = 0x40, .prize = 0x7B,
                  .hidePrizeFlag = 0x00 } },
    { .id = 113,  // $71 BARDS_HAT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 114,  // $72 GREEN_BERET
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 115,  // $73 HEAD_BAND
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 116,  // $74 MITHRIL_HELM
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 117,  // $75 TIARA
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 118,  // $76 GOLD_HELMET
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 119,  // $77 TIGER_MASK
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 120,  // $78 RED_CAP
      .record = { .monster = 0x7E, .unused40 = 0x40, .prize = 0x70,
                  .hidePrizeFlag = 0x00 } },
    { .id = 121,  // $79 MYSTERY_VEIL
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 122,  // $7A CIRCLET
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 123,  // $7B REGAL_CROWN
      .record = { .monster = 0xC8, .unused40 = 0x40, .prize = 0x81,
                  .hidePrizeFlag = 0x00 } },
    { .id = 124,  // $7C DIAMOND_HELM
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 125,  // $7D DARK_HOOD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 126,  // $7E CRYSTAL_HELM
      .record = { .monster = 0xD9, .unused40 = 0x40, .prize = 0x7C,
                  .hidePrizeFlag = 0x00 } },
    { .id = 127,  // $7F OATH_VEIL
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 128,  // $80 CAT_HOOD
      .record = { .monster = 0x3E, .unused40 = 0x40, .prize = 0xDA,
                  .hidePrizeFlag = 0xFF } },
    { .id = 129,  // $81 GENJI_HELMET
      .record = { .monster = 0xEA, .unused40 = 0x40, .prize = 0x7E,
                  .hidePrizeFlag = 0x00 } },
    { .id = 130,  // $82 THORNLET
      .record = { .monster = 0xC8, .unused40 = 0x40, .prize = 0x8E,
                  .hidePrizeFlag = 0x00 } },
    { .id = 131,  // $83 TITANIUM
      .record = { .monster = 0x26, .unused40 = 0x40, .prize = 0x80,
                  .hidePrizeFlag = 0x00 } },
    { .id = 132,  // $84 LEATHERARMOR
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 133,  // $85 COTTON_ROBE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 134,  // $86 KUNG_FU_SUIT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 135,  // $87 IRON_ARMOR
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 136,  // $88 SILK_ROBE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 137,  // $89 MITHRIL_VEST
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 138,  // $8A NINJA_GEAR
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 139,  // $8B WHITE_DRESS
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 140,  // $8C MITHRIL_MAIL
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 141,  // $8D GAIA_GEAR
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 142,  // $8E MIRAGE_VEST
      .record = { .monster = 0xE4, .unused40 = 0x40, .prize = 0x93,
                  .hidePrizeFlag = 0x00 } },
    { .id = 143,  // $8F GOLD_ARMOR
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 144,  // $90 POWER_SASH
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 145,  // $91 LIGHT_ROBE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 146,  // $92 DIAMOND_VEST
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 147,  // $93 RED_JACKET
      .record = { .monster = 0xE4, .unused40 = 0x40, .prize = 0x93,
                  .hidePrizeFlag = 0x00 } },
    { .id = 148,  // $94 FORCE_ARMOR
      .record = { .monster = 0x7F, .unused40 = 0x40, .prize = 0x94,
                  .hidePrizeFlag = 0x00 } },
    { .id = 149,  // $95 DIAMONDARMOR
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 150,  // $96 DARK_GEAR
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 151,  // $97 TAO_ROBE
      .record = { .monster = 0x9C, .unused40 = 0x40, .prize = 0x97,
                  .hidePrizeFlag = 0x00 } },
    { .id = 152,  // $98 CRYSTAL_MAIL
      .record = { .monster = 0x67, .unused40 = 0x40, .prize = 0x61,
                  .hidePrizeFlag = 0x00 } },
    { .id = 153,  // $99 CZARINA_GOWN
      .record = { .monster = 0xFC, .unused40 = 0x40, .prize = 0x9C,
                  .hidePrizeFlag = 0x00 } },
    { .id = 154,  // $9A GENJI_ARMOR
      .record = { .monster = 0xF2, .unused40 = 0x40, .prize = 0xA9,
                  .hidePrizeFlag = 0x00 } },
    { .id = 155,  // $9B IMPS_ARMOR
      .record = { .monster = 0x7E, .unused40 = 0x40, .prize = 0x65,
                  .hidePrizeFlag = 0x00 } },
    { .id = 156,  // $9C MINERVA
      .record = { .monster = 0x54, .unused40 = 0x40, .prize = 0x99,
                  .hidePrizeFlag = 0x00 } },
    { .id = 157,  // $9D TABBY_SUIT
      .record = { .monster = 0x80, .unused40 = 0x40, .prize = 0x9E,
                  .hidePrizeFlag = 0x00 } },
    { .id = 158,  // $9E CHOCOBO_SUIT
      .record = { .monster = 0xFB, .unused40 = 0x40, .prize = 0x9F,
                  .hidePrizeFlag = 0x00 } },
    { .id = 159,  // $9F MOOGLE_SUIT
      .record = { .monster = 0x6A, .unused40 = 0x40, .prize = 0xA0,
                  .hidePrizeFlag = 0x00 } },
    { .id = 160,  // $A0 NUTKIN_SUIT
      .record = { .monster = 0xC8, .unused40 = 0x40, .prize = 0x9A,
                  .hidePrizeFlag = 0x00 } },
    { .id = 161,  // $A1 BEHEMOTHSUIT
      .record = { .monster = 0xBD, .unused40 = 0x40, .prize = 0xA2,
                  .hidePrizeFlag = 0x00 } },
    { .id = 162,  // $A2 SNOW_MUFFLER
      .record = { .monster = 0x07, .unused40 = 0x40, .prize = 0xDF,
                  .hidePrizeFlag = 0x00 } },
    { .id = 163,  // $A3 NOISEBLASTER
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 164,  // $A4 BIO_BLASTER
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 165,  // $A5 FLASH
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 166,  // $A6 CHAIN_SAW
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 167,  // $A7 DEBILITATOR
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 168,  // $A8 DRILL
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 169,  // $A9 AIR_ANCHOR
      .record = { .monster = 0x84, .unused40 = 0x40, .prize = 0xC0,
                  .hidePrizeFlag = 0x00 } },
    { .id = 170,  // $AA AUTOCROSSBOW
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 171,  // $AB FIRE_SKEAN
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 172,  // $AC WATER_EDGE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 173,  // $AD BOLT_EDGE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 174,  // $AE INVIZ_EDGE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 175,  // $AF SHADOW_EDGE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 176,  // $B0 GOGGLES
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 177,  // $B1 STAR_PENDANT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 178,  // $B2 PEACE_RING
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 179,  // $B3 AMULET
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 180,  // $B4 WHITE_CAPE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 181,  // $B5 JEWEL_RING
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 182,  // $B6 FAIRY_RING
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 183,  // $B7 BARRIER_RING
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 184,  // $B8 MITHRILGLOVE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 185,  // $B9 GUARD_RING
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 186,  // $BA RUNNINGSHOES
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 187,  // $BB WALL_RING
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 188,  // $BC CHERUB_DOWN
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 189,  // $BD CURE_RING
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 190,  // $BE TRUE_KNIGHT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 191,  // $BF DRAGOONBOOTS
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 192,  // $C0 ZEPHYR_CAPE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 193,  // $C1 CZARINA_RING
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 194,  // $C2 CURSED_RING
      .record = { .monster = 0x16, .unused40 = 0x40, .prize = 0xA9,
                  .hidePrizeFlag = 0x00 } },
    { .id = 195,  // $C3 EARRINGS
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 196,  // $C4 ATLAS_ARMLET
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 197,  // $C5 BLIZZARD_ORB
      .record = { .monster = 0x85, .unused40 = 0x40, .prize = 0xC6,
                  .hidePrizeFlag = 0x00 } },
    { .id = 198,  // $C6 RAGE_RING
      .record = { .monster = 0x85, .unused40 = 0x40, .prize = 0xC5,
                  .hidePrizeFlag = 0x00 } },
    { .id = 199,  // $C7 SNEAK_RING
      .record = { .monster = 0xF0, .unused40 = 0x40, .prize = 0xCF,
                  .hidePrizeFlag = 0x00 } },
    { .id = 200,  // $C8 POD_BRACELET
      .record = { .monster = 0xC1, .unused40 = 0x40, .prize = 0xC9,
                  .hidePrizeFlag = 0x00 } },
    { .id = 201,  // $C9 HERO_RING
      .record = { .monster = 0x7E, .unused40 = 0x40, .prize = 0xC8,
                  .hidePrizeFlag = 0x00 } },
    { .id = 202,  // $CA RIBBON
      .record = { .monster = 0x0D, .unused40 = 0x40, .prize = 0xCD,
                  .hidePrizeFlag = 0x00 } },
    { .id = 203,  // $CB MUSCLE_BELT
      .record = { .monster = 0x85, .unused40 = 0x40, .prize = 0xCC,
                  .hidePrizeFlag = 0x00 } },
    { .id = 204,  // $CC CRYSTAL_ORB
      .record = { .monster = 0xF2, .unused40 = 0x40, .prize = 0xCD,
                  .hidePrizeFlag = 0x00 } },
    { .id = 205,  // $CD GOLD_HAIRPIN
      .record = { .monster = 0xB7, .unused40 = 0x40, .prize = 0xD9,
                  .hidePrizeFlag = 0x00 } },
    { .id = 206,  // $CE ECONOMIZER
      .record = { .monster = 0xE4, .unused40 = 0x40, .prize = 0xD9,
                  .hidePrizeFlag = 0x00 } },
    { .id = 207,  // $CF THIEF_GLOVE
      .record = { .monster = 0x2B, .unused40 = 0x40, .prize = 0x00,
                  .hidePrizeFlag = 0x00 } },
    { .id = 208,  // $D0 GAUNTLET
      .record = { .monster = 0xE4, .unused40 = 0x40, .prize = 0x62,
                  .hidePrizeFlag = 0x00 } },
    { .id = 209,  // $D1 GENJI_GLOVE
      .record = { .monster = 0xC1, .unused40 = 0x40, .prize = 0x62,
                  .hidePrizeFlag = 0x00 } },
    { .id = 210,  // $D2 HYPER_WRIST
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 211,  // $D3 OFFERING
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 212,  // $D4 BEADS
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 213,  // $D5 BLACK_BELT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 214,  // $D6 COIN_TOSS
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 215,  // $D7 FAKEMUSTACHE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 216,  // $D8 GEM_BOX
      .record = { .monster = 0x7F, .unused40 = 0x40, .prize = 0xCE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 217,  // $D9 DRAGON_HORN
      .record = { .monster = 0x7E, .unused40 = 0x40, .prize = 0xCD,
                  .hidePrizeFlag = 0x00 } },
    { .id = 218,  // $DA MERIT_AWARD
      .record = { .monster = 0x67, .unused40 = 0x40, .prize = 0xE7,
                  .hidePrizeFlag = 0xFF } },
    { .id = 219,  // $DB MEMENTO_RING
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xDB,
                  .hidePrizeFlag = 0x00 } },
    { .id = 220,  // $DC SAFETY_BIT
      .record = { .monster = 0x54, .unused40 = 0x40, .prize = 0xD9,
                  .hidePrizeFlag = 0x00 } },
    { .id = 221,  // $DD RELIC_RING
      .record = { .monster = 0xFC, .unused40 = 0x40, .prize = 0xDF,
                  .hidePrizeFlag = 0x00 } },
    { .id = 222,  // $DE MOOGLE_CHARM
      .record = { .monster = 0xBD, .unused40 = 0x40, .prize = 0xDF,
                  .hidePrizeFlag = 0x00 } },
    { .id = 223,  // $DF CHARM_BANGLE
      .record = { .monster = 0x07, .unused40 = 0x40, .prize = 0xD9,
                  .hidePrizeFlag = 0x00 } },
    { .id = 224,  // $E0 MARVEL_SHOES
      .record = { .monster = 0x27, .unused40 = 0x40, .prize = 0xE5,
                  .hidePrizeFlag = 0x00 } },
    { .id = 225,  // $E1 BACK_GUARD
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 226,  // $E2 GALE_HAIRPIN
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 227,  // $E3 SNIPER_SIGHT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 228,  // $E4 EXP_EGG
      .record = { .monster = 0x16, .unused40 = 0x40, .prize = 0xE5,
                  .hidePrizeFlag = 0x00 } },
    { .id = 229,  // $E5 TINTINABAR
      .record = { .monster = 0x0D, .unused40 = 0x40, .prize = 0xE4,
                  .hidePrizeFlag = 0x00 } },
    { .id = 230,  // $E6 SPRINT_SHOES
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 231,  // $E7 RENAME_CARD
      .record = { .monster = 0x25, .unused40 = 0x40, .prize = 0xE0,
                  .hidePrizeFlag = 0x00 } },
    { .id = 232,  // $E8 TONIC
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 233,  // $E9 POTION
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 234,  // $EA X_POTION
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 235,  // $EB TINCTURE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 236,  // $EC ETHER
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 237,  // $ED X_ETHER
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 238,  // $EE ELIXIR
      .record = { .monster = 0x4C, .unused40 = 0x40, .prize = 0xE7,
                  .hidePrizeFlag = 0x00 } },
    { .id = 239,  // $EF MEGALIXIR
      .record = { .monster = 0x37, .unused40 = 0x40, .prize = 0xE5,
                  .hidePrizeFlag = 0x00 } },
    { .id = 240,  // $F0 FENIX_DOWN
      .record = { .monster = 0x4C, .unused40 = 0x40, .prize = 0xF9,
                  .hidePrizeFlag = 0x00 } },
    { .id = 241,  // $F1 REVIVIFY
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 242,  // $F2 ANTIDOTE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 243,  // $F3 EYEDROP
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 244,  // $F4 SOFT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 245,  // $F5 REMEDY
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 246,  // $F6 SLEEPING_BAG
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 247,  // $F7 TENT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 248,  // $F8 GREEN_CHERRY
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 249,  // $F9 MAGICITE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 250,  // $FA SUPER_BALL
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 251,  // $FB ECHO_SCREEN
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 252,  // $FC SMOKE_BOMB
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 253,  // $FD WARP_STONE
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 254,  // $FE DRIED_MEAT
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
    { .id = 255,  // $FF EMPTY
      .record = { .monster = 0x40, .unused40 = 0x40, .prize = 0xEE,
                  .hidePrizeFlag = 0x00 } },
}};

}  // namespace ostinato::test
