// AUTO-GENERATED by tools/asm_parser/parse_formations.py
// Ground-truth cond_battle words (.index decimal, raw formation words).
// (original-src pinned at 1ea47b5) — DO NOT EDIT BY HAND.
#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

struct ExpectedConditionalBattle {
    std::uint16_t index;
    std::uint16_t trigger;
    std::uint16_t replacement;
};

inline constexpr std::array<ExpectedConditionalBattle, 16> kExpectedConditionalBattles = {{
    { .index =  0, .trigger = 0x01C4, .replacement = 0x01A8 },
    { .index =  1, .trigger = 0x0000, .replacement = 0x0000 },
    { .index =  2, .trigger = 0x0000, .replacement = 0x0000 },
    { .index =  3, .trigger = 0x0000, .replacement = 0x0000 },
    { .index =  4, .trigger = 0x0000, .replacement = 0x0000 },
    { .index =  5, .trigger = 0x0000, .replacement = 0x0000 },
    { .index =  6, .trigger = 0x0000, .replacement = 0x0000 },
    { .index =  7, .trigger = 0x0000, .replacement = 0x0000 },
    { .index =  8, .trigger = 0x0000, .replacement = 0x0000 },
    { .index =  9, .trigger = 0x0000, .replacement = 0x0000 },
    { .index = 10, .trigger = 0x0000, .replacement = 0x0000 },
    { .index = 11, .trigger = 0x0000, .replacement = 0x0000 },
    { .index = 12, .trigger = 0x0000, .replacement = 0x0000 },
    { .index = 13, .trigger = 0x0000, .replacement = 0x0000 },
    { .index = 14, .trigger = 0x0000, .replacement = 0x0000 },
    { .index = 15, .trigger = 0x0000, .replacement = 0x0000 },
}};

}  // namespace ostinato::test
