// AUTO-GENERATED by tools/asm_parser/parse_dance_prop.py
// Source: src/battle/dance_prop.asm (DanceProp, 8 dances x 4 ATTACK bytes)
// Source: include/const.inc (ATTACK / DANCE values)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_dance_prop.py \
//       --source-root  original-src \
//       --inc-out      src/data/generated/dance_prop_data.inc \
//       --fixture-out  tests/fixtures/dance_prop_expected.h

// Test fixture for tests/test_dance_properties.cpp — the
// ground-truth record bytes. The full-corpus test asserts, per
// entry: fixture id == position, table id enumerator ==
// position, and a 4-byte memcmp of the packed record against
// src/data/generated/dance_prop_data.inc's row.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 4-byte dance record: the four ATTACK bytes in slot order
// (probability tiers 7/16, 3/8, 1/8, 1/16). Values are the exact ROM
// bytes with every upstream symbol resolved — deliberately independent
// of the enum-symbol rows in dance_prop_data.inc, so symbol/value drift
// in either artifact fails the full-corpus byte-equivalence test.
struct ExpectedDanceRecord {
    std::uint8_t attack1, attack2, attack3, attack4;  // ATTACK bytes
};
static_assert(sizeof(ExpectedDanceRecord) == 4,
              "fixture record must stay byte-identical to a ROM dance record");

// One fixture entry: the record's identity as a typed field (raw decimal
// index — the fixture stays independent of the port's DanceId header)
// alongside the raw record bytes. Mirrors ostinato::DancePropertiesEntry
// without depending on it.
struct ExpectedDanceEntry {
    std::uint8_t id;
    ExpectedDanceRecord record;
};

inline constexpr std::array<ExpectedDanceEntry, 8> kExpectedDanceEntries = {{  // ROM DanceProp
    { .id = 0,  // $00 WIND_SONG
      .record = { .attack1 = 0x65, .attack2 = 0x66, .attack3 = 0x70, .attack4 = 0x75 } },
    { .id = 1,  // $01 FOREST_SUITE
      .record = { .attack1 = 0x67, .attack2 = 0x68, .attack3 = 0x6B, .attack4 = 0x76 } },
    { .id = 2,  // $02 DESERT_ARIA
      .record = { .attack1 = 0x69, .attack2 = 0x6A, .attack3 = 0x65, .attack4 = 0x77 } },
    { .id = 3,  // $03 LOVE_SONATA
      .record = { .attack1 = 0x6B, .attack2 = 0x6C, .attack3 = 0x71, .attack4 = 0x78 } },
    { .id = 4,  // $04 EARTH_BLUES
      .record = { .attack1 = 0x6D, .attack2 = 0x6E, .attack3 = 0x66, .attack4 = 0x79 } },
    { .id = 5,  // $05 WATER_RONDO
      .record = { .attack1 = 0x6F, .attack2 = 0x70, .attack3 = 0x6C, .attack4 = 0x7A } },
    { .id = 6,  // $06 DUSK_REQUIUM
      .record = { .attack1 = 0x72, .attack2 = 0x71, .attack3 = 0x6B, .attack4 = 0x7B } },
    { .id = 7,  // $07 SNOWMAN_JAZZ
      .record = { .attack1 = 0x73, .attack2 = 0x74, .attack3 = 0x71, .attack4 = 0x7C } },
}};

}  // namespace ostinato::test
