// AUTO-GENERATED by tools/asm_parser/parse_encounters.py — DO NOT EDIT.
// (original-src pinned at 1ea47b5) — DO NOT EDIT BY HAND.
#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// Ground-truth inline field/battle.asm tables, raw values.
inline constexpr std::array<std::uint8_t, 16> kExpectedWorldBattleBg = {{ 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x00, 0x01, 0x2F, 0x03, 0x05, 0x05, 0x06, 0x07 }};

inline constexpr std::array<std::uint8_t, 8> kExpectedBattleBgRateSlot = {{ 3, 2, 1, 2, 3, 0, 3, 3 }};

inline constexpr std::array<std::uint8_t, 8> kExpectedBattleBgGroupOffset = {{ 0, 1, 2, 1, 0, 3, 0, 0 }};

inline constexpr std::array<std::uint16_t, 16> kExpectedWorldBattleRateIncrements = {{ 192, 96, 384, 0, 96, 48, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0 }};

inline constexpr std::array<std::uint16_t, 16> kExpectedSubBattleRateIncrements = {{ 112, 64, 352, 512, 56, 32, 176, 256, 0, 0, 0, 0, 0, 0, 0, 0 }};

}  // namespace ostinato::test
