// AUTO-GENERATED by tools/asm_parser/parse_const_enums.py — DO NOT EDIT.
// Regenerate from original-src/include/const.inc; hand edits will be lost.
// Expected values for every emitted limit.
// X(name, expected_value) — consumed by tests/test_game_limits.cpp.
#pragma once

#define OSTINATO_LIMIT_EXPECTED(X) \
    X(kMaxGil, 9999999) \
    X(kMaxSteps, 9999999) \
    X(kMaxExperience, 15000000)
