// AUTO-GENERATED by tools/asm_parser/parse_genju_prop.py
// Source: src/menu/genju_prop.asm (GenjuProp, ROM D8/6E00,
//         27 espers x 11 bytes: five {rate, spell} pairs + bonus)
// Source: include/const.inc (ATTACK / GENJU / GENJU_BONUS values)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_genju_prop.py \
//       --source-root  original-src \
//       --inc-out      src/data/generated/genju_prop_data.inc \
//       --fixture-out  tests/fixtures/genju_prop_expected.h

// Test fixture for tests/test_esper_properties.cpp — the
// ground-truth record bytes. The full-corpus test asserts, per
// entry: fixture id == position + kExpectedEsperFirstId, table
// id enumerator == fixture id, and an 11-byte memcmp of the
// packed record against src/data/generated/genju_prop_data.inc's
// row.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 11-byte esper record: five {rate, spell} byte pairs in ROM
// order (rate first, spell second) then the bonus byte. Values are the
// exact ROM bytes with every upstream symbol resolved — deliberately
// independent of the enum-symbol rows in genju_prop_data.inc, so
// symbol/value drift in either artifact fails the full-corpus
// byte-equivalence test.
struct ExpectedEsperRecord {
    std::uint8_t rate1, spell1;   // ATTACK byte after its learn rate
    std::uint8_t rate2, spell2;
    std::uint8_t rate3, spell3;
    std::uint8_t rate4, spell4;
    std::uint8_t rate5, spell5;
    std::uint8_t bonus;           // GENJU_BONUS byte
};
static_assert(sizeof(ExpectedEsperRecord) == 11,
              "fixture record must stay byte-identical to a ROM esper record");

// One fixture entry: the record's identity as a typed field (the raw
// decimal GENJU value — the fixture stays independent of the port's
// EsperId header) alongside the raw record bytes. Mirrors
// ostinato::EsperPropertiesEntry without depending on it.
struct ExpectedEsperEntry {
    std::uint8_t id;
    ExpectedEsperRecord record;
};

// The GENJU index space starts at $36 (RAMUH) — parser-derived
// from const.inc, so the fixture's id arithmetic never
// hand-types the base.
inline constexpr std::uint8_t kExpectedEsperFirstId = 54;

inline constexpr std::array<ExpectedEsperEntry, 27> kExpectedEsperEntries = {{  // ROM GenjuProp
    { .id = 54,  // $36 RAMUH
      .record = { .rate1 = 0x0A, .spell1 = 0x02, .rate2 = 0x02, .spell2 = 0x07,
                  .rate3 = 0x05, .spell3 = 0x03, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x0D } },
    { .id = 55,  // $37 IFRIT
      .record = { .rate1 = 0x0A, .spell1 = 0x00, .rate2 = 0x05, .spell2 = 0x05,
                  .rate3 = 0x01, .spell3 = 0x04, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x09 } },
    { .id = 56,  // $38 SHIVA
      .record = { .rate1 = 0x0A, .spell1 = 0x01, .rate2 = 0x05, .spell2 = 0x06,
                  .rate3 = 0x04, .spell3 = 0x1A, .rate4 = 0x04, .spell4 = 0x29,
                  .rate5 = 0x03, .spell5 = 0x2D, .bonus = 0xFF } },
    { .id = 57,  // $39 SIREN
      .record = { .rate1 = 0x0A, .spell1 = 0x1D, .rate2 = 0x08, .spell2 = 0x1B,
                  .rate3 = 0x07, .spell3 = 0x19, .rate4 = 0x06, .spell4 = 0x00,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x00 } },
    { .id = 58,  // $3A TERRATO
      .record = { .rate1 = 0x03, .spell1 = 0x15, .rate2 = 0x01, .spell2 = 0x11,
                  .rate3 = 0x01, .spell3 = 0x16, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x01 } },
    { .id = 59,  // $3B SHOAT
      .record = { .rate1 = 0x08, .spell1 = 0x08, .rate2 = 0x05, .spell2 = 0x0C,
                  .rate3 = 0x02, .spell3 = 0x0D, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x00 } },
    { .id = 60,  // $3C MADUIN
      .record = { .rate1 = 0x03, .spell1 = 0x05, .rate2 = 0x03, .spell2 = 0x06,
                  .rate3 = 0x03, .spell3 = 0x07, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x0F } },
    { .id = 61,  // $3D BISMARK
      .record = { .rate1 = 0x14, .spell1 = 0x00, .rate2 = 0x14, .spell2 = 0x01,
                  .rate3 = 0x14, .spell3 = 0x02, .rate4 = 0x02, .spell4 = 0x30,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x0A } },
    { .id = 62,  // $3E STRAY
      .record = { .rate1 = 0x07, .spell1 = 0x1E, .rate2 = 0x05, .spell2 = 0x23,
                  .rate3 = 0x02, .spell3 = 0x22, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x0F } },
    { .id = 63,  // $3F PALIDOR
      .record = { .rate1 = 0x14, .spell1 = 0x1F, .rate2 = 0x14, .spell2 = 0x19,
                  .rate3 = 0x02, .spell3 = 0x27, .rate4 = 0x02, .spell4 = 0x28,
                  .rate5 = 0x05, .spell5 = 0x22, .bonus = 0xFF } },
    { .id = 64,  // $40 TRITOCH
      .record = { .rate1 = 0x01, .spell1 = 0x09, .rate2 = 0x01, .spell2 = 0x0A,
                  .rate3 = 0x01, .spell3 = 0x0B, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x10 } },
    { .id = 65,  // $41 ODIN
      .record = { .rate1 = 0x01, .spell1 = 0x13, .rate2 = 0x00, .spell2 = 0xFF,
                  .rate3 = 0x00, .spell3 = 0xFF, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x0B } },
    { .id = 66,  // $42 RAIDEN
      .record = { .rate1 = 0x01, .spell1 = 0x2B, .rate2 = 0x00, .spell2 = 0xFF,
                  .rate3 = 0x00, .spell3 = 0xFF, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x0A } },
    { .id = 67,  // $43 BAHAMUT
      .record = { .rate1 = 0x02, .spell1 = 0x0F, .rate2 = 0x00, .spell2 = 0xFF,
                  .rate3 = 0x00, .spell3 = 0xFF, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x02 } },
    { .id = 68,  // $44 ALEXANDR
      .record = { .rate1 = 0x02, .spell1 = 0x0E, .rate2 = 0x0A, .spell2 = 0x25,
                  .rate3 = 0x0A, .spell3 = 0x1C, .rate4 = 0x0A, .spell4 = 0x2C,
                  .rate5 = 0x0F, .spell5 = 0x33, .bonus = 0xFF } },
    { .id = 69,  // $45 CRUSADER
      .record = { .rate1 = 0x01, .spell1 = 0x17, .rate2 = 0x0A, .spell2 = 0x13,
                  .rate3 = 0x00, .spell3 = 0xFF, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x05 } },
    { .id = 70,  // $46 RAGNAROK
      .record = { .rate1 = 0x01, .spell1 = 0x14, .rate2 = 0x00, .spell2 = 0xFF,
                  .rate3 = 0x00, .spell3 = 0xFF, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0xFF } },
    { .id = 71,  // $47 KIRIN
      .record = { .rate1 = 0x05, .spell1 = 0x2D, .rate2 = 0x01, .spell2 = 0x2E,
                  .rate3 = 0x03, .spell3 = 0x34, .rate4 = 0x04, .spell4 = 0x32,
                  .rate5 = 0x05, .spell5 = 0x18, .bonus = 0xFF } },
    { .id = 72,  // $48 ZONESEEK
      .record = { .rate1 = 0x14, .spell1 = 0x1A, .rate2 = 0x0F, .spell2 = 0x29,
                  .rate3 = 0x05, .spell3 = 0x25, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x10 } },
    { .id = 73,  // $49 CARBUNKL
      .record = { .rate1 = 0x05, .spell1 = 0x24, .rate2 = 0x03, .spell2 = 0x1F,
                  .rate3 = 0x02, .spell3 = 0x25, .rate4 = 0x02, .spell4 = 0x1C,
                  .rate5 = 0x02, .spell5 = 0x2A, .bonus = 0xFF } },
    { .id = 74,  // $4A PHANTOM
      .record = { .rate1 = 0x03, .spell1 = 0x21, .rate2 = 0x03, .spell2 = 0x26,
                  .rate3 = 0x05, .spell3 = 0x10, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x03 } },
    { .id = 75,  // $4B SRAPHIM
      .record = { .rate1 = 0x05, .spell1 = 0x30, .rate2 = 0x08, .spell2 = 0x2E,
                  .rate3 = 0x14, .spell3 = 0x2D, .rate4 = 0x0A, .spell4 = 0x34,
                  .rate5 = 0x04, .spell5 = 0x33, .bonus = 0xFF } },
    { .id = 76,  // $4C GOLEM
      .record = { .rate1 = 0x05, .spell1 = 0x1C, .rate2 = 0x05, .spell2 = 0x20,
                  .rate3 = 0x05, .spell3 = 0x2E, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x0E } },
    { .id = 77,  // $4D UNICORN
      .record = { .rate1 = 0x04, .spell1 = 0x2E, .rate2 = 0x03, .spell2 = 0x33,
                  .rate3 = 0x02, .spell3 = 0x2C, .rate4 = 0x01, .spell4 = 0x1C,
                  .rate5 = 0x01, .spell5 = 0x25, .bonus = 0xFF } },
    { .id = 78,  // $4E FENRIR
      .record = { .rate1 = 0x0A, .spell1 = 0x2A, .rate2 = 0x05, .spell2 = 0x12,
                  .rate3 = 0x03, .spell3 = 0x20, .rate4 = 0x00, .spell4 = 0xFF,
                  .rate5 = 0x00, .spell5 = 0xFF, .bonus = 0x04 } },
    { .id = 79,  // $4F STARLET
      .record = { .rate1 = 0x19, .spell1 = 0x2D, .rate2 = 0x10, .spell2 = 0x2E,
                  .rate3 = 0x01, .spell3 = 0x2F, .rate4 = 0x14, .spell4 = 0x34,
                  .rate5 = 0x14, .spell5 = 0x33, .bonus = 0x0E } },
    { .id = 80,  // $50 PHOENIX
      .record = { .rate1 = 0x0A, .spell1 = 0x30, .rate2 = 0x02, .spell2 = 0x31,
                  .rate3 = 0x01, .spell3 = 0x35, .rate4 = 0x02, .spell4 = 0x2F,
                  .rate5 = 0x03, .spell5 = 0x09, .bonus = 0xFF } },
}};

}  // namespace ostinato::test
