// AUTO-GENERATED by tools/asm_parser/parse_anim_prop.py
// Source: btlgfx_main.asm:48980 (ItemAnimPtrs, ROM d1/0000)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_anim_prop.py \
//       --source-root original-src --repo-root .

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// The raw 32 ItemAnimPtrs ROM words (row*14, or 0xFFFF for none).
// The test re-multiplies each AttackAnimationIndex by 14 and
// memcmps against this to prove byte identity.
inline constexpr std::array<std::uint16_t, 32>
kExpectedItemAnimPtrs = {{
    0xFFFF,
    0xFFFF,
    0xFFFF,
    0xFFFF,
    0xFFFF,
    0xFFFF,
    0xFFFF,
    0x15FC,
    0x126E,
    0x127C,
    0x128A,
    0x1298,
    0x12A6,
    0x12B4,
    0x12C2,
    0x12D0,
    0x12DE,
    0x12EC,
    0x12FA,
    0x1308,
    0x1316,
    0x1324,
    0x1332,
    0x1340,
    0x134E,
    0x135C,
    0x136A,
    0x1378,
    0x1386,
    0x1394,
    0x13A2,
    0xFFFF,
}};

}  // namespace ostinato::test
