// AUTO-GENERATED by tools/asm_parser/parse_magic_prop.py
// Source: src/battle/magic_prop_en.dat (MagicProp, ROM C4/6AC0,
//         256 records x 14 bytes; layout per notes/battle-ram.txt:208-249
//         and LoadMagicProp in src/battle/battle_main.asm)
// Source: include/const.inc (ATTACK / TARGET / STATUS_ID / ELEMENT values)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_magic_prop.py \
//       --source-root  original-src \
//       --inc-out      src/data/generated/magic_prop_en_data.inc \
//       --fixture-out  tests/fixtures/magic_prop_expected.h

// Test fixture for tests/test_attack_properties.cpp — the
// ground-truth record bytes. The full-corpus test asserts, per
// entry: fixture id == position, table id enumerator ==
// position, and a 14-byte memcmp of the packed record against
// src/data/generated/magic_prop_en_data.inc's row.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 14-byte magic_prop record; field names and order mirror the
// battle-ram.txt:210-249 record layout. Values are the exact ROM bytes —
// deliberately independent of the typed-surface rows in
// magic_prop_en_data.inc, so decomposition/builder drift in either
// artifact fails the full-corpus byte-equivalence test.
struct ExpectedAttackRecord {
    std::uint8_t targeting;
    std::uint8_t element;
    std::uint8_t traits;
    std::uint8_t flags1;
    std::uint8_t flags2;
    std::uint8_t mpCost;
    std::uint8_t power;
    std::uint8_t misc;
    std::uint8_t hitRate;
    std::uint8_t specialEffect;
    std::uint8_t status1, status2, status3, status4;
};
static_assert(sizeof(ExpectedAttackRecord) == 14,
              "fixture record must stay byte-identical to a ROM magic_prop record");

// One fixture entry: the record's identity as a typed field (raw decimal
// index — the fixture stays independent of the port's AttackId header)
// alongside the raw record bytes. Mirrors ostinato::AttackPropertiesEntry
// without depending on it.
struct ExpectedAttackEntry {
    std::uint8_t id;
    ExpectedAttackRecord record;
};

inline constexpr std::array<ExpectedAttackEntry, 256> kExpectedAttackEntries = {{  // ROM MagicProp (EN)
    { .id =   0,  // $00 FIRE
      .record = { .targeting = 0x61, .element = 0x01, .traits = 0x00,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x04, .power = 0x15,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =   1,  // $01 ICE
      .record = { .targeting = 0x61, .element = 0x02, .traits = 0x00,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x05, .power = 0x16,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =   2,  // $02 BOLT
      .record = { .targeting = 0x61, .element = 0x04, .traits = 0x00,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x06, .power = 0x14,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =   3,  // $03 POISON
      .record = { .targeting = 0x41, .element = 0x08, .traits = 0x08,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x03, .power = 0x19,
                  .misc = 0x00, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x04, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =   4,  // $04 DRAIN
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x08,
                  .flags1 = 0x2A, .flags2 = 0x02, .mpCost = 0x0F, .power = 0x26,
                  .misc = 0x00, .hitRate = 0x78, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =   5,  // $05 FIRE_2
      .record = { .targeting = 0x61, .element = 0x01, .traits = 0x00,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x14, .power = 0x3C,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =   6,  // $06 ICE_2
      .record = { .targeting = 0x61, .element = 0x02, .traits = 0x00,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x15, .power = 0x3E,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =   7,  // $07 BOLT_2
      .record = { .targeting = 0x61, .element = 0x04, .traits = 0x00,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x16, .power = 0x3D,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =   8,  // $08 BIO
      .record = { .targeting = 0x61, .element = 0x08, .traits = 0x08,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x1A, .power = 0x35,
                  .misc = 0x00, .hitRate = 0x78, .specialEffect = 0xFF,
                  .status1 = 0x04, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =   9,  // $09 FIRE_3
      .record = { .targeting = 0x61, .element = 0x01, .traits = 0x00,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x33, .power = 0x79,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  10,  // $0A ICE_3
      .record = { .targeting = 0x61, .element = 0x02, .traits = 0x00,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x34, .power = 0x7A,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  11,  // $0B BOLT_3
      .record = { .targeting = 0x61, .element = 0x04, .traits = 0x00,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x35, .power = 0x78,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  12,  // $0C BREAK
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x28, .flags2 = 0x10, .mpCost = 0x19, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x78, .specialEffect = 0xFF,
                  .status1 = 0x40, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  13,  // $0D DOOM
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x28, .flags2 = 0x10, .mpCost = 0x23, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x5F, .specialEffect = 0x35,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  14,  // $0E PEARL
      .record = { .targeting = 0x41, .element = 0x20, .traits = 0x00,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x28, .power = 0x6C,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  15,  // $0F FLARE
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x28, .flags2 = 0x00, .mpCost = 0x2D, .power = 0x3C,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  16,  // $10 DEMI
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x42,
                  .flags1 = 0x2A, .flags2 = 0x90, .mpCost = 0x21, .power = 0x08,
                  .misc = 0x00, .hitRate = 0x78, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  17,  // $11 QUARTR
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x42,
                  .flags1 = 0x2A, .flags2 = 0x90, .mpCost = 0x30, .power = 0x0C,
                  .misc = 0x00, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  18,  // $12 X_ZONE
      .record = { .targeting = 0x6A, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x2A, .flags2 = 0x10, .mpCost = 0x35, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x55, .specialEffect = 0x23,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  19,  // $13 METEOR
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x60,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x3E, .power = 0x24,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  20,  // $14 ULTIMA
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x2A, .flags2 = 0x20, .mpCost = 0x50, .power = 0x96,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  21,  // $15 QUAKE
      .record = { .targeting = 0x04, .element = 0x40, .traits = 0x30,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x32, .power = 0x6F,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0x25,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  22,  // $16 W_WIND
      .record = { .targeting = 0x04, .element = 0x00, .traits = 0x52,
                  .flags1 = 0x02, .flags2 = 0x90, .mpCost = 0x4B, .power = 0x0F,
                  .misc = 0x00, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  23,  // $17 MERTON
      .record = { .targeting = 0x04, .element = 0x11, .traits = 0x30,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x55, .power = 0x8A,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  24,  // $18 SCAN
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x00, .mpCost = 0x03, .power = 0x00,
                  .misc = 0x00, .hitRate = 0xDE, .specialEffect = 0x10,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  25,  // $19 SLOW
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x00, .mpCost = 0x05, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x78, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x04, .status4 = 0x00 } },
    { .id =  26,  // $1A RASP
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x08,
                  .flags1 = 0xA8, .flags2 = 0x00, .mpCost = 0x0C, .power = 0x0A,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  27,  // $1B MUTE
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x00, .mpCost = 0x08, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x08, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  28,  // $1C SAFE
      .record = { .targeting = 0x01, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x20, .mpCost = 0x0C, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x40, .status4 = 0x00 } },
    { .id =  29,  // $1D SLEEP
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x00, .mpCost = 0x05, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x6F, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x80, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  30,  // $1E MUDDLE
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x00, .mpCost = 0x08, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x5E, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x20, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  31,  // $1F HASTE
      .record = { .targeting = 0x01, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x20, .mpCost = 0x0A, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x08, .status4 = 0x00 } },
    { .id =  32,  // $20 STOP
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x00, .mpCost = 0x0A, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x10, .status4 = 0x00 } },
    { .id =  33,  // $21 BSERK
      .record = { .targeting = 0x01, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x00, .mpCost = 0x10, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x10, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  34,  // $22 FLOAT
      .record = { .targeting = 0x21, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x0B, .flags2 = 0x20, .mpCost = 0x11, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x80 } },
    { .id =  35,  // $23 IMP
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x09, .flags2 = 0x08, .mpCost = 0x0A, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x20, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  36,  // $24 RFLECT
      .record = { .targeting = 0x01, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x20, .mpCost = 0x16, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x80, .status4 = 0x00 } },
    { .id =  37,  // $25 SHELL
      .record = { .targeting = 0x01, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x20, .mpCost = 0x0F, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x20, .status4 = 0x00 } },
    { .id =  38,  // $26 VANISH
      .record = { .targeting = 0x01, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x0A, .flags2 = 0x28, .mpCost = 0x12, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x10, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  39,  // $27 HASTE2
      .record = { .targeting = 0x29, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x20, .mpCost = 0x26, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x08, .status4 = 0x00 } },
    { .id =  40,  // $28 SLOW_2
      .record = { .targeting = 0x69, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x08, .flags2 = 0x00, .mpCost = 0x1A, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x04, .status4 = 0x00 } },
    { .id =  41,  // $29 OSMOSE
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x08,
                  .flags1 = 0xAA, .flags2 = 0x02, .mpCost = 0x01, .power = 0x1A,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  42,  // $2A WARP
      .record = { .targeting = 0x00, .element = 0x00, .traits = 0x10,
                  .flags1 = 0x13, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x18,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  43,  // $2B QUICK
      .record = { .targeting = 0x02, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x12, .flags2 = 0x20, .mpCost = 0x63, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x43,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  44,  // $2C DISPEL
      .record = { .targeting = 0x41, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x0B, .flags2 = 0x24, .mpCost = 0x19, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x10, .status2 = 0x14, .status3 = 0xFE, .status4 = 0x84 } },
    { .id =  45,  // $2D CURE
      .record = { .targeting = 0x21, .element = 0x00, .traits = 0x28,
                  .flags1 = 0x09, .flags2 = 0x21, .mpCost = 0x05, .power = 0x0A,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  46,  // $2E CURE_2
      .record = { .targeting = 0x21, .element = 0x00, .traits = 0x28,
                  .flags1 = 0x09, .flags2 = 0x21, .mpCost = 0x19, .power = 0x1C,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  47,  // $2F CURE_3
      .record = { .targeting = 0x21, .element = 0x00, .traits = 0x28,
                  .flags1 = 0x09, .flags2 = 0x21, .mpCost = 0x28, .power = 0x42,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  48,  // $30 LIFE
      .record = { .targeting = 0x01, .element = 0x00, .traits = 0x2C,
                  .flags1 = 0x0B, .flags2 = 0xA5, .mpCost = 0x1E, .power = 0x02,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x20 } },
    { .id =  49,  // $31 LIFE_2
      .record = { .targeting = 0x01, .element = 0x00, .traits = 0x2C,
                  .flags1 = 0x0B, .flags2 = 0xA5, .mpCost = 0x3C, .power = 0x10,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x20 } },
    { .id =  50,  // $32 ANTDOT
      .record = { .targeting = 0x03, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x0B, .flags2 = 0x24, .mpCost = 0x03, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x04, .status2 = 0x40, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  51,  // $33 REMEDY
      .record = { .targeting = 0x03, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x0B, .flags2 = 0x24, .mpCost = 0x0F, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x45, .status2 = 0xE8, .status3 = 0x14, .status4 = 0x00 } },
    { .id =  52,  // $34 REGEN
      .record = { .targeting = 0x03, .element = 0x00, .traits = 0x08,
                  .flags1 = 0x08, .flags2 = 0x20, .mpCost = 0x0A, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x02, .status4 = 0x00 } },
    { .id =  53,  // $35 LIFE_3
      .record = { .targeting = 0x03, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x0A, .flags2 = 0x20, .mpCost = 0x32, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x04 } },
    { .id =  54,  // $36 RAMUH
      .record = { .targeting = 0x6E, .element = 0x04, .traits = 0x80,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x19, .power = 0x32,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  55,  // $37 IFRIT
      .record = { .targeting = 0x6E, .element = 0x01, .traits = 0x80,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x1A, .power = 0x33,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  56,  // $38 SHIVA
      .record = { .targeting = 0x6E, .element = 0x02, .traits = 0x80,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x1B, .power = 0x34,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  57,  // $39 SIREN
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x80,
                  .flags1 = 0x02, .flags2 = 0x00, .mpCost = 0x10, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x88, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x08, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  58,  // $3A TERRATO
      .record = { .targeting = 0x6E, .element = 0x40, .traits = 0x80,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x28, .power = 0x5D,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0x25,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  59,  // $3B SHOAT
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x82,
                  .flags1 = 0x02, .flags2 = 0x10, .mpCost = 0x2D, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x60, .specialEffect = 0xFF,
                  .status1 = 0x40, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  60,  // $3C MADUIN
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x80,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x2C, .power = 0x37,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  61,  // $3D BISMARK
      .record = { .targeting = 0x6E, .element = 0x80, .traits = 0x80,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x32, .power = 0x3A,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  62,  // $3E STRAY
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x80,
                  .flags1 = 0x02, .flags2 = 0x00, .mpCost = 0x1C, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x80, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x20, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  63,  // $3F PALIDOR
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x70,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x3D, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x13,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x20 } },
    { .id =  64,  // $40 TRITOCH
      .record = { .targeting = 0x6E, .element = 0x07, .traits = 0x80,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x44, .power = 0x6E,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  65,  // $41 ODIN
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x82,
                  .flags1 = 0x02, .flags2 = 0x10, .mpCost = 0x46, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x6E, .specialEffect = 0x23,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  66,  // $42 RAIDEN
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x82,
                  .flags1 = 0x02, .flags2 = 0x10, .mpCost = 0x50, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x8C, .specialEffect = 0x23,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  67,  // $43 BAHAMUT
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x56, .power = 0x5C,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  68,  // $44 ALEXANDR
      .record = { .targeting = 0x6E, .element = 0x20, .traits = 0x80,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x5A, .power = 0x72,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  69,  // $45 CRUSADER
      .record = { .targeting = 0x04, .element = 0x00, .traits = 0x40,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x60, .power = 0xBE,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x24,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  70,  // $46 RAGNAROK
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x80,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x06, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x12,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  71,  // $47 KIRIN
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x08,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x12, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x02, .status4 = 0x00 } },
    { .id =  72,  // $48 ZONESEEK
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x1E, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x20, .status4 = 0x00 } },
    { .id =  73,  // $49 CARBUNKL
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x24, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x80, .status4 = 0x00 } },
    { .id =  74,  // $4A PHANTOM
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x26, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x10, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  75,  // $4B SRAPHIM
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x28,
                  .flags1 = 0x02, .flags2 = 0x21, .mpCost = 0x28, .power = 0x12,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  76,  // $4C GOLEM
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x21, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x11,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  77,  // $4D UNICORN
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x24, .mpCost = 0x1E, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x45, .status2 = 0xE8, .status3 = 0x14, .status4 = 0x00 } },
    { .id =  78,  // $4E FENRIR
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x46, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x04, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  79,  // $4F STARLET
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x28,
                  .flags1 = 0x02, .flags2 = 0x21, .mpCost = 0x4A, .power = 0x22,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  80,  // $50 PHOENIX
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x0C,
                  .flags1 = 0x02, .flags2 = 0xA5, .mpCost = 0x6E, .power = 0x04,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  81,  // $51 FIRE_SKEAN
      .record = { .targeting = 0x6E, .element = 0x01, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x64,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  82,  // $52 WATER_EDGE
      .record = { .targeting = 0x6E, .element = 0x80, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x64,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  83,  // $53 BOLT_EDGE
      .record = { .targeting = 0x6E, .element = 0x04, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x64,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  84,  // $54 STORM
      .record = { .targeting = 0x7E, .element = 0x02, .traits = 0x10,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x64,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  85,  // $55 DISPATCH
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x21,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x78,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  86,  // $56 RETORT
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x38,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x3C,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  87,  // $57 SLASH
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x23,
                  .flags1 = 0x22, .flags2 = 0xA0, .mpCost = 0x00, .power = 0x08,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x40, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  88,  // $58 QUADRA_SLAM
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x01,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x48,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x32,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  89,  // $59 EMPOWERER
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x28,
                  .flags1 = 0xA2, .flags2 = 0x22, .mpCost = 0x00, .power = 0x31,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x36,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  90,  // $5A STUNNER
      .record = { .targeting = 0x7A, .element = 0x00, .traits = 0x50,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x61,
                  .misc = 0x00, .hitRate = 0x8C, .specialEffect = 0x3F,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x10, .status4 = 0x00 } },
    { .id =  91,  // $5B QUADRA_SLICE
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x21,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x46,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x32,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  92,  // $5C CLEAVE
      .record = { .targeting = 0x7A, .element = 0x00, .traits = 0x32,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x01, .hitRate = 0xB6, .specialEffect = 0x23,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  93,  // $5D PUMMEL
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x21,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x6E,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x00,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  94,  // $5E AURABOLT
      .record = { .targeting = 0x53, .element = 0x20, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x44,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  95,  // $5F SUPLEX
      .record = { .targeting = 0x7E, .element = 0x00, .traits = 0x21,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0xB4,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x30,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  96,  // $60 FIRE_DANCE
      .record = { .targeting = 0x7A, .element = 0x01, .traits = 0x50,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x2A,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  97,  // $61 MANTRA
      .record = { .targeting = 0x3E, .element = 0x00, .traits = 0x38,
                  .flags1 = 0x22, .flags2 = 0x25, .mpCost = 0x00, .power = 0x01,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x15,
                  .status1 = 0x05, .status2 = 0x48, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  98,  // $62 AIR_BLADE
      .record = { .targeting = 0x7A, .element = 0x10, .traits = 0x50,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x4E,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id =  99,  // $63 SPIRALER
      .record = { .targeting = 0x3E, .element = 0x00, .traits = 0x38,
                  .flags1 = 0x02, .flags2 = 0x25, .mpCost = 0x00, .power = 0xC8,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x16,
                  .status1 = 0x67, .status2 = 0xF9, .status3 = 0x14, .status4 = 0x02 } },
    { .id = 100,  // $64 BUM_RUSH
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x80,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 101,  // $65 WIND_SLASH
      .record = { .targeting = 0x7E, .element = 0x10, .traits = 0x50,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x30,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 102,  // $66 SUN_BATH
      .record = { .targeting = 0x3E, .element = 0x00, .traits = 0x38,
                  .flags1 = 0x02, .flags2 = 0x21, .mpCost = 0x00, .power = 0x32,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 103,  // $67 RAGE
      .record = { .targeting = 0x7E, .element = 0x00, .traits = 0x50,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x32,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 104,  // $68 HARVESTER
      .record = { .targeting = 0x3E, .element = 0x00, .traits = 0x10,
                  .flags1 = 0x02, .flags2 = 0x24, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x45, .status2 = 0xE8, .status3 = 0x14, .status4 = 0x00 } },
    { .id = 105,  // $69 SAND_STORM
      .record = { .targeting = 0x7E, .element = 0x10, .traits = 0x50,
                  .flags1 = 0x02, .flags2 = 0x00, .mpCost = 0x00, .power = 0x2D,
                  .misc = 0x00, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 106,  // $6A ANTLION
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x22, .flags2 = 0x10, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 107,  // $6B ELF_FIRE
      .record = { .targeting = 0x53, .element = 0x01, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x48,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 108,  // $6C SPECTER
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x78, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x20, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 109,  // $6D LAND_SLIDE
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x41,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 110,  // $6E SONIC_BOOM
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x22, .flags2 = 0xA0, .mpCost = 0x00, .power = 0x0A,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x40, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 111,  // $6F EL_NINO
      .record = { .targeting = 0x7E, .element = 0x80, .traits = 0x50,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x3D,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 112,  // $70 PLASMA
      .record = { .targeting = 0x53, .element = 0x04, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x46,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 113,  // $71 SNARE
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x22, .flags2 = 0x10, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x64, .specialEffect = 0x23,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 114,  // $72 CAVE_IN
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x22, .flags2 = 0xA0, .mpCost = 0x00, .power = 0x0C,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x40, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 115,  // $73 SNOWBALL
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x22, .flags2 = 0xA0, .mpCost = 0x00, .power = 0x08,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x40, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 116,  // $74 SURGE
      .record = { .targeting = 0x7E, .element = 0x02, .traits = 0x50,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x37,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 117,  // $75 COKATRICE
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x22,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x00, .power = 0x32,
                  .misc = 0x00, .hitRate = 0x60, .specialEffect = 0xFF,
                  .status1 = 0x40, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 118,  // $76 WOMBAT
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x58,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x25,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 119,  // $77 KITTY
      .record = { .targeting = 0x3E, .element = 0x00, .traits = 0x10,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x08, .status4 = 0x00 } },
    { .id = 120,  // $78 TAPIR
      .record = { .targeting = 0x3E, .element = 0x00, .traits = 0x10,
                  .flags1 = 0x02, .flags2 = 0x25, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x17,
                  .status1 = 0x67, .status2 = 0xF9, .status3 = 0x14, .status4 = 0x00 } },
    { .id = 121,  // $79 WHUMP
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x35,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x25,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 122,  // $7A WILD_BEAR
      .record = { .targeting = 0x3E, .element = 0x00, .traits = 0x38,
                  .flags1 = 0x02, .flags2 = 0x25, .mpCost = 0x00, .power = 0x64,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x47, .status2 = 0xF9, .status3 = 0x14, .status4 = 0x02 } },
    { .id = 123,  // $7B POIS_FROG
      .record = { .targeting = 0x53, .element = 0x08, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x38,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x04, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 124,  // $7C ICE_RABBIT
      .record = { .targeting = 0x3E, .element = 0x00, .traits = 0x38,
                  .flags1 = 0x02, .flags2 = 0x21, .mpCost = 0x00, .power = 0x3C,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 125,  // $7D BIO_BLAST_TOOL
      .record = { .targeting = 0x6A, .element = 0x08, .traits = 0xC0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x14,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x04, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 126,  // $7E FLASH_TOOL
      .record = { .targeting = 0x6A, .element = 0x00, .traits = 0xC0,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x00, .power = 0x2A,
                  .misc = 0x00, .hitRate = 0x80, .specialEffect = 0xFF,
                  .status1 = 0x01, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 127,  // $7F CHOCOBOP
      .record = { .targeting = 0x7E, .element = 0x00, .traits = 0x70,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x24,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x25,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 128,  // $80 H_BOMB
      .record = { .targeting = 0x7E, .element = 0x00, .traits = 0x10,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x82,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 129,  // $81 SEVEN_FLUSH
      .record = { .targeting = 0x7E, .element = 0x00, .traits = 0x10,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x54,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 130,  // $82 SHOCK
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x80,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 131,  // $83 FIRE_BEAM
      .record = { .targeting = 0x43, .element = 0x01, .traits = 0x00,
                  .flags1 = 0x20, .flags2 = 0x20, .mpCost = 0x00, .power = 0x3C,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 132,  // $84 BOLT_BEAM
      .record = { .targeting = 0x43, .element = 0x04, .traits = 0x00,
                  .flags1 = 0x20, .flags2 = 0x20, .mpCost = 0x00, .power = 0x3E,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 133,  // $85 ICE_BEAM
      .record = { .targeting = 0x43, .element = 0x02, .traits = 0x00,
                  .flags1 = 0x20, .flags2 = 0x20, .mpCost = 0x00, .power = 0x3D,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 134,  // $86 BIO_BLAST_MAGITEK
      .record = { .targeting = 0x6A, .element = 0x08, .traits = 0x40,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x3C,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x04, .status2 = 0x40, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 135,  // $87 HEAL_FORCE
      .record = { .targeting = 0x03, .element = 0x00, .traits = 0x28,
                  .flags1 = 0x02, .flags2 = 0x21, .mpCost = 0x00, .power = 0x32,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 136,  // $88 CONFUSER
      .record = { .targeting = 0x6A, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x80, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x20, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 137,  // $89 XFER
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x02, .flags2 = 0x10, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x78, .specialEffect = 0x23,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 138,  // $8A TEKMISSILE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x3A,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x40, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 139,  // $8B CONDEMNED
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x06, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x01, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 140,  // $8C ROULETTE
      .record = { .targeting = 0xC0, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x26, .flags2 = 0x20, .mpCost = 0x0A, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 141,  // $8D CLEANSWEEP
      .record = { .targeting = 0x6E, .element = 0x80, .traits = 0x40,
                  .flags1 = 0x26, .flags2 = 0x00, .mpCost = 0x1E, .power = 0x32,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 142,  // $8E AQUA_RAKE
      .record = { .targeting = 0x6A, .element = 0x90, .traits = 0x00,
                  .flags1 = 0x26, .flags2 = 0x00, .mpCost = 0x16, .power = 0x47,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 143,  // $8F AERO
      .record = { .targeting = 0x6A, .element = 0x10, .traits = 0x00,
                  .flags1 = 0x26, .flags2 = 0x00, .mpCost = 0x29, .power = 0x7D,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 144,  // $90 BLOW_FISH
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x60,
                  .flags1 = 0x26, .flags2 = 0x20, .mpCost = 0x32, .power = 0x01,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x1A,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 145,  // $91 BIG_GUARD
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x06, .flags2 = 0x20, .mpCost = 0x50, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x60, .status4 = 0x00 } },
    { .id = 146,  // $92 REVENGE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x60,
                  .flags1 = 0x26, .flags2 = 0x20, .mpCost = 0x1F, .power = 0x01,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x3D,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 147,  // $93 PEARL_WIND
      .record = { .targeting = 0x2E, .element = 0x00, .traits = 0x68,
                  .flags1 = 0x06, .flags2 = 0x21, .mpCost = 0x2D, .power = 0x01,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x1B,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 148,  // $94 L5_DOOM
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x06, .flags2 = 0x40, .mpCost = 0x16, .power = 0x00,
                  .misc = 0x03, .hitRate = 0x05, .specialEffect = 0xFF,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 149,  // $95 L4_FLARE
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x60,
                  .flags1 = 0x06, .flags2 = 0x40, .mpCost = 0x2A, .power = 0x42,
                  .misc = 0x02, .hitRate = 0x04, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 150,  // $96 L3_MUDDLE
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x06, .flags2 = 0x40, .mpCost = 0x1C, .power = 0x00,
                  .misc = 0x03, .hitRate = 0x03, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x20, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 151,  // $97 REFLECT_LORE
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x06, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x03, .hitRate = 0x00, .specialEffect = 0x1C,
                  .status1 = 0x01, .status2 = 0x08, .status3 = 0x04, .status4 = 0x00 } },
    { .id = 152,  // $98 PEARL_LORE
      .record = { .targeting = 0x6E, .element = 0x20, .traits = 0x00,
                  .flags1 = 0x06, .flags2 = 0x40, .mpCost = 0x32, .power = 0x78,
                  .misc = 0x02, .hitRate = 0x00, .specialEffect = 0x1D,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 153,  // $99 STEP_MINE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x06, .flags2 = 0x20, .mpCost = 0x01, .power = 0x20,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x1E,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 154,  // $9A FORCEFIELD
      .record = { .targeting = 0x04, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x06, .flags2 = 0x20, .mpCost = 0x18, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x31,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 155,  // $9B DISCHORD
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x26, .flags2 = 0x00, .mpCost = 0x44, .power = 0x00,
                  .misc = 0x02, .hitRate = 0x64, .specialEffect = 0x1F,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 156,  // $9C SOUR_MOUTH
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x26, .flags2 = 0x00, .mpCost = 0x20, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x25, .status2 = 0xA8, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 157,  // $9D PEP_UP
      .record = { .targeting = 0x03, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x66, .flags2 = 0xA5, .mpCost = 0x01, .power = 0x10,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x20,
                  .status1 = 0x47, .status2 = 0xFB, .status3 = 0x14, .status4 = 0x00 } },
    { .id = 158,  // $9E RIPPLER
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x26, .flags2 = 0x00, .mpCost = 0x42, .power = 0x00,
                  .misc = 0x03, .hitRate = 0x6F, .specialEffect = 0x21,
                  .status1 = 0x37, .status2 = 0xFD, .status3 = 0xFE, .status4 = 0x84 } },
    { .id = 159,  // $9F STONE
      .record = { .targeting = 0x63, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x26, .flags2 = 0x00, .mpCost = 0x16, .power = 0x28,
                  .misc = 0x02, .hitRate = 0x4B, .specialEffect = 0x22,
                  .status1 = 0x00, .status2 = 0x20, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 160,  // $A0 QUASAR
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x06, .flags2 = 0x20, .mpCost = 0x32, .power = 0x39,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 161,  // $A1 GRANDTRAIN
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x06, .flags2 = 0x20, .mpCost = 0x40, .power = 0x54,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 162,  // $A2 EXPLODER
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x66, .flags2 = 0x20, .mpCost = 0x01, .power = 0x01,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x19,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 163,  // $A3 IMP_SONG
      .record = { .targeting = 0x6B, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x08, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x03, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x20, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 164,  // $A4 CLEAR
      .record = { .targeting = 0x02, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x45,
                  .status1 = 0x25, .status2 = 0xE9, .status3 = 0x10, .status4 = 0x00 } },
    { .id = 165,  // $A5 VIRITE
      .record = { .targeting = 0x6B, .element = 0x08, .traits = 0x08,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x14,
                  .misc = 0x00, .hitRate = 0x50, .specialEffect = 0xFF,
                  .status1 = 0x04, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 166,  // $A6 CHOKESMOKE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x04,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x03, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x02, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 167,  // $A7 SCHILLER
      .record = { .targeting = 0x6A, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x50, .specialEffect = 0xFF,
                  .status1 = 0x01, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 168,  // $A8 LULLABY
      .record = { .targeting = 0x6A, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x5A, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x80, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 169,  // $A9 ACID_RAIN
      .record = { .targeting = 0x6A, .element = 0x88, .traits = 0x48,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x19,
                  .misc = 0x00, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x40, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 170,  // $AA CONFUSION
      .record = { .targeting = 0x6B, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x44, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x20, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 171,  // $AB MEGAZERK
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x0A, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x10, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 172,  // $AC ENEMY_MUTE
      .record = { .targeting = 0x6B, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x5A, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x08, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 173,  // $AD NET
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x10, .status4 = 0x00 } },
    { .id = 174,  // $AE SLIMER
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x04, .status4 = 0x00 } },
    { .id = 175,  // $AF DELTA_HIT
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x40, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 176,  // $B0 ENTWINE
      .record = { .targeting = 0x6B, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x04, .status4 = 0x00 } },
    { .id = 177,  // $B1 BLASTER
      .record = { .targeting = 0x6B, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x2A, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x46, .specialEffect = 0xFF,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 178,  // $B2 CYCLONIC
      .record = { .targeting = 0x6B, .element = 0x00, .traits = 0x42,
                  .flags1 = 0x22, .flags2 = 0x80, .mpCost = 0x14, .power = 0x0F,
                  .misc = 0x00, .hitRate = 0x4B, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x02, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 179,  // $B3 FIRE_BALL
      .record = { .targeting = 0x6B, .element = 0x01, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x32,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 180,  // $B4 ATOMIC_RAY
      .record = { .targeting = 0x6B, .element = 0x01, .traits = 0x00,
                  .flags1 = 0x2A, .flags2 = 0x00, .mpCost = 0x14, .power = 0x50,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 181,  // $B5 TEK_LASER
      .record = { .targeting = 0x43, .element = 0x04, .traits = 0x00,
                  .flags1 = 0x2A, .flags2 = 0x00, .mpCost = 0x14, .power = 0x14,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 182,  // $B6 DIFFUSER
      .record = { .targeting = 0x6B, .element = 0x04, .traits = 0x00,
                  .flags1 = 0x2A, .flags2 = 0x00, .mpCost = 0x14, .power = 0x3E,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 183,  // $B7 WAVECANNON
      .record = { .targeting = 0x6B, .element = 0x04, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x6E,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 184,  // $B8 MEGA_VOLT
      .record = { .targeting = 0x63, .element = 0x04, .traits = 0x00,
                  .flags1 = 0x2A, .flags2 = 0x00, .mpCost = 0x14, .power = 0x14,
                  .misc = 0x00, .hitRate = 0x96, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 185,  // $B9 GIGA_VOLT
      .record = { .targeting = 0x63, .element = 0x04, .traits = 0x00,
                  .flags1 = 0x2A, .flags2 = 0x00, .mpCost = 0x14, .power = 0x6E,
                  .misc = 0x00, .hitRate = 0x82, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 186,  // $BA BLIZZARD
      .record = { .targeting = 0x6B, .element = 0x02, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x19,
                  .misc = 0x00, .hitRate = 0x8C, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 187,  // $BB ABSOLUTE0
      .record = { .targeting = 0x6B, .element = 0x02, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x6E,
                  .misc = 0x00, .hitRate = 0x8C, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 188,  // $BC MAGNITUDE8
      .record = { .targeting = 0x6A, .element = 0x40, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x64,
                  .misc = 0x00, .hitRate = 0x82, .specialEffect = 0x25,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 189,  // $BD RAID
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x08,
                  .flags1 = 0x22, .flags2 = 0x02, .mpCost = 0x14, .power = 0x28,
                  .misc = 0x00, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 190,  // $BE FLASH_RAIN
      .record = { .targeting = 0x6B, .element = 0x82, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x3C,
                  .misc = 0x00, .hitRate = 0x8C, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 191,  // $BF TEKBARRIER
      .record = { .targeting = 0x03, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x20, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0xC0, .status4 = 0x00 } },
    { .id = 192,  // $C0 FALLEN_ONE
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x40,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 193,  // $C1 WALLCHANGE
      .record = { .targeting = 0x12, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x26,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 194,  // $C2 ESCAPE
      .record = { .targeting = 0x02, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x27,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x20 } },
    { .id = 195,  // $C3 FIFTY_GS
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x0A, .flags2 = 0x24, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x80 } },
    { .id = 196,  // $C4 MIND_BLAST
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x6E, .specialEffect = 0x28,
                  .status1 = 0x67, .status2 = 0xF9, .status3 = 0x14, .status4 = 0x00 } },
    { .id = 197,  // $C5 N_CROSS
      .record = { .targeting = 0x6E, .element = 0x02, .traits = 0x00,
                  .flags1 = 0x0A, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x03, .hitRate = 0x5A, .specialEffect = 0x29,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x02 } },
    { .id = 198,  // $C6 FLARE_STAR
      .record = { .targeting = 0x6B, .element = 0x01, .traits = 0x60,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x50,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x2A,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 199,  // $C7 LOVE_TOKEN
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x02, .hitRate = 0x00, .specialEffect = 0x2D,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 200,  // $C8 SEIZE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x24, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x2E,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x04, .status4 = 0x00 } },
    { .id = 201,  // $C9 R_POLARITY
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x2B,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 202,  // $CA TARGETTING
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x2F,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 203,  // $CB SNEEZE
      .record = { .targeting = 0x63, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x00, .specialEffect = 0x38,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x20 } },
    { .id = 204,  // $CC S_CROSS
      .record = { .targeting = 0x6B, .element = 0x01, .traits = 0x40,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x78,
                  .misc = 0x00, .hitRate = 0x78, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 205,  // $CD LAUNCHER
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x72,
                  .flags1 = 0x22, .flags2 = 0x80, .mpCost = 0x14, .power = 0x08,
                  .misc = 0x00, .hitRate = 0x64, .specialEffect = 0x2C,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 206,  // $CE CHARM
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x02, .hitRate = 0x50, .specialEffect = 0x34,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 207,  // $CF COLD_DUST
      .record = { .targeting = 0x43, .element = 0x02, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x03, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x02 } },
    { .id = 208,  // $D0 TENTACLE
      .record = { .targeting = 0x6A, .element = 0x00, .traits = 0x01,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x92,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 209,  // $D1 HYPERDRIVE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x20,
                  .flags1 = 0x2A, .flags2 = 0x20, .mpCost = 0x00, .power = 0x76,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x40, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 210,  // $D2 TRAIN
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x01, .status2 = 0x08, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 211,  // $D3 EVIL_TOOT
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x78, .specialEffect = 0x3B,
                  .status1 = 0x25, .status2 = 0x71, .status3 = 0x04, .status4 = 0x00 } },
    { .id = 212,  // $D4 GRAV_BOMB
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x12,
                  .flags1 = 0x22, .flags2 = 0x90, .mpCost = 0x14, .power = 0x08,
                  .misc = 0x00, .hitRate = 0x64, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 213,  // $D5 ENGULF
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x10,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x02, .hitRate = 0x00, .specialEffect = 0x39,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 214,  // $D6 DISASTER
      .record = { .targeting = 0x63, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x2A, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x3E, .specialEffect = 0xFF,
                  .status1 = 0x21, .status2 = 0x29, .status3 = 0x00, .status4 = 0x80 } },
    { .id = 215,  // $D7 SHRAPNEL
      .record = { .targeting = 0x63, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x78,
                  .misc = 0x00, .hitRate = 0x78, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 216,  // $D8 BOMBLET
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 217,  // $D9 HEART_BURN
      .record = { .targeting = 0x63, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x1E,
                  .misc = 0x00, .hitRate = 0x78, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 218,  // $DA ZINGER
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x3A,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 219,  // $DB DISCARD
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x44,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 220,  // $DC OVERCAST
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x02, .hitRate = 0x00, .specialEffect = 0x37,
                  .status1 = 0x00, .status2 = 0x01, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 221,  // $DD MISSILE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x22, .flags2 = 0x80, .mpCost = 0x14, .power = 0x04,
                  .misc = 0x00, .hitRate = 0x7E, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x40, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 222,  // $DE GONER
      .record = { .targeting = 0x6E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0xDC,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 223,  // $DF METEO
      .record = { .targeting = 0x6B, .element = 0x00, .traits = 0x60,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x3C,
                  .misc = 0x00, .hitRate = 0x50, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 224,  // $E0 REVENGER
      .record = { .targeting = 0x6A, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x24, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x10, .status2 = 0x04, .status3 = 0xEA, .status4 = 0x84 } },
    { .id = 225,  // $E1 PHANTASM
      .record = { .targeting = 0x6A, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x02, .hitRate = 0x00, .specialEffect = 0x3E,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 226,  // $E2 DREAD
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x4B, .specialEffect = 0xFF,
                  .status1 = 0x40, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 227,  // $E3 SHOCK_WAVE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x19,
                  .misc = 0x00, .hitRate = 0x78, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 228,  // $E4 BLAZE
      .record = { .targeting = 0x63, .element = 0x01, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x14, .power = 0x44,
                  .misc = 0x00, .hitRate = 0x78, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 229,  // $E5 SOUL_OUT
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x00,
                  .misc = 0x03, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x02, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 230,  // $E6 GALE_CUT
      .record = { .targeting = 0x6E, .element = 0x10, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x0F,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 231,  // $E7 SHIMSHAM
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x2A, .flags2 = 0xA0, .mpCost = 0x14, .power = 0x08,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 232,  // $E8 LODE_STONE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x02,
                  .flags1 = 0x22, .flags2 = 0xA0, .mpCost = 0x14, .power = 0x0C,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 233,  // $E9 SCAR_BEAM
      .record = { .targeting = 0x6E, .element = 0x20, .traits = 0x40,
                  .flags1 = 0x2A, .flags2 = 0x20, .mpCost = 0x14, .power = 0x1C,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 234,  // $EA BABABREATH
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x00, .specialEffect = 0x33,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x20 } },
    { .id = 235,  // $EB LIFESHAVER
      .record = { .targeting = 0x43, .element = 0x40, .traits = 0x08,
                  .flags1 = 0x22, .flags2 = 0x22, .mpCost = 0x14, .power = 0x54,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 236,  // $EC FIRE_WALL
      .record = { .targeting = 0x43, .element = 0x01, .traits = 0x00,
                  .flags1 = 0x2A, .flags2 = 0x20, .mpCost = 0x14, .power = 0x32,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 237,  // $ED SLIDE
      .record = { .targeting = 0x6E, .element = 0x40, .traits = 0x00,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x14, .power = 0x4B,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x25,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 238,  // $EE BATTLE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x01,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 239,  // $EF SPECIAL
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x01,
                  .flags1 = 0x22, .flags2 = 0x00, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 240,  // $F0 RIOT_BLADE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x8E,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 241,  // $F1 MIRAGER
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x8B,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 242,  // $F2 BACK_BLADE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x8C,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 243,  // $F3 SHADOWFANG
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x8C,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x40, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 244,  // $F4 ROYALSHOCK
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x8F,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 245,  // $F5 TIGERBREAK
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x8C,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 246,  // $F6 SPIN_EDGE
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x8F,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 247,  // $F7 SABRESOUL
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x82,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 248,  // $F8 STAR_PRISM
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0x82,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x01, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x80, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 249,  // $F9 RED_CARD
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x93,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 250,  // $FA MOOGLERUSH
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x96,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 251,  // $FB X_METEO
      .record = { .targeting = 0x43, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x92,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 252,  // $FC TAKEDOWN
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x37,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x25,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 253,  // $FD WILD_FANG
      .record = { .targeting = 0x53, .element = 0x00, .traits = 0xA0,
                  .flags1 = 0x22, .flags2 = 0x20, .mpCost = 0x00, .power = 0x42,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0x25,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 254,  // $FE LAGOMORPH
      .record = { .targeting = 0x3E, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x02, .flags2 = 0x25, .mpCost = 0x00, .power = 0x0A,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x05, .status2 = 0x80, .status3 = 0x00, .status4 = 0x00 } },
    { .id = 255,  // $FF NONE
      .record = { .targeting = 0x00, .element = 0x00, .traits = 0x00,
                  .flags1 = 0x00, .flags2 = 0x00, .mpCost = 0x00, .power = 0x00,
                  .misc = 0x00, .hitRate = 0x00, .specialEffect = 0xFF,
                  .status1 = 0x00, .status2 = 0x00, .status3 = 0x00, .status4 = 0x00 } },
}};

}  // namespace ostinato::test
