// AUTO-GENERATED by tools/asm_parser/parse_menu_orders.py
// Source: skills.asm (GenjuOrder, MagicOrderTbl), equip.asm (ImpItem)
// Source: include/const.inc (GENJU / ATTACK / ITEM values)
// (original-src pinned at 1ea47b5; cross-checked against the vanilla ROM
// over the whole list)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_menu_orders.py \
//       --source-root  original-src

// Test fixture for tests/test_menu_orders.cpp — the raw cartridge
// bytes of all three lists, deliberately independent of the typed
// rows in the generated tables.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// Each esper's place in the menu list, in esper index order.
inline constexpr std::array<std::uint8_t, 27> kExpectedEsperMenuOrder = {
     1,  5,  6,  3, 19,  9,  8, 12,  4, 16, 18, 23, 27, 24, 21, 26, 25,  2, 14, 11, 10, 15, 13,  7, 17, 20, 22};

// The six magic-order rows, four raw bytes each including the
// $FF terminator.
inline constexpr std::array<std::array<std::uint8_t, 4>, 6>
    kExpectedMagicListOrder = {{
    {{ 0x2D, 0x00, 0x18, 0xFF }},
    {{ 0x2D, 0x18, 0x00, 0xFF }},
    {{ 0x00, 0x18, 0x2D, 0xFF }},
    {{ 0x00, 0x2D, 0x18, 0xFF }},
    {{ 0x18, 0x2D, 0x00, 0xFF }},
    {{ 0x18, 0x00, 0x2D, 0xFF }},
}};

// The imp's sixteen equipment slots.
inline constexpr std::array<std::uint8_t, 16> kExpectedImpEquipment = {
    0x66, 0x82, 0x24, 0x65, 0x83, 0x9B, 0x1C, 0x12, 0x16, 0x33, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};

}  // namespace ostinato::test
