// AUTO-GENERATED by tools/asm_parser/parse_metamorph_prop.py
// Source: src/battle/metamorph_prop.dat (MetamorphProp, ROM C4/7F40,
//         32 packs x 4 bytes; consumed by the metamorph effect
//         TargetEffect_12 in src/battle/battle_main.asm:9385-9409)
// Source: src/battle/battle_main.asm MetamorphRateTbl (:10008-10009,
//         ROM c2/3dc5 — the eight probability bytes)
// Source: include/const.inc (ITEM values)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_metamorph_prop.py \
//       --source-root  original-src \
//       --pack-inc-out src/data/generated/metamorph_prop_data.inc \
//       --rate-inc-out src/data/generated/metamorph_rate_data.inc \
//       --fixture-out  tests/fixtures/metamorph_expected.h

// Test fixture for tests/test_monster_properties.cpp — the
// ground-truth bytes for both metamorph tables. The
// full-corpus tests assert, per entry: fixture index ==
// position, table index field == position, and byte equality
// of the pack/rate data against the generated rows.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 4-byte metamorph pack; values are the exact ROM bytes —
// deliberately independent of the typed-surface rows in
// metamorph_prop_data.inc, so symbol/value drift in either artifact
// fails the full-corpus byte-equivalence test.
struct ExpectedMetamorphPack {
    std::uint8_t item0, item1, item2, item3;
};
static_assert(sizeof(ExpectedMetamorphPack) == 4,
              "fixture pack must stay byte-identical to a ROM metamorph pack");

// One fixture entry per table row: identity as a typed field (raw
// decimal index) alongside the raw bytes. Mirror
// ostinato::MetamorphPackEntry / MetamorphRateEntry without depending
// on them.
struct ExpectedMetamorphPackEntry {
    std::uint8_t index;
    ExpectedMetamorphPack record;
};

struct ExpectedMetamorphRateEntry {
    std::uint8_t index;
    std::uint8_t value;
};

inline constexpr std::array<ExpectedMetamorphPackEntry, 32> kExpectedMetamorphPacks = {{  // ROM MetamorphProp
    { .index =  0,
      .record = { .item0 = 0xF2, .item1 = 0xF8, .item2 = 0xF3, .item3 = 0xF4 } },
    { .index =  1,
      .record = { .item0 = 0xF7, .item1 = 0xF0, .item2 = 0xFD, .item3 = 0xF1 } },
    { .index =  2,
      .record = { .item0 = 0xFE, .item1 = 0xFE, .item2 = 0xFE, .item3 = 0xFE } },
    { .index =  3,
      .record = { .item0 = 0xF5, .item1 = 0xF5, .item2 = 0xF5, .item3 = 0xF5 } },
    { .index =  4,
      .record = { .item0 = 0x0A, .item1 = 0x74, .item2 = 0x8C, .item3 = 0x5B } },
    { .index =  5,
      .record = { .item0 = 0x22, .item1 = 0x5D, .item2 = 0x76, .item3 = 0x8F } },
    { .index =  6,
      .record = { .item0 = 0x14, .item1 = 0x63, .item2 = 0x7E, .item3 = 0x98 } },
    { .index =  7,
      .record = { .item0 = 0x9B, .item1 = 0x83, .item2 = 0x65, .item3 = 0x24 } },
    { .index =  8,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0x17 } },
    { .index =  9,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0xE0 } },
    { .index = 10,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0xE5 } },
    { .index = 11,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0xEF } },
    { .index = 12,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0xEA } },
    { .index = 13,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0xED } },
    { .index = 14,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0xEE } },
    { .index = 15,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0xD0 } },
    { .index = 16,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0xD1 } },
    { .index = 17,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0xDC } },
    { .index = 18,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0xE4 } },
    { .index = 19,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0xCA } },
    { .index = 20,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0x60 } },
    { .index = 21,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0x61 } },
    { .index = 22,
      .record = { .item0 = 0xE8, .item1 = 0xE8, .item2 = 0xE8, .item3 = 0x62 } },
    { .index = 23,
      .record = { .item0 = 0xC2, .item1 = 0xC2, .item2 = 0x82, .item3 = 0xDD } },
    { .index = 24,
      .record = { .item0 = 0xBD, .item1 = 0xBD, .item2 = 0xDC, .item3 = 0xC8 } },
    { .index = 25,
      .record = { .item0 = 0x50, .item1 = 0x50, .item2 = 0x05, .item3 = 0x29 } },
    { .index = 26,
      .record = { .item0 = 0x00, .item1 = 0x00, .item2 = 0x00, .item3 = 0x00 } },
    { .index = 27,
      .record = { .item0 = 0x00, .item1 = 0x00, .item2 = 0x00, .item3 = 0x00 } },
    { .index = 28,
      .record = { .item0 = 0x00, .item1 = 0x00, .item2 = 0x00, .item3 = 0x00 } },
    { .index = 29,
      .record = { .item0 = 0x00, .item1 = 0x00, .item2 = 0x00, .item3 = 0x00 } },
    { .index = 30,
      .record = { .item0 = 0x00, .item1 = 0x00, .item2 = 0x00, .item3 = 0x00 } },
    { .index = 31,
      .record = { .item0 = 0x00, .item1 = 0x00, .item2 = 0x00, .item3 = 0x00 } },
}};

inline constexpr std::array<ExpectedMetamorphRateEntry, 8> kExpectedMetamorphRates = {{  // MetamorphRateTbl
    { .index = 0, .value = 0xFF },
    { .index = 1, .value = 0xC0 },
    { .index = 2, .value = 0x80 },
    { .index = 3, .value = 0x40 },
    { .index = 4, .value = 0x20 },
    { .index = 5, .value = 0x10 },
    { .index = 6, .value = 0x08 },
    { .index = 7, .value = 0x00 },
}};

}  // namespace ostinato::test
