// AUTO-GENERATED by tools/asm_parser/parse_monster_items.py
// Source: src/battle/monster_items.asm (ROM CF/3000, 384 records x
//         4 bytes: rare steal, common steal, rare drop, common drop —
//         the monster_steal/monster_drop macro pairs; the MonsterItems
//         label lives at the include site, battle_main.asm:16468-16469)
// Source: include/const.inc (ITEM / MONSTER values)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_monster_items.py \
//       --source-root  original-src \
//       --inc-out      src/data/generated/monster_items_data.inc \
//       --fixture-out  tests/fixtures/monster_items_expected.h

// Test fixture for tests/test_monster_tables.cpp — the
// ground-truth record bytes. The full-corpus test asserts, per
// entry: fixture id == position, table id enumerator ==
// position, and a 4-byte memcmp of the packed record against
// src/data/generated/monster_items_data.inc's row.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 4-byte monster_items record: rare steal, common steal, rare
// drop, common drop. Values are the exact ROM bytes with every upstream
// symbol resolved — deliberately independent of the enum-symbol rows in
// monster_items_data.inc, so symbol/value drift in either artifact
// fails the full-corpus byte-equivalence test.
struct ExpectedMonsterItemsRecord {
    std::uint8_t rareSteal, commonSteal, rareDrop, commonDrop;
};
static_assert(sizeof(ExpectedMonsterItemsRecord) == 4,
              "fixture record must stay byte-identical to a ROM monster_items record");

// One fixture entry: the record's identity as a typed field (raw decimal
// index — the fixture stays independent of the port's MonsterId header)
// alongside the raw record bytes. Mirrors ostinato::MonsterItemsEntry
// without depending on it.
struct ExpectedMonsterItemsEntry {
    std::uint16_t id;
    ExpectedMonsterItemsRecord record;
};

inline constexpr std::array<ExpectedMonsterItemsEntry, 384> kExpectedMonsterItemsEntries = {{  // ROM MonsterItems
    { .id =   0,  // $000 GUARD
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =   1,  // $001 SOLDIER
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE9, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =   2,  // $002 TEMPLAR
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id =   3,  // $003 NINJA
      .record = { .rareSteal = 0xBC, .commonSteal = 0xFF, .rareDrop = 0x42, .commonDrop = 0xFF } },
    { .id =   4,  // $004 SAMURAI
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =   5,  // $005 OROG
      .record = { .rareSteal = 0xB3, .commonSteal = 0xFF, .rareDrop = 0xB3, .commonDrop = 0xF1 } },
    { .id =   6,  // $006 MAG_ROADER_1
      .record = { .rareSteal = 0x41, .commonSteal = 0xAD, .rareDrop = 0xAC, .commonDrop = 0xFF } },
    { .id =   7,  // $007 RETAINER
      .record = { .rareSteal = 0x30, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =   8,  // $008 HAZER
      .record = { .rareSteal = 0xE9, .commonSteal = 0xFF, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =   9,  // $009 DAHLING
      .record = { .rareSteal = 0x9F, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  10,  // $00A RAIN_MAN
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  11,  // $00B BRAWLER
      .record = { .rareSteal = 0x6E, .commonSteal = 0xFF, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =  12,  // $00C APOKRYPHOS
      .record = { .rareSteal = 0xBD, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  13,  // $00D DARK_FORCE
      .record = { .rareSteal = 0x14, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  14,  // $00E WHISPER
      .record = { .rareSteal = 0xE9, .commonSteal = 0xFF, .rareDrop = 0xF4, .commonDrop = 0xFF } },
    { .id =  15,  // $00F OVER_MIND
      .record = { .rareSteal = 0xE9, .commonSteal = 0xFF, .rareDrop = 0xF1, .commonDrop = 0xF8 } },
    { .id =  16,  // $010 OSTEOSAUR
      .record = { .rareSteal = 0xF5, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xF1 } },
    { .id =  17,  // $011 COMMANDER
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  18,  // $012 RHODOX
      .record = { .rareSteal = 0xE8, .commonSteal = 0xF2, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  19,  // $013 WERE_RAT
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =  20,  // $014 URSUS
      .record = { .rareSteal = 0xC7, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  21,  // $015 RHINOTAUR
      .record = { .rareSteal = 0x54, .commonSteal = 0xE8, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id =  22,  // $016 STEROIDITE
      .record = { .rareSteal = 0x62, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  23,  // $017 LEAFER
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =  24,  // $018 STRAY_CAT
      .record = { .rareSteal = 0xE9, .commonSteal = 0xFF, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =  25,  // $019 LOBO
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =  26,  // $01A DOBERMAN
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE8, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id =  27,  // $01B VOMAMMOTH
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE8, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id =  28,  // $01C FIDOR
      .record = { .rareSteal = 0xE9, .commonSteal = 0xF0, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  29,  // $01D BASKERVOR
      .record = { .rareSteal = 0x8D, .commonSteal = 0xFF, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id =  30,  // $01E SURIANDER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  31,  // $01F CHIMERA
      .record = { .rareSteal = 0xD2, .commonSteal = 0xFF, .rareDrop = 0x8F, .commonDrop = 0xFF } },
    { .id =  32,  // $020 BEHEMOTH
      .record = { .rareSteal = 0xBA, .commonSteal = 0xFF, .rareDrop = 0xEA, .commonDrop = 0xFF } },
    { .id =  33,  // $021 MESOSAUR
      .record = { .rareSteal = 0xFF, .commonSteal = 0xF2, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  34,  // $022 PTERODON
      .record = { .rareSteal = 0x02, .commonSteal = 0x01, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id =  35,  // $023 FOSSILFANG
      .record = { .rareSteal = 0xF5, .commonSteal = 0xF1, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  36,  // $024 WHITE_DRGN
      .record = { .rareSteal = 0x21, .commonSteal = 0xEA, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  37,  // $025 DOOM_DRGN
      .record = { .rareSteal = 0xC8, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  38,  // $026 BRACHOSAUR
      .record = { .rareSteal = 0xCA, .commonSteal = 0xFF, .rareDrop = 0xCE, .commonDrop = 0xFF } },
    { .id =  39,  // $027 TYRANOSAUR
      .record = { .rareSteal = 0x9B, .commonSteal = 0xFF, .rareDrop = 0x24, .commonDrop = 0xFF } },
    { .id =  40,  // $028 DARK_WIND
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  41,  // $029 BEAKOR
      .record = { .rareSteal = 0xE9, .commonSteal = 0xF3, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id =  42,  // $02A VULTURE
      .record = { .rareSteal = 0xF0, .commonSteal = 0xE9, .rareDrop = 0xF0, .commonDrop = 0xFF } },
    { .id =  43,  // $02B HARPY
      .record = { .rareSteal = 0xF0, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  44,  // $02C HERMITCRAB
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE9, .rareDrop = 0xFD, .commonDrop = 0xFF } },
    { .id =  45,  // $02D TRAPPER
      .record = { .rareSteal = 0xAA, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  46,  // $02E HORNET
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  47,  // $02F CRASSHOPPR
      .record = { .rareSteal = 0xF2, .commonSteal = 0xF2, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id =  48,  // $030 DELTA_BUG
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE8, .rareDrop = 0xF6, .commonDrop = 0xFF } },
    { .id =  49,  // $031 GILOMANTIS
      .record = { .rareSteal = 0x56, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  50,  // $032 TRILIUM
      .record = { .rareSteal = 0xF5, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  51,  // $033 NIGHTSHADE
      .record = { .rareSteal = 0xA0, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  52,  // $034 TUMBLEWEED
      .record = { .rareSteal = 0x83, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  53,  // $035 BLOOMPIRE
      .record = { .rareSteal = 0xFB, .commonSteal = 0xFF, .rareDrop = 0xFC, .commonDrop = 0xFF } },
    { .id =  54,  // $036 TRILOBITER
      .record = { .rareSteal = 0xE8, .commonSteal = 0xF2, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  55,  // $037 SIEGFRIED_1
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  56,  // $038 NAUTILOID
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE8, .rareDrop = 0xF3, .commonDrop = 0xFF } },
    { .id =  57,  // $039 EXOCITE
      .record = { .rareSteal = 0x54, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =  58,  // $03A ANGUIFORM
      .record = { .rareSteal = 0xE9, .commonSteal = 0xFF, .rareDrop = 0xF0, .commonDrop = 0xFF } },
    { .id =  59,  // $03B REACH_FROG
      .record = { .rareSteal = 0x43, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  60,  // $03C LIZARD
      .record = { .rareSteal = 0x12, .commonSteal = 0xFF, .rareDrop = 0xF4, .commonDrop = 0xFF } },
    { .id =  61,  // $03D CHICKENLIP
      .record = { .rareSteal = 0xF6, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  62,  // $03E HOOVER
      .record = { .rareSteal = 0xF5, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  63,  // $03F RIDER
      .record = { .rareSteal = 0xEE, .commonSteal = 0x89, .rareDrop = 0xF5, .commonDrop = 0xF5 } },
    { .id =  64,  // $040 CHUPON_COLOSSEUM
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  65,  // $041 PIPSQUEAK
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  66,  // $042 M_TEKARMOR
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xE9 } },
    { .id =  67,  // $043 SKY_ARMOR
      .record = { .rareSteal = 0xFF, .commonSteal = 0xEB, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  68,  // $044 TELSTAR
      .record = { .rareSteal = 0xEA, .commonSteal = 0xFF, .rareDrop = 0x72, .commonDrop = 0x72 } },
    { .id =  69,  // $045 LETHAL_WPN
      .record = { .rareSteal = 0xA7, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  70,  // $046 VAPORITE
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =  71,  // $047 FLAN
      .record = { .rareSteal = 0xF9, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  72,  // $048 ING
      .record = { .rareSteal = 0xB3, .commonSteal = 0xFF, .rareDrop = 0xF1, .commonDrop = 0xFF } },
    { .id =  73,  // $049 HUMPTY
      .record = { .rareSteal = 0xFF, .commonSteal = 0xF8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  74,  // $04A BRAINPAN
      .record = { .rareSteal = 0xC3, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  75,  // $04B CRULLER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  76,  // $04C CACTROT
      .record = { .rareSteal = 0xF4, .commonSteal = 0xFF, .rareDrop = 0xF4, .commonDrop = 0xFF } },
    { .id =  77,  // $04D REPO_MAN
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =  78,  // $04E HARVESTER
      .record = { .rareSteal = 0xBF, .commonSteal = 0xB0, .rareDrop = 0xB7, .commonDrop = 0xFF } },
    { .id =  79,  // $04F BOMB
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE8, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id =  80,  // $050 STILL_LIFE
      .record = { .rareSteal = 0xD7, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  81,  // $051 BOXED_SET
      .record = { .rareSteal = 0xF2, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  82,  // $052 SLAMDANCER
      .record = { .rareSteal = 0x04, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  83,  // $053 HADESGIGAS
      .record = { .rareSteal = 0xC4, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  84,  // $054 PUG
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xE5, .commonDrop = 0xFF } },
    { .id =  85,  // $055 MAGIC_URN
      .record = { .rareSteal = 0xEE, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  86,  // $056 MOVER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFA, .rareDrop = 0xF9, .commonDrop = 0xFF } },
    { .id =  87,  // $057 FIGALIZ
      .record = { .rareSteal = 0xE9, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  88,  // $058 BUFFALAX
      .record = { .rareSteal = 0x92, .commonSteal = 0xEB, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  89,  // $059 ASPIK
      .record = { .rareSteal = 0xE8, .commonSteal = 0xFF, .rareDrop = 0xEA, .commonDrop = 0xFF } },
    { .id =  90,  // $05A GHOST
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =  91,  // $05B CRAWLER
      .record = { .rareSteal = 0xF5, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  92,  // $05C SAND_RAY
      .record = { .rareSteal = 0xF2, .commonSteal = 0xF2, .rareDrop = 0xF2, .commonDrop = 0xFF } },
    { .id =  93,  // $05D ARENEID
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id =  94,  // $05E ACTANEON
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  95,  // $05F SAND_HORSE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  96,  // $060 DARK_SIDE
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id =  97,  // $061 MAD_OSCAR
      .record = { .rareSteal = 0xEA, .commonSteal = 0xFF, .rareDrop = 0xF5, .commonDrop = 0xF1 } },
    { .id =  98,  // $062 CRAWLY
      .record = { .rareSteal = 0xF5, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id =  99,  // $063 BLEARY
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id = 100,  // $064 MARSHAL
      .record = { .rareSteal = 0xFF, .commonSteal = 0x01, .rareDrop = 0xE9, .commonDrop = 0xE9 } },
    { .id = 101,  // $065 TROOPER
      .record = { .rareSteal = 0x0A, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 102,  // $066 GENERAL
      .record = { .rareSteal = 0x5C, .commonSteal = 0xE8, .rareDrop = 0xF8, .commonDrop = 0xFF } },
    { .id = 103,  // $067 COVERT
      .record = { .rareSteal = 0x43, .commonSteal = 0x41, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 104,  // $068 OGOR
      .record = { .rareSteal = 0x2F, .commonSteal = 0x2B, .rareDrop = 0xFF, .commonDrop = 0xF1 } },
    { .id = 105,  // $069 WARLOCK
      .record = { .rareSteal = 0xFD, .commonSteal = 0xFF, .rareDrop = 0xFD, .commonDrop = 0xFF } },
    { .id = 106,  // $06A MADAM
      .record = { .rareSteal = 0xB0, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 107,  // $06B JOKER
      .record = { .rareSteal = 0x72, .commonSteal = 0xE8, .rareDrop = 0x34, .commonDrop = 0xFF } },
    { .id = 108,  // $06C IRON_FIST
      .record = { .rareSteal = 0x73, .commonSteal = 0xE8, .rareDrop = 0x01, .commonDrop = 0xFF } },
    { .id = 109,  // $06D GOBLIN
      .record = { .rareSteal = 0xB8, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 110,  // $06E APPARITE
      .record = { .rareSteal = 0xE9, .commonSteal = 0xF1, .rareDrop = 0xF1, .commonDrop = 0xFF } },
    { .id = 111,  // $06F POWERDEMON
      .record = { .rareSteal = 0x92, .commonSteal = 0xE9, .rareDrop = 0xB3, .commonDrop = 0xF1 } },
    { .id = 112,  // $070 DISPLAYER
      .record = { .rareSteal = 0xFD, .commonSteal = 0xFF, .rareDrop = 0xFD, .commonDrop = 0xFF } },
    { .id = 113,  // $071 VECTOR_PUP
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 114,  // $072 PEEPERS
      .record = { .rareSteal = 0xEE, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 115,  // $073 SEWER_RAT
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 116,  // $074 SLATTER
      .record = { .rareSteal = 0xFD, .commonSteal = 0xFF, .rareDrop = 0xFD, .commonDrop = 0xFF } },
    { .id = 117,  // $075 RHINOX
      .record = { .rareSteal = 0xA5, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 118,  // $076 RHOBITE
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE9, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id = 119,  // $077 WILD_CAT
      .record = { .rareSteal = 0x9D, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 120,  // $078 RED_FANG
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xFE, .commonDrop = 0xFF } },
    { .id = 121,  // $079 BOUNTY_MAN
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 122,  // $07A TUSKER
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE8, .rareDrop = 0xF4, .commonDrop = 0xFF } },
    { .id = 123,  // $07B RALPH
      .record = { .rareSteal = 0x77, .commonSteal = 0xE8, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id = 124,  // $07C CHITONID
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE9, .rareDrop = 0xF5, .commonDrop = 0xFF } },
    { .id = 125,  // $07D WART_PUCK
      .record = { .rareSteal = 0xFE, .commonSteal = 0x44, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 126,  // $07E RHYOS
      .record = { .rareSteal = 0x22, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 127,  // $07F SRBEHEMOTH_UNDEAD
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xA1, .commonDrop = 0xA1 } },
    { .id = 128,  // $080 VECTAUR
      .record = { .rareSteal = 0x42, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 129,  // $081 WYVERN
      .record = { .rareSteal = 0xBF, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 130,  // $082 ZOMBONE
      .record = { .rareSteal = 0xE9, .commonSteal = 0xF0, .rareDrop = 0xF0, .commonDrop = 0xFF } },
    { .id = 131,  // $083 DRAGON
      .record = { .rareSteal = 0xD1, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 132,  // $084 BRONTAUR
      .record = { .rareSteal = 0xFE, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 133,  // $085 ALLOSAURUS
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 134,  // $086 CIRPIUS
      .record = { .rareSteal = 0xE8, .commonSteal = 0xF2, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 135,  // $087 SPRINTER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0x9B, .commonDrop = 0xFF } },
    { .id = 136,  // $088 GOBBLER
      .record = { .rareSteal = 0xE9, .commonSteal = 0xF8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 137,  // $089 HARPIAI
      .record = { .rareSteal = 0xF0, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 138,  // $08A GLOOMSHELL
      .record = { .rareSteal = 0xE9, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 139,  // $08B DROP
      .record = { .rareSteal = 0xFF, .commonSteal = 0xEB, .rareDrop = 0xEB, .commonDrop = 0xFF } },
    { .id = 140,  // $08C MIND_CANDY
      .record = { .rareSteal = 0xE8, .commonSteal = 0xF4, .rareDrop = 0xF4, .commonDrop = 0xFF } },
    { .id = 141,  // $08D WEEDFEEDER
      .record = { .rareSteal = 0xF2, .commonSteal = 0xF2, .rareDrop = 0xFB, .commonDrop = 0xFF } },
    { .id = 142,  // $08E LURIDAN
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 143,  // $08F TOE_CUTTER
      .record = { .rareSteal = 0xFF, .commonSteal = 0x38, .rareDrop = 0x38, .commonDrop = 0xFF } },
    { .id = 144,  // $090 OVER_GRUNK
      .record = { .rareSteal = 0xF5, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 145,  // $091 EXORAY
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xF1 } },
    { .id = 146,  // $092 CRUSHER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFA, .rareDrop = 0xFA, .commonDrop = 0xFF } },
    { .id = 147,  // $093 UROBUROS
      .record = { .rareSteal = 0xF0, .commonSteal = 0xFF, .rareDrop = 0xF0, .commonDrop = 0xFF } },
    { .id = 148,  // $094 PRIMORDITE
      .record = { .rareSteal = 0xE8, .commonSteal = 0xF3, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 149,  // $095 SKY_CAP
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 150,  // $096 CEPHALER
      .record = { .rareSteal = 0xF5, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 151,  // $097 MALIGA
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 152,  // $098 GIGAN_TOAD
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xF6, .commonDrop = 0xFF } },
    { .id = 153,  // $099 GECKOREX
      .record = { .rareSteal = 0x65, .commonSteal = 0xFF, .rareDrop = 0x65, .commonDrop = 0xFF } },
    { .id = 154,  // $09A CLUCK
      .record = { .rareSteal = 0xFD, .commonSteal = 0xFF, .rareDrop = 0xFD, .commonDrop = 0xFF } },
    { .id = 155,  // $09B LAND_WORM
      .record = { .rareSteal = 0xEA, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 156,  // $09C TEST_RIDER
      .record = { .rareSteal = 0x20, .commonSteal = 0xFF, .rareDrop = 0x1F, .commonDrop = 0xFF } },
    { .id = 157,  // $09D PLUTOARMOR
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 158,  // $09E TOMB_THUMB
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xF8, .commonDrop = 0xFF } },
    { .id = 159,  // $09F HEAVYARMOR
      .record = { .rareSteal = 0x6F, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 160,  // $0A0 CHASER
      .record = { .rareSteal = 0xA4, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 161,  // $0A1 SCULLION
      .record = { .rareSteal = 0xA9, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 162,  // $0A2 POPLIUM
      .record = { .rareSteal = 0xE9, .commonSteal = 0xFF, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id = 163,  // $0A3 INTANGIR
      .record = { .rareSteal = 0xF9, .commonSteal = 0xFF, .rareDrop = 0xF2, .commonDrop = 0xFF } },
    { .id = 164,  // $0A4 MISFIT
      .record = { .rareSteal = 0xE1, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 165,  // $0A5 ELAND
      .record = { .rareSteal = 0xFD, .commonSteal = 0xFF, .rareDrop = 0xFD, .commonDrop = 0xFF } },
    { .id = 166,  // $0A6 ENUO
      .record = { .rareSteal = 0xEA, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 167,  // $0A7 DEEP_EYE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xF3, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 168,  // $0A8 GREASEMONK
      .record = { .rareSteal = 0x5A, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 169,  // $0A9 NECKHUNTER
      .record = { .rareSteal = 0x7D, .commonSteal = 0xFF, .rareDrop = 0xB2, .commonDrop = 0xFF } },
    { .id = 170,  // $0AA GRENADE
      .record = { .rareSteal = 0xAB, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 171,  // $0AB CRITIC
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 172,  // $0AC PAN_DORA
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 173,  // $0AD SOULDANCER
      .record = { .rareSteal = 0x9F, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 174,  // $0AE GIGANTOS
      .record = { .rareSteal = 0xEE, .commonSteal = 0xEA, .rareDrop = 0x28, .commonDrop = 0x28 } },
    { .id = 175,  // $0AF MAG_ROADER_2
      .record = { .rareSteal = 0x41, .commonSteal = 0xAD, .rareDrop = 0xAB, .commonDrop = 0xFF } },
    { .id = 176,  // $0B0 SPEK_TOR
      .record = { .rareSteal = 0xEA, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 177,  // $0B1 PARASITE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 178,  // $0B2 EARTHGUARD
      .record = { .rareSteal = 0xEF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 179,  // $0B3 COELECITE
      .record = { .rareSteal = 0xE9, .commonSteal = 0xF2, .rareDrop = 0xF2, .commonDrop = 0xFF } },
    { .id = 180,  // $0B4 ANEMONE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xF8 } },
    { .id = 181,  // $0B5 HIPOCAMPUS
      .record = { .rareSteal = 0xFD, .commonSteal = 0xFF, .rareDrop = 0xFD, .commonDrop = 0xFF } },
    { .id = 182,  // $0B6 SPECTRE
      .record = { .rareSteal = 0x36, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id = 183,  // $0B7 EVIL_OSCAR
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFD, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 184,  // $0B8 SLURM
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 185,  // $0B9 LATIMERIA
      .record = { .rareSteal = 0xFF, .commonSteal = 0x8D, .rareDrop = 0xF2, .commonDrop = 0xFF } },
    { .id = 186,  // $0BA STILLGOING
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id = 187,  // $0BB ALLO_VER
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE8, .rareDrop = 0x59, .commonDrop = 0x59 } },
    { .id = 188,  // $0BC PHASE
      .record = { .rareSteal = 0xF0, .commonSteal = 0xFF, .rareDrop = 0xF0, .commonDrop = 0xFF } },
    { .id = 189,  // $0BD OUTSIDER
      .record = { .rareSteal = 0x11, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 190,  // $0BE BARB_E
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 191,  // $0BF PARASOUL
      .record = { .rareSteal = 0xF0, .commonSteal = 0xFF, .rareDrop = 0xF0, .commonDrop = 0xFF } },
    { .id = 192,  // $0C0 PM_STALKER
      .record = { .rareSteal = 0xEA, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 193,  // $0C1 HEMOPHYTE
      .record = { .rareSteal = 0x43, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 194,  // $0C2 SP_FORCES
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE8, .rareDrop = 0xF9, .commonDrop = 0xFF } },
    { .id = 195,  // $0C3 NOHRABBIT
      .record = { .rareSteal = 0xFF, .commonSteal = 0xF5, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id = 196,  // $0C4 WIZARD
      .record = { .rareSteal = 0x36, .commonSteal = 0x37, .rareDrop = 0x35, .commonDrop = 0xFF } },
    { .id = 197,  // $0C5 SCRAPPER
      .record = { .rareSteal = 0xCF, .commonSteal = 0xFF, .rareDrop = 0x03, .commonDrop = 0xFF } },
    { .id = 198,  // $0C6 CERITOPS
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xB4, .commonDrop = 0xF8 } },
    { .id = 199,  // $0C7 COMMANDO
      .record = { .rareSteal = 0x89, .commonSteal = 0xF7, .rareDrop = 0xF7, .commonDrop = 0xFF } },
    { .id = 200,  // $0C8 OPINICUS
      .record = { .rareSteal = 0xFD, .commonSteal = 0xFF, .rareDrop = 0xFD, .commonDrop = 0xFF } },
    { .id = 201,  // $0C9 POPPERS
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xF8, .commonDrop = 0xFF } },
    { .id = 202,  // $0CA LUNARIS
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 203,  // $0CB GARM
      .record = { .rareSteal = 0xF0, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 204,  // $0CC VINDR
      .record = { .rareSteal = 0x9E, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 205,  // $0CD KIWOK
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xB4, .commonDrop = 0xF8 } },
    { .id = 206,  // $0CE NASTIDON
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE8, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id = 207,  // $0CF RINN
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 208,  // $0D0 INSECARE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFB, .rareDrop = 0xFC, .commonDrop = 0xFF } },
    { .id = 209,  // $0D1 VERMIN
      .record = { .rareSteal = 0xF2, .commonSteal = 0xE9, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id = 210,  // $0D2 MANTODEA
      .record = { .rareSteal = 0x24, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 211,  // $0D3 BOGY
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 212,  // $0D4 PRUSSIAN
      .record = { .rareSteal = 0x45, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 213,  // $0D5 BLACK_DRGN
      .record = { .rareSteal = 0xFF, .commonSteal = 0xF1, .rareDrop = 0xF7, .commonDrop = 0xFF } },
    { .id = 214,  // $0D6 ADAMANCHYT
      .record = { .rareSteal = 0x5D, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 215,  // $0D7 DANTE
      .record = { .rareSteal = 0x7C, .commonSteal = 0xFF, .rareDrop = 0x5D, .commonDrop = 0xFF } },
    { .id = 216,  // $0D8 WIREY_DRGN
      .record = { .rareSteal = 0xBF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 217,  // $0D9 DUELLER
      .record = { .rareSteal = 0xA6, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 218,  // $0DA PSYCHOT
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id = 219,  // $0DB MUUS
      .record = { .rareSteal = 0xF9, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 220,  // $0DC KARKASS
      .record = { .rareSteal = 0x16, .commonSteal = 0x0A, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 221,  // $0DD PUNISHER
      .record = { .rareSteal = 0x4A, .commonSteal = 0x48, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 222,  // $0DE BALLOON
      .record = { .rareSteal = 0xF0, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 223,  // $0DF GABBLDEGAK
      .record = { .rareSteal = 0xF0, .commonSteal = 0xF3, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 224,  // $0E0 GTBEHEMOTH
      .record = { .rareSteal = 0x59, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 225,  // $0E1 SCORPION
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id = 226,  // $0E2 CHAOS_DRGN
      .record = { .rareSteal = 0xF0, .commonSteal = 0xFF, .rareDrop = 0xF0, .commonDrop = 0xFF } },
    { .id = 227,  // $0E3 SPIT_FIRE
      .record = { .rareSteal = 0xEE, .commonSteal = 0xEB, .rareDrop = 0xEB, .commonDrop = 0xFF } },
    { .id = 228,  // $0E4 VECTAGOYLE
      .record = { .rareSteal = 0x07, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 229,  // $0E5 LICH
      .record = { .rareSteal = 0x38, .commonSteal = 0xF8, .rareDrop = 0xF8, .commonDrop = 0xFF } },
    { .id = 230,  // $0E6 OSPREY
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFB, .commonDrop = 0xFF } },
    { .id = 231,  // $0E7 MAG_ROADER_3
      .record = { .rareSteal = 0x41, .commonSteal = 0xAD, .rareDrop = 0xAC, .commonDrop = 0xFF } },
    { .id = 232,  // $0E8 BUG
      .record = { .rareSteal = 0xE9, .commonSteal = 0xF4, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 233,  // $0E9 SEA_FLOWER
      .record = { .rareSteal = 0xF0, .commonSteal = 0xFF, .rareDrop = 0xF0, .commonDrop = 0xFF } },
    { .id = 234,  // $0EA FORTIS
      .record = { .rareSteal = 0xA8, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 235,  // $0EB ABOLISHER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xF2, .rareDrop = 0xF0, .commonDrop = 0xFF } },
    { .id = 236,  // $0EC AQUILA
      .record = { .rareSteal = 0xCE, .commonSteal = 0xF0, .rareDrop = 0xF0, .commonDrop = 0xFF } },
    { .id = 237,  // $0ED JUNK
      .record = { .rareSteal = 0xA3, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 238,  // $0EE MANDRAKE
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE9, .rareDrop = 0xF5, .commonDrop = 0xFF } },
    { .id = 239,  // $0EF FIRST_CLASS
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 240,  // $0F0 TAP_DANCER
      .record = { .rareSteal = 0x07, .commonSteal = 0x00, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 241,  // $0F1 NECROMANCR
      .record = { .rareSteal = 0xF0, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xF1 } },
    { .id = 242,  // $0F2 BORRAS
      .record = { .rareSteal = 0xCB, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 243,  // $0F3 MAG_ROADER_4
      .record = { .rareSteal = 0x41, .commonSteal = 0xAD, .rareDrop = 0xAB, .commonDrop = 0xFF } },
    { .id = 244,  // $0F4 WILD_RAT
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 245,  // $0F5 GOLD_BEAR
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE8, .rareDrop = 0xE9, .commonDrop = 0xFF } },
    { .id = 246,  // $0F6 INNOC
      .record = { .rareSteal = 0xA4, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 247,  // $0F7 TRIXTER
      .record = { .rareSteal = 0xF0, .commonSteal = 0xFF, .rareDrop = 0xF0, .commonDrop = 0xFF } },
    { .id = 248,  // $0F8 RED_WOLF
      .record = { .rareSteal = 0xE8, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id = 249,  // $0F9 DIDALOS
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 250,  // $0FA WOOLLY
      .record = { .rareSteal = 0x28, .commonSteal = 0x25, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 251,  // $0FB VETERAN
      .record = { .rareSteal = 0xC3, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 252,  // $0FC SKY_BASE
      .record = { .rareSteal = 0xA5, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 253,  // $0FD IRONHITMAN
      .record = { .rareSteal = 0xAA, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 254,  // $0FE IO
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 255,  // $0FF PUGS
      .record = { .rareSteal = 0x9C, .commonSteal = 0xFF, .rareDrop = 0x9C, .commonDrop = 0xFF } },
    { .id = 256,  // $100 WHELK
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xEB, .commonDrop = 0xEB } },
    { .id = 257,  // $101 PRESENTER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0x58, .commonDrop = 0x58 } },
    { .id = 258,  // $102 MEGA_ARMOR
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 259,  // $103 VARGAS
      .record = { .rareSteal = 0x54, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 260,  // $104 TUNNELARMR
      .record = { .rareSteal = 0xA4, .commonSteal = 0x03, .rareDrop = 0xEE, .commonDrop = 0xEE } },
    { .id = 261,  // $105 PROMETHEUS
      .record = { .rareSteal = 0xA7, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 262,  // $106 GHOSTTRAIN
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xF7, .commonDrop = 0xF7 } },
    { .id = 263,  // $107 DADALUMA
      .record = { .rareSteal = 0xC7, .commonSteal = 0xB5, .rareDrop = 0x04, .commonDrop = 0x73 } },
    { .id = 264,  // $108 SHIVA
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 265,  // $109 IFRIT
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 266,  // $10A NUMBER_024
      .record = { .rareSteal = 0x12, .commonSteal = 0x0C, .rareDrop = 0x0D, .commonDrop = 0x0E } },
    { .id = 267,  // $10B NUMBER_128
      .record = { .rareSteal = 0x2E, .commonSteal = 0xFF, .rareDrop = 0xF7, .commonDrop = 0xF7 } },
    { .id = 268,  // $10C INFERNO
      .record = { .rareSteal = 0x61, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 269,  // $10D CRANE_1
      .record = { .rareSteal = 0xA3, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 270,  // $10E CRANE_2
      .record = { .rareSteal = 0xA7, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 271,  // $10F UMARO_1
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 272,  // $110 UMARO_2
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 273,  // $111 GUARDIAN_VECTOR
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 274,  // $112 GUARDIAN_BOSS
      .record = { .rareSteal = 0xCA, .commonSteal = 0x94, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 275,  // $113 AIR_FORCE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xEE, .rareDrop = 0xC1, .commonDrop = 0xC1 } },
    { .id = 276,  // $114 TRITOCH_INTRO
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 277,  // $115 TRITOCH_MORPH
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 278,  // $116 FLAMEEATER
      .record = { .rareSteal = 0xFF, .commonSteal = 0x0D, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 279,  // $117 ATMAWEAPON
      .record = { .rareSteal = 0xCA, .commonSteal = 0xEE, .rareDrop = 0xEE, .commonDrop = 0xEE } },
    { .id = 280,  // $118 NERAPA
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 281,  // $119 SRBEHEMOTH
      .record = { .rareSteal = 0x2F, .commonSteal = 0xFF, .rareDrop = 0xA1, .commonDrop = 0xA1 } },
    { .id = 282,  // $11A KEFKA_1
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 283,  // $11B TENTACLE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 284,  // $11C DULLAHAN
      .record = { .rareSteal = 0xD1, .commonSteal = 0xEA, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 285,  // $11D DOOM_GAZE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 286,  // $11E CHADARNOOK_1
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 287,  // $11F CURLEY
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 288,  // $120 LARRY
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 289,  // $121 MOE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 290,  // $122 WREXSOUL
      .record = { .rareSteal = 0xDB, .commonSteal = 0xFF, .rareDrop = 0xC8, .commonDrop = 0xC8 } },
    { .id = 291,  // $123 HIDON
      .record = { .rareSteal = 0x82, .commonSteal = 0xFD, .rareDrop = 0xFD, .commonDrop = 0xFD } },
    { .id = 292,  // $124 KATANASOUL
      .record = { .rareSteal = 0x31, .commonSteal = 0x2F, .rareDrop = 0xD3, .commonDrop = 0xD3 } },
    { .id = 293,  // $125 L30_MAGIC
      .record = { .rareSteal = 0xEB, .commonSteal = 0xFF, .rareDrop = 0xEB, .commonDrop = 0xFF } },
    { .id = 294,  // $126 HIDONITE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 295,  // $127 DOOM
      .record = { .rareSteal = 0xDC, .commonSteal = 0xFF, .rareDrop = 0x32, .commonDrop = 0x32 } },
    { .id = 296,  // $128 GODDESS
      .record = { .rareSteal = 0x9C, .commonSteal = 0xFF, .rareDrop = 0x18, .commonDrop = 0x18 } },
    { .id = 297,  // $129 POLTRGEIST
      .record = { .rareSteal = 0x93, .commonSteal = 0xFF, .rareDrop = 0x23, .commonDrop = 0x23 } },
    { .id = 298,  // $12A FINAL_KEFKA
      .record = { .rareSteal = 0xFF, .commonSteal = 0xEF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 299,  // $12B L40_MAGIC
      .record = { .rareSteal = 0xEB, .commonSteal = 0xFF, .rareDrop = 0xEB, .commonDrop = 0xFF } },
    { .id = 300,  // $12C ULTROS_RIVER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 301,  // $12D ULTROS_OPERA
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 302,  // $12E ULTROS_MOUNTAIN
      .record = { .rareSteal = 0xFF, .commonSteal = 0xB4, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 303,  // $12F CHUPON_AIRSHIP
      .record = { .rareSteal = 0xFF, .commonSteal = 0x00, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 304,  // $130 L20_MAGIC
      .record = { .rareSteal = 0xEB, .commonSteal = 0xFF, .rareDrop = 0xEB, .commonDrop = 0xFF } },
    { .id = 305,  // $131 SIEGFRIED_2
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xF8, .commonDrop = 0xF8 } },
    { .id = 306,  // $132 L10_MAGIC
      .record = { .rareSteal = 0xEB, .commonSteal = 0xFF, .rareDrop = 0xEB, .commonDrop = 0xFF } },
    { .id = 307,  // $133 L50_MAGIC
      .record = { .rareSteal = 0xEC, .commonSteal = 0xFF, .rareDrop = 0xEB, .commonDrop = 0xFF } },
    { .id = 308,  // $134 HEAD
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xE9, .commonDrop = 0xE9 } },
    { .id = 309,  // $135 WHELK_HEAD
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0x58, .commonDrop = 0x58 } },
    { .id = 310,  // $136 COLOSSUS
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0x6E, .commonDrop = 0x6E } },
    { .id = 311,  // $137 CZARDRAGON
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 312,  // $138 MASTER_PUG
      .record = { .rareSteal = 0xEF, .commonSteal = 0xEE, .rareDrop = 0x08, .commonDrop = 0x08 } },
    { .id = 313,  // $139 L60_MAGIC
      .record = { .rareSteal = 0xEC, .commonSteal = 0xFF, .rareDrop = 0xEB, .commonDrop = 0xFF } },
    { .id = 314,  // $13A MERCHANT
      .record = { .rareSteal = 0x02, .commonSteal = 0x6B, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 315,  // $13B B_DAY_SUIT
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 316,  // $13C TENTACLE_1
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 317,  // $13D TENTACLE_2
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 318,  // $13E TENTACLE_3
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 319,  // $13F RIGHTBLADE
      .record = { .rareSteal = 0xEB, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xF0 } },
    { .id = 320,  // $140 LEFT_BLADE
      .record = { .rareSteal = 0xEB, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xF0 } },
    { .id = 321,  // $141 ROUGH
      .record = { .rareSteal = 0x60, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 322,  // $142 STRIKER
      .record = { .rareSteal = 0x60, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 323,  // $143 L70_MAGIC
      .record = { .rareSteal = 0xEC, .commonSteal = 0xFF, .rareDrop = 0xEB, .commonDrop = 0xFF } },
    { .id = 324,  // $144 TRITOCH_BOSS
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 325,  // $145 LASER_GUN
      .record = { .rareSteal = 0xFF, .commonSteal = 0xED, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 326,  // $146 SPECK
      .record = { .rareSteal = 0xB3, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 327,  // $147 MISSILEBAY
      .record = { .rareSteal = 0xA7, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 328,  // $148 CHADARNOOK_2
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 329,  // $149 ICE_DRAGON
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0x68, .commonDrop = 0x68 } },
    { .id = 330,  // $14A KEFKA_NARSHE
      .record = { .rareSteal = 0xEE, .commonSteal = 0xEC, .rareDrop = 0xB2, .commonDrop = 0xB2 } },
    { .id = 331,  // $14B STORM_DRGN
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0x94, .commonDrop = 0x94 } },
    { .id = 332,  // $14C DIRT_DRGN
      .record = { .rareSteal = 0xEA, .commonSteal = 0xFF, .rareDrop = 0x3C, .commonDrop = 0x3C } },
    { .id = 333,  // $14D IPOOH
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE9, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 334,  // $14E LEADER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xF0, .commonDrop = 0xD5 } },
    { .id = 335,  // $14F GRUNT
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id = 336,  // $150 GOLD_DRGN
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xCC, .commonDrop = 0xCC } },
    { .id = 337,  // $151 SKULL_DRGN
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xCB, .commonDrop = 0xCB } },
    { .id = 338,  // $152 BLUE_DRGN
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0x19, .commonDrop = 0x19 } },
    { .id = 339,  // $153 RED_DRAGON
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0x31, .commonDrop = 0x31 } },
    { .id = 340,  // $154 PIRANHA
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id = 341,  // $155 RIZOPAS
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xF5, .commonDrop = 0xF5 } },
    { .id = 342,  // $156 SPECTER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xD2, .commonDrop = 0xD2 } },
    { .id = 343,  // $157 SHORT_ARM
      .record = { .rareSteal = 0xFF, .commonSteal = 0xEE, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 344,  // $158 LONG_ARM
      .record = { .rareSteal = 0xFF, .commonSteal = 0xEE, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 345,  // $159 FACE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xEE, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 346,  // $15A TIGER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xEE, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 347,  // $15B TOOLS
      .record = { .rareSteal = 0xFF, .commonSteal = 0xEE, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 348,  // $15C MAGIC
      .record = { .rareSteal = 0xFF, .commonSteal = 0xEE, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 349,  // $15D HIT
      .record = { .rareSteal = 0xFF, .commonSteal = 0xEE, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 350,  // $15E GIRL
      .record = { .rareSteal = 0xFF, .commonSteal = 0x1B, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 351,  // $15F SLEEP
      .record = { .rareSteal = 0xFF, .commonSteal = 0x1C, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 352,  // $160 HIDONITE_1
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 353,  // $161 HIDONITE_2
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 354,  // $162 HIDONITE_3
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 355,  // $163 L80_MAGIC
      .record = { .rareSteal = 0xEC, .commonSteal = 0xFF, .rareDrop = 0xEB, .commonDrop = 0xFF } },
    { .id = 356,  // $164 L90_MAGIC
      .record = { .rareSteal = 0xEC, .commonSteal = 0xFF, .rareDrop = 0xEB, .commonDrop = 0xFF } },
    { .id = 357,  // $165 PROTOARMOR
      .record = { .rareSteal = 0x8C, .commonSteal = 0xE9, .rareDrop = 0xA4, .commonDrop = 0xFF } },
    { .id = 358,  // $166 MAGIMASTER
      .record = { .rareSteal = 0xCC, .commonSteal = 0xEE, .rareDrop = 0xEF, .commonDrop = 0xEF } },
    { .id = 359,  // $167 SOULSAVER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 360,  // $168 ULTROS_AIRSHIP
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFE, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 361,  // $169 NAUGHTY
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 362,  // $16A PHUNBABA_1
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 363,  // $16B PHUNBABA_2
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 364,  // $16C PHUNBABA_3
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 365,  // $16D PHUNBABA_4
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 366,  // $16E TERRA_FLASHBACK
      .record = { .rareSteal = 0xB1, .commonSteal = 0xF0, .rareDrop = 0xF5, .commonDrop = 0xFF } },
    { .id = 367,  // $16F KEFKA_IMP_CAMP
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 368,  // $170 CYAN_IMP_CAMP
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 369,  // $171 ZONE_EATER
      .record = { .rareSteal = 0xFD, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 370,  // $172 GAU_VELDT
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 371,  // $173 KEFKA_VS_LEO
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 372,  // $174 KEFKA_ESPER_GATE
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 373,  // $175 OFFICER
      .record = { .rareSteal = 0xE9, .commonSteal = 0xE8, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 374,  // $176 CADET
      .record = { .rareSteal = 0xFF, .commonSteal = 0xE8, .rareDrop = 0xE8, .commonDrop = 0xFF } },
    { .id = 375,  // $177 MONSTER_0177
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 376,  // $178 MONSTER_0178
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 377,  // $179 SOLDIER_FLASHBACK
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 378,  // $17A KEFKA_VS_ESPER
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 379,  // $17B EVENT
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 380,  // $17C MONSTER_017C
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 381,  // $17D ATMA
      .record = { .rareSteal = 0xCC, .commonSteal = 0x12, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 382,  // $17E SHADOW_COLOSSEUM
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
    { .id = 383,  // $17F COLOSSEUM
      .record = { .rareSteal = 0xFF, .commonSteal = 0xFF, .rareDrop = 0xFF, .commonDrop = 0xFF } },
}};

}  // namespace ostinato::test
