// AUTO-GENERATED by tools/asm_parser/parse_natural_magic.py
// Source: src/field/event.asm (NaturalMagic, ROM EC/E3C0,
//         Terra's 16 {spell, level} pairs then Celes's 16, contiguous)
// Source: include/const.inc (ATTACK values)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_natural_magic.py \
//       --source-root  original-src \
//       --inc-out      src/data/generated/natural_magic_data.inc \
//       --fixture-out  tests/fixtures/natural_magic_expected.h

// Test fixture for tests/test_natural_magic.cpp — the ground-truth
// record bytes. The full-corpus test asserts, per entry of both
// halves: fixture slot == position, table slot == position, and a
// 2-byte memcmp of the packed record against
// src/data/generated/natural_magic_data.inc's row.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 2-byte natural-magic pair in ROM order: the ATTACK byte then
// the learn level. Values are the exact ROM bytes with every upstream
// symbol resolved — deliberately independent of the enum-symbol rows in
// natural_magic_data.inc, so symbol/value drift in either artifact
// fails the full-corpus byte-equivalence test.
struct ExpectedNaturalMagicRecord {
    std::uint8_t spell;   // ATTACK byte
    std::uint8_t level;
};
static_assert(sizeof(ExpectedNaturalMagicRecord) == 2,
              "fixture record must stay byte-identical to a ROM natural-magic pair");

// One fixture entry: the pair's identity as a typed field (its decimal
// slot within the character's half) alongside the raw record bytes.
// Mirrors ostinato::NaturalMagicSlot without depending on it.
struct ExpectedNaturalMagicSlot {
    std::uint8_t slot;
    ExpectedNaturalMagicRecord record;
};

inline constexpr std::array<ExpectedNaturalMagicSlot, 16> kExpectedNaturalMagicTerra = {{
    { .slot =  0, .record = { .spell = 0x2D, .level = 0x01 } },  // CURE
    { .slot =  1, .record = { .spell = 0x00, .level = 0x03 } },  // FIRE
    { .slot =  2, .record = { .spell = 0x32, .level = 0x06 } },  // ANTDOT
    { .slot =  3, .record = { .spell = 0x04, .level = 0x0C } },  // DRAIN
    { .slot =  4, .record = { .spell = 0x30, .level = 0x12 } },  // LIFE
    { .slot =  5, .record = { .spell = 0x05, .level = 0x16 } },  // FIRE_2
    { .slot =  6, .record = { .spell = 0x2A, .level = 0x1A } },  // WARP
    { .slot =  7, .record = { .spell = 0x2E, .level = 0x21 } },  // CURE_2
    { .slot =  8, .record = { .spell = 0x2C, .level = 0x25 } },  // DISPEL
    { .slot =  9, .record = { .spell = 0x09, .level = 0x2B } },  // FIRE_3
    { .slot = 10, .record = { .spell = 0x31, .level = 0x31 } },  // LIFE_2
    { .slot = 11, .record = { .spell = 0x0E, .level = 0x39 } },  // PEARL
    { .slot = 12, .record = { .spell = 0x0C, .level = 0x44 } },  // BREAK
    { .slot = 13, .record = { .spell = 0x11, .level = 0x4B } },  // QUARTR
    { .slot = 14, .record = { .spell = 0x17, .level = 0x56 } },  // MERTON
    { .slot = 15, .record = { .spell = 0x14, .level = 0x63 } },  // ULTIMA
}};

inline constexpr std::array<ExpectedNaturalMagicSlot, 16> kExpectedNaturalMagicCeles = {{
    { .slot =  0, .record = { .spell = 0x01, .level = 0x01 } },  // ICE
    { .slot =  1, .record = { .spell = 0x2D, .level = 0x04 } },  // CURE
    { .slot =  2, .record = { .spell = 0x32, .level = 0x08 } },  // ANTDOT
    { .slot =  3, .record = { .spell = 0x23, .level = 0x0D } },  // IMP
    { .slot =  4, .record = { .spell = 0x18, .level = 0x12 } },  // SCAN
    { .slot =  5, .record = { .spell = 0x1C, .level = 0x16 } },  // SAFE
    { .slot =  6, .record = { .spell = 0x06, .level = 0x1A } },  // ICE_2
    { .slot =  7, .record = { .spell = 0x1F, .level = 0x20 } },  // HASTE
    { .slot =  8, .record = { .spell = 0x21, .level = 0x28 } },  // BSERK
    { .slot =  9, .record = { .spell = 0x1E, .level = 0x20 } },  // MUDDLE
    { .slot = 10, .record = { .spell = 0x0A, .level = 0x2A } },  // ICE_3
    { .slot = 11, .record = { .spell = 0x26, .level = 0x30 } },  // VANISH
    { .slot = 12, .record = { .spell = 0x27, .level = 0x34 } },  // HASTE2
    { .slot = 13, .record = { .spell = 0x0E, .level = 0x48 } },  // PEARL
    { .slot = 14, .record = { .spell = 0x0F, .level = 0x51 } },  // FLARE
    { .slot = 15, .record = { .spell = 0x13, .level = 0x62 } },  // METEOR
}};

}  // namespace ostinato::test
