// AUTO-GENERATED by tools/asm_parser/parse_rom_regions.py
// Source: tools/extract_assets.py:323-331 (the CRC32 branches)
// Source: cfg/ff6-en.cfg (the ROM bank extent)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_rom_regions.py \
//       --source-root original-src --repo-root .

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace ostinato::test {

// One accepted revision: the GameVersion enumerator as its decimal
// value, and the CRC32 of that revision's headerless image.
struct ExpectedRomIdentity {
    std::uint8_t  version;
    std::uint32_t crc32;
};

inline constexpr std::size_t kExpectedRomSizeBytes = 3145728;
inline constexpr std::size_t kExpectedCopierHeaderBytes = 512;

inline constexpr std::array<ExpectedRomIdentity, 3>
kExpectedRomIdentities = {{
    { .version = 0, .crc32 = 0x45EF5AC8 },
    { .version = 1, .crc32 = 0xA27F1C7A },
    { .version = 2, .crc32 = 0xC0FA0464 },
}};

}  // namespace ostinato::test
