// AUTO-GENERATED by tools/asm_parser/parse_shop_prop.py
// Source: src/menu/shop_prop.dat (ShopProp, ROM C4/7AC0,
//         128 records x 9 bytes; layout per the consumer access sites
//         cited in src/data/shop_properties.h)
// Source: include/const.inc (ITEM values)
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_shop_prop.py \
//       --source-root  original-src \
//       --inc-out      src/data/generated/shop_prop_data.inc \
//       --fixture-out  tests/fixtures/shop_prop_expected.h

// Test fixture for tests/test_shop_properties.cpp — the
// ground-truth record bytes. The full-corpus test asserts, per
// entry: fixture shopIndex == position, table shopIndex ==
// position, and a 9-byte memcmp of the packed record against
// src/data/generated/shop_prop_data.inc's row.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// One raw 9-byte shop_prop record; field names mirror the
// src/data/shop_properties.h record layout (the eight item slots appear
// as their individual bytes). Values are the exact ROM bytes —
// deliberately independent of the typed-surface rows in
// shop_prop_data.inc, so decomposition/builder drift in either artifact
// fails the full-corpus byte-equivalence test.
struct ExpectedShopRecord {
    std::uint8_t config;
    std::uint8_t item0, item1, item2, item3, item4, item5, item6, item7;
};
static_assert(sizeof(ExpectedShopRecord) == 9,
              "fixture record must stay byte-identical to a ROM shop_prop record");

// One fixture entry: the record's identity as a typed field (the decimal
// shop index) alongside the raw record bytes. Mirrors
// ostinato::ShopEntry without depending on it.
struct ExpectedShopEntry {
    std::uint8_t shopIndex;
    ExpectedShopRecord record;
};

inline constexpr std::array<ExpectedShopEntry, 128> kExpectedShopEntries = {{  // ROM ShopProp
    { .shopIndex =   0,  // [$00]
      .record = { .config = 0x01, .item0 = 0x0B, .item1 = 0x54,
                  .item2 = 0x2C, .item3 = 0x1D, .item4 = 0x03,
                  .item5 = 0x44, .item6 = 0x45, .item7 = 0xFF } },
    { .shopIndex =   1,  // [$01]
      .record = { .config = 0x02, .item0 = 0x5C, .item1 = 0x6D,
                  .item2 = 0x6E, .item3 = 0x6F, .item4 = 0x88,
                  .item5 = 0x87, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =   2,  // [$02]
      .record = { .config = 0x04, .item0 = 0xE6, .item1 = 0xB5,
                  .item2 = 0xB6, .item3 = 0xB7, .item4 = 0xB8,
                  .item5 = 0xBE, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =   3,  // [$03]
      .record = { .config = 0x03, .item0 = 0xE8, .item1 = 0xE9,
                  .item2 = 0xEB, .item3 = 0xF4, .item4 = 0xF0,
                  .item5 = 0xFC, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =   4,  // [$04]
      .record = { .config = 0x33, .item0 = 0xE8, .item1 = 0xEB,
                  .item2 = 0xF2, .item3 = 0xF4, .item4 = 0xFB,
                  .item5 = 0xF0, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =   5,  // [$05]
      .record = { .config = 0x01, .item0 = 0x00, .item1 = 0x01,
                  .item2 = 0x0A, .item3 = 0x0B, .item4 = 0xA3,
                  .item5 = 0xA4, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =   6,  // [$06]
      .record = { .config = 0x02, .item0 = 0x5A, .item1 = 0x5B,
                  .item2 = 0x6A, .item3 = 0x6B, .item4 = 0x85,
                  .item5 = 0x86, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =   7,  // [$07]
      .record = { .config = 0x04, .item0 = 0xE6, .item1 = 0xB0,
                  .item2 = 0xB1, .item3 = 0xB5, .item4 = 0xBE,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =   8,  // [$08]
      .record = { .config = 0x03, .item0 = 0xE8, .item1 = 0xF2,
                  .item2 = 0xF4, .item3 = 0xF3, .item4 = 0xFB,
                  .item5 = 0xF0, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =   9,  // [$09]
      .record = { .config = 0x01, .item0 = 0x01, .item1 = 0x0A,
                  .item2 = 0x54, .item3 = 0x2C, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  10,  // [$0A]
      .record = { .config = 0x02, .item0 = 0x5A, .item1 = 0x5B,
                  .item2 = 0x6B, .item3 = 0x6D, .item4 = 0x6E,
                  .item5 = 0x6F, .item6 = 0x86, .item7 = 0x87 } },
    { .shopIndex =  11,  // [$0B]
      .record = { .config = 0x04, .item0 = 0xE6, .item1 = 0xB4,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  12,  // [$0C]
      .record = { .config = 0x03, .item0 = 0xFE, .item1 = 0xE8,
                  .item2 = 0xE9, .item3 = 0xF3, .item4 = 0xF8,
                  .item5 = 0xF0, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =  13,  // [$0D]
      .record = { .config = 0x01, .item0 = 0x54, .item1 = 0x2C,
                  .item2 = 0x1D, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  14,  // [$0E]
      .record = { .config = 0x02, .item0 = 0x5B, .item1 = 0x6B,
                  .item2 = 0x6D, .item3 = 0x6E, .item4 = 0x6F,
                  .item5 = 0x86, .item6 = 0x88, .item7 = 0x87 } },
    { .shopIndex =  15,  // [$0F]
      .record = { .config = 0x03, .item0 = 0xE8, .item1 = 0xE9,
                  .item2 = 0xFB, .item3 = 0xFC, .item4 = 0xF8,
                  .item5 = 0xF0, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =  16,  // [$10]
      .record = { .config = 0x04, .item0 = 0xB0, .item1 = 0xB1,
                  .item2 = 0xB4, .item3 = 0xB6, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  17,  // [$11]
      .record = { .config = 0x01, .item0 = 0x03, .item1 = 0x44,
                  .item2 = 0x45, .item3 = 0x41, .item4 = 0xAB,
                  .item5 = 0xAC, .item6 = 0xAD, .item7 = 0xAE } },
    { .shopIndex =  18,  // [$12]
      .record = { .config = 0x02, .item0 = 0x5C, .item1 = 0x6D,
                  .item2 = 0x6E, .item3 = 0x73, .item4 = 0x6F,
                  .item5 = 0x88, .item6 = 0x87, .item7 = 0xFF } },
    { .shopIndex =  19,  // [$13]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF1, .item3 = 0xF2, .item4 = 0xF8,
                  .item5 = 0xF0, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =  20,  // [$14]
      .record = { .config = 0x01, .item0 = 0x2D, .item1 = 0x55,
                  .item2 = 0x26, .item3 = 0x45, .item4 = 0xAB,
                  .item5 = 0xAC, .item6 = 0xAD, .item7 = 0xAF } },
    { .shopIndex =  21,  // [$15]
      .record = { .config = 0x02, .item0 = 0x5C, .item1 = 0x73,
                  .item2 = 0x89, .item3 = 0x8A, .item4 = 0x8B,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  22,  // [$16]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF2, .item3 = 0xF4, .item4 = 0xF1,
                  .item5 = 0xF0, .item6 = 0xFB, .item7 = 0xF7 } },
    { .shopIndex =  23,  // [$17]
      .record = { .config = 0x04, .item0 = 0xB2, .item1 = 0xB7,
                  .item2 = 0xB8, .item3 = 0xC3, .item4 = 0xBE,
                  .item5 = 0xE3, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  24,  // [$18]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF3, .item3 = 0xF5, .item4 = 0xF1,
                  .item5 = 0xF0, .item6 = 0xF7, .item7 = 0xFD } },
    { .shopIndex =  25,  // [$19]
      .record = { .config = 0x01, .item0 = 0x2D, .item1 = 0x56,
                  .item2 = 0x10, .item3 = 0x27, .item4 = 0x41,
                  .item5 = 0xAB, .item6 = 0xAC, .item7 = 0xAD } },
    { .shopIndex =  26,  // [$1A]
      .record = { .config = 0x02, .item0 = 0x73, .item1 = 0x71,
                  .item2 = 0x89, .item3 = 0x8A, .item4 = 0x8B,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  27,  // [$1B]
      .record = { .config = 0x01, .item0 = 0x2D, .item1 = 0x56,
                  .item2 = 0x10, .item3 = 0x27, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  28,  // [$1C]
      .record = { .config = 0x02, .item0 = 0x73, .item1 = 0x71,
                  .item2 = 0x89, .item3 = 0x8A, .item4 = 0x8B,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  29,  // [$1D]
      .record = { .config = 0x01, .item0 = 0x03, .item1 = 0x45,
                  .item2 = 0x10, .item3 = 0x47, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  30,  // [$1E]
      .record = { .config = 0x02, .item0 = 0x71, .item1 = 0x74,
                  .item2 = 0x89, .item3 = 0x8A, .item4 = 0x8B,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  31,  // [$1F]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF3, .item3 = 0xF8, .item4 = 0xFB,
                  .item5 = 0xF1, .item6 = 0xF0, .item7 = 0xF7 } },
    { .shopIndex =  32,  // [$20]
      .record = { .config = 0x04, .item0 = 0xC3, .item1 = 0xBA,
                  .item2 = 0xD5, .item3 = 0xB3, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  33,  // [$21]
      .record = { .config = 0x01, .item0 = 0x34, .item1 = 0x35,
                  .item2 = 0x36, .item3 = 0x37, .item4 = 0x46,
                  .item5 = 0x49, .item6 = 0x1F, .item7 = 0x4E } },
    { .shopIndex =  34,  // [$22]
      .record = { .config = 0x02, .item0 = 0x5D, .item1 = 0x77,
                  .item2 = 0x75, .item3 = 0x76, .item4 = 0x79,
                  .item5 = 0x90, .item6 = 0x8D, .item7 = 0x8F } },
    { .shopIndex =  35,  // [$23]
      .record = { .config = 0x03, .item0 = 0xE8, .item1 = 0xE9,
                  .item2 = 0xEB, .item3 = 0xF5, .item4 = 0xFD,
                  .item5 = 0xF1, .item6 = 0xF0, .item7 = 0xF7 } },
    { .shopIndex =  36,  // [$24]
      .record = { .config = 0x03, .item0 = 0xF3, .item1 = 0xE8,
                  .item2 = 0xE9, .item3 = 0xEB, .item4 = 0xFB,
                  .item5 = 0xF6, .item6 = 0xF7, .item7 = 0xE6 } },
    { .shopIndex =  37,  // [$25]
      .record = { .config = 0x01, .item0 = 0x1D, .item1 = 0x1E,
                  .item2 = 0x56, .item3 = 0x10, .item4 = 0x47,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  38,  // [$26]
      .record = { .config = 0x02, .item0 = 0x71, .item1 = 0x72,
                  .item2 = 0x74, .item3 = 0x89, .item4 = 0x8C,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  39,  // [$27]
      .record = { .config = 0x05, .item0 = 0xE8, .item1 = 0xF0,
                  .item2 = 0xF7, .item3 = 0x6B, .item4 = 0x41,
                  .item5 = 0xAE, .item6 = 0xAF, .item7 = 0xE6 } },
    { .shopIndex =  40,  // [$28]
      .record = { .config = 0x04, .item0 = 0xB0, .item1 = 0xB2,
                  .item2 = 0xC3, .item3 = 0xE3, .item4 = 0xBB,
                  .item5 = 0xB3, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  41,  // [$29]
      .record = { .config = 0x01, .item0 = 0x38, .item1 = 0x1E,
                  .item2 = 0x47, .item3 = 0x46, .item4 = 0x49,
                  .item5 = 0x27, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  42,  // [$2A]
      .record = { .config = 0x02, .item0 = 0x5D, .item1 = 0x71,
                  .item2 = 0x72, .item3 = 0x74, .item4 = 0x75,
                  .item5 = 0x76, .item6 = 0x8C, .item7 = 0x90 } },
    { .shopIndex =  43,  // [$2B]
      .record = { .config = 0x04, .item0 = 0xC3, .item1 = 0xE3,
                  .item2 = 0xBA, .item3 = 0xBB, .item4 = 0xD5,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  44,  // [$2C]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF0, .item3 = 0xF8, .item4 = 0xF7,
                  .item5 = 0xAB, .item6 = 0xAC, .item7 = 0xAD } },
    { .shopIndex =  45,  // [$2D]
      .record = { .config = 0x04, .item0 = 0xC3, .item1 = 0xE3,
                  .item2 = 0xBA, .item3 = 0xBB, .item4 = 0xD5,
                  .item5 = 0xBF, .item6 = 0xE6, .item7 = 0xFF } },
    { .shopIndex =  46,  // [$2E]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF1, .item3 = 0xF0, .item4 = 0xF5,
                  .item5 = 0xFC, .item6 = 0xFD, .item7 = 0xF7 } },
    { .shopIndex =  47,  // [$2F]
      .record = { .config = 0x33, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF0, .item3 = 0xF1, .item4 = 0xF2,
                  .item5 = 0xF3, .item6 = 0xF4, .item7 = 0xF7 } },
    { .shopIndex =  48,  // [$30]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF0, .item3 = 0xF1, .item4 = 0xF5,
                  .item5 = 0xF6, .item6 = 0xFC, .item7 = 0xFD } },
    { .shopIndex =  49,  // [$31]
      .record = { .config = 0x01, .item0 = 0x0D, .item1 = 0x0E,
                  .item2 = 0x0F, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  50,  // [$32]
      .record = { .config = 0x02, .item0 = 0x5D, .item1 = 0x71,
                  .item2 = 0x72, .item3 = 0x76, .item4 = 0x8F,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  51,  // [$33]
      .record = { .config = 0x04, .item0 = 0xE6, .item1 = 0xC4,
                  .item2 = 0xC3, .item3 = 0xB7, .item4 = 0xB8,
                  .item5 = 0xBE, .item6 = 0xBB, .item7 = 0xB5 } },
    { .shopIndex =  52,  // [$34]
      .record = { .config = 0x01, .item0 = 0x55, .item1 = 0x56,
                  .item2 = 0x0D, .item3 = 0x0E, .item4 = 0x0F,
                  .item5 = 0x57, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  53,  // [$35]
      .record = { .config = 0x02, .item0 = 0x5D, .item1 = 0x6C,
                  .item2 = 0x77, .item3 = 0x76, .item4 = 0x90,
                  .item5 = 0x8F, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  54,  // [$36]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF8, .item3 = 0xF0, .item4 = 0xFB,
                  .item5 = 0xF1, .item6 = 0xF6, .item7 = 0xFA } },
    { .shopIndex =  55,  // [$37]
      .record = { .config = 0x04, .item0 = 0xBF, .item1 = 0xC7,
                  .item2 = 0xD5, .item3 = 0xE1, .item4 = 0xE3,
                  .item5 = 0xB2, .item6 = 0xB5, .item7 = 0xB3 } },
    { .shopIndex =  56,  // [$38]
      .record = { .config = 0x01, .item0 = 0x0C, .item1 = 0x0D,
                  .item2 = 0x0E, .item3 = 0x0F, .item4 = 0x13,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  57,  // [$39]
      .record = { .config = 0x02, .item0 = 0x5F, .item1 = 0x71,
                  .item2 = 0x72, .item3 = 0x7C, .item4 = 0x8D,
                  .item5 = 0x90, .item6 = 0x92, .item7 = 0xFF } },
    { .shopIndex =  58,  // [$3A]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF4, .item3 = 0xF0, .item4 = 0xF1,
                  .item5 = 0xF5, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =  59,  // [$3B]
      .record = { .config = 0x04, .item0 = 0xB4, .item1 = 0xBD,
                  .item2 = 0xC0, .item3 = 0xE2, .item4 = 0xD2,
                  .item5 = 0xD4, .item6 = 0xB3, .item7 = 0xC1 } },
    { .shopIndex =  60,  // [$3C]
      .record = { .config = 0x31, .item0 = 0x1E, .item1 = 0x1F,
                  .item2 = 0x13, .item3 = 0x22, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  61,  // [$3D]
      .record = { .config = 0x32, .item0 = 0x5F, .item1 = 0x71,
                  .item2 = 0x72, .item3 = 0x7C, .item4 = 0x8D,
                  .item5 = 0x92, .item6 = 0x95, .item7 = 0xFF } },
    { .shopIndex =  62,  // [$3E]
      .record = { .config = 0x34, .item0 = 0xB0, .item1 = 0xB1,
                  .item2 = 0xB6, .item3 = 0xB3, .item4 = 0xBA,
                  .item5 = 0xBB, .item6 = 0xBD, .item7 = 0xC1 } },
    { .shopIndex =  63,  // [$3F]
      .record = { .config = 0x33, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF3, .item3 = 0xFB, .item4 = 0xF0,
                  .item5 = 0xF1, .item6 = 0xF5, .item7 = 0xF7 } },
    { .shopIndex =  64,  // [$40]
      .record = { .config = 0x33, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF2, .item3 = 0xF3, .item4 = 0xFB,
                  .item5 = 0xF0, .item6 = 0xF5, .item7 = 0xF7 } },
    { .shopIndex =  65,  // [$41]
      .record = { .config = 0x01, .item0 = 0x4E, .item1 = 0x51,
                  .item2 = 0x50, .item3 = 0x13, .item4 = 0x22,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  66,  // [$42]
      .record = { .config = 0x02, .item0 = 0x5F, .item1 = 0x71,
                  .item2 = 0x72, .item3 = 0x7C, .item4 = 0x92,
                  .item5 = 0x95, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  67,  // [$43]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF2, .item3 = 0xF0, .item4 = 0xF1,
                  .item5 = 0xF5, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =  68,  // [$44]
      .record = { .config = 0x01, .item0 = 0x00, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  69,  // [$45]
      .record = { .config = 0x02, .item0 = 0x00, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  70,  // [$46]
      .record = { .config = 0x04, .item0 = 0x00, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  71,  // [$47]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF0, .item3 = 0xF1, .item4 = 0xF5,
                  .item5 = 0xFB, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =  72,  // [$48]
      .record = { .config = 0x01, .item0 = 0x3E, .item1 = 0x3A,
                  .item2 = 0x39, .item3 = 0x50, .item4 = 0x22,
                  .item5 = 0x06, .item6 = 0x41, .item7 = 0x42 } },
    { .shopIndex =  73,  // [$49]
      .record = { .config = 0x02, .item0 = 0x79, .item1 = 0x7A,
                  .item2 = 0x7D, .item3 = 0x91, .item4 = 0x92,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  74,  // [$4A]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF0, .item3 = 0xF1, .item4 = 0xF5,
                  .item5 = 0xFC, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =  75,  // [$4B]
      .record = { .config = 0x04, .item0 = 0xB7, .item1 = 0xB6,
                  .item2 = 0xBB, .item3 = 0xB5, .item4 = 0xC1,
                  .item5 = 0xB9, .item6 = 0xB2, .item7 = 0xBD } },
    { .shopIndex =  76,  // [$4C]
      .record = { .config = 0x01, .item0 = 0x06, .item1 = 0x20,
                  .item2 = 0x14, .item3 = 0x4B, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  77,  // [$4D]
      .record = { .config = 0x02, .item0 = 0x7A, .item1 = 0x7D,
                  .item2 = 0x7E, .item3 = 0x96, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  78,  // [$4E]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF0, .item3 = 0xF1, .item4 = 0xF5,
                  .item5 = 0xFD, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =  79,  // [$4F]
      .record = { .config = 0x04, .item0 = 0xC1, .item1 = 0xB9,
                  .item2 = 0xC4, .item3 = 0xBC, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  80,  // [$50]
      .record = { .config = 0x01, .item0 = 0x3A, .item1 = 0x07,
                  .item2 = 0x15, .item3 = 0xAB, .item4 = 0xAC,
                  .item5 = 0xAD, .item6 = 0xAE, .item7 = 0xAF } },
    { .shopIndex =  81,  // [$51]
      .record = { .config = 0x02, .item0 = 0x63, .item1 = 0x7E,
                  .item2 = 0x7F, .item3 = 0x96, .item4 = 0x97,
                  .item5 = 0x98, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  82,  // [$52]
      .record = { .config = 0x33, .item0 = 0xAA, .item1 = 0xA3,
                  .item2 = 0xA4, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  83,  // [$53]
      .record = { .config = 0x33, .item0 = 0xAA, .item1 = 0xA3,
                  .item2 = 0xA4, .item3 = 0xA5, .item4 = 0xA8,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  84,  // [$54]
      .record = { .config = 0x33, .item0 = 0xAA, .item1 = 0xA3,
                  .item2 = 0xA4, .item3 = 0xA5, .item4 = 0xA7,
                  .item5 = 0xA8, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  85,  // [$55]
      .record = { .config = 0x03, .item0 = 0xE8, .item1 = 0xE9,
                  .item2 = 0xF2, .item3 = 0xF8, .item4 = 0xF0,
                  .item5 = 0xF6, .item6 = 0x41, .item7 = 0xFF } },
    { .shopIndex =  86,  // [$56]
      .record = { .config = 0x03, .item0 = 0xE9, .item1 = 0xEB,
                  .item2 = 0xF0, .item3 = 0xF1, .item4 = 0xF5,
                  .item5 = 0xFD, .item6 = 0xF6, .item7 = 0xF7 } },
    { .shopIndex =  87,  // [$57]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  88,  // [$58]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  89,  // [$59]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  90,  // [$5A]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  91,  // [$5B]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  92,  // [$5C]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  93,  // [$5D]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  94,  // [$5E]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  95,  // [$5F]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  96,  // [$60]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  97,  // [$61]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  98,  // [$62]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex =  99,  // [$63]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 100,  // [$64]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 101,  // [$65]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 102,  // [$66]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 103,  // [$67]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 104,  // [$68]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 105,  // [$69]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 106,  // [$6A]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 107,  // [$6B]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 108,  // [$6C]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 109,  // [$6D]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 110,  // [$6E]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 111,  // [$6F]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 112,  // [$70]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 113,  // [$71]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 114,  // [$72]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 115,  // [$73]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 116,  // [$74]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 117,  // [$75]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 118,  // [$76]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 119,  // [$77]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 120,  // [$78]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 121,  // [$79]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 122,  // [$7A]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 123,  // [$7B]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 124,  // [$7C]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 125,  // [$7D]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 126,  // [$7E]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
    { .shopIndex = 127,  // [$7F]
      .record = { .config = 0x00, .item0 = 0xFF, .item1 = 0xFF,
                  .item2 = 0xFF, .item3 = 0xFF, .item4 = 0xFF,
                  .item5 = 0xFF, .item6 = 0xFF, .item7 = 0xFF } },
}};

}  // namespace ostinato::test
