// AUTO-GENERATED by tools/asm_parser/parse_text_meta.py
// Source: original-src/include/text/*_en.inc (ARRAY_LENGTH / ITEM_SIZE /
//         offset-symbol counts) + the DTE char-table format.
// (original-src pinned at 1ea47b5)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_text_meta.py \
//       --source-root  original-src \
//       --inc-out      src/data/generated/text_metadata_data.inc \
//       --fixture-out  tests/fixtures/text_metadata_expected.h

// Test fixture for tests/test_text_metadata.cpp — the
// ground-truth copy of the metadata table (.id decimal identity,
// .kind 0=FIXED/1=POINTER, decimal count/size). The full-corpus
// test asserts kTextClassMetadata matches this array entry by
// entry, so a hand edit or re-emit drift in either file fails.

#pragma once

#include <array>
#include <cstdint>

namespace ostinato::test {

// Mirrors ostinato::TextClassMetadata (src/data/text_metadata.h)
// without depending on it. kind: 0 = FIXED, 1 = POINTER.
struct ExpectedTextClassMetadata {
    std::uint8_t id;
    std::uint8_t kind;
    std::uint16_t recordCount;
    std::uint8_t recordSize;
};

inline constexpr std::array<ExpectedTextClassMetadata, 30>
kExpectedTextClassMetadata = {{  // FF6 text-class structure
    { .id =  0, .kind = 0, .recordCount =   64, .recordSize = 6 },
    { .id =  1, .kind = 0, .recordCount =  256, .recordSize = 13 },
    { .id =  2, .kind = 0, .recordCount =   54, .recordSize = 7 },
    { .id =  3, .kind = 0, .recordCount =  175, .recordSize = 10 },
    { .id =  4, .kind = 0, .recordCount =  384, .recordSize = 10 },
    { .id =  5, .kind = 0, .recordCount =  384, .recordSize = 10 },
    { .id =  6, .kind = 0, .recordCount =   32, .recordSize = 10 },
    { .id =  7, .kind = 0, .recordCount =   27, .recordSize = 8 },
    { .id =  8, .kind = 0, .recordCount =   27, .recordSize = 10 },
    { .id =  9, .kind = 0, .recordCount =   17, .recordSize = 9 },
    { .id = 10, .kind = 0, .recordCount =    8, .recordSize = 12 },
    { .id = 11, .kind = 0, .recordCount =    8, .recordSize = 12 },
    { .id = 12, .kind = 0, .recordCount =   32, .recordSize = 7 },
    { .id = 13, .kind = 0, .recordCount =   16, .recordSize = 7 },
    { .id = 14, .kind = 0, .recordCount =   20, .recordSize = 13 },
    { .id = 15, .kind = 1, .recordCount = 1574, .recordSize = 0 },
    { .id = 16, .kind = 1, .recordCount = 1510, .recordSize = 0 },
    { .id = 17, .kind = 1, .recordCount =  256, .recordSize = 0 },
    { .id = 18, .kind = 1, .recordCount =  256, .recordSize = 0 },
    { .id = 19, .kind = 1, .recordCount =  256, .recordSize = 0 },
    { .id = 20, .kind = 1, .recordCount =   73, .recordSize = 0 },
    { .id = 21, .kind = 1, .recordCount =  256, .recordSize = 0 },
    { .id = 22, .kind = 1, .recordCount =   54, .recordSize = 0 },
    { .id = 23, .kind = 1, .recordCount =   24, .recordSize = 0 },
    { .id = 24, .kind = 1, .recordCount =    8, .recordSize = 0 },
    { .id = 25, .kind = 1, .recordCount =    8, .recordSize = 0 },
    { .id = 26, .kind = 1, .recordCount =   32, .recordSize = 0 },
    { .id = 27, .kind = 1, .recordCount =   24, .recordSize = 0 },
    { .id = 28, .kind = 1, .recordCount =   20, .recordSize = 0 },
    { .id = 29, .kind = 0, .recordCount =  128, .recordSize = 2 },
}};

}  // namespace ostinato::test
