// AUTO-GENERATED by tools/asm_parser/parse_world_anim.py
// Source: world/world_anim.asm (record structure)
// Source: world/sprite.asm (the frame-sequence tables)
// (original-src pinned at 1ea47b5; cross-checked against the cartridge)
// DO NOT EDIT BY HAND — regenerate via:
//   python3 tools/asm_parser/parse_world_anim.py \
//       --source-root original-src --repo-root .

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

// What the world animation frames are shaped like, and what the
// frame-sequence tables hold.
//
// Structure only. The sprite arrangements are cartridge content and
// are never written into this repository — a test that wants them
// reads the cartridge, the same way the game does.
namespace ostinato::test {

// The region holding the pointer table and the records behind it,
// as one extent.
inline constexpr std::uint32_t kExpectedWorldAnimRegionAt = 0xEE573E;
inline constexpr std::size_t kExpectedWorldAnimRegionSize = 5294;
inline constexpr std::size_t kExpectedWorldAnimPointerBytes = 216;
inline constexpr std::size_t kExpectedWorldAnimBlockBytes = 5078;
inline constexpr std::size_t kExpectedWorldAnimFrameCount = 108;

// A record that stores more sprite rows than it declares: the frame,
// the count it declares, and the rows it actually holds. The extra
// rows are never drawn.
struct ExpectedSurplusFrame {
    std::uint8_t frame;
    std::uint8_t declaredSprites;
    std::uint8_t storedRows;
};

inline constexpr std::array<ExpectedSurplusFrame, 8>
kExpectedWorldAnimSurplusFrames = {{
    { .frame =  63, .declaredSprites = 2, .storedRows = 4 },
    { .frame =  64, .declaredSprites = 2, .storedRows = 4 },
    { .frame =  65, .declaredSprites = 2, .storedRows = 4 },
    { .frame =  66, .declaredSprites = 2, .storedRows = 4 },
    { .frame =  67, .declaredSprites = 2, .storedRows = 4 },
    { .frame =  68, .declaredSprites = 2, .storedRows = 4 },
    { .frame = 106, .declaredSprites = 4, .storedRows = 6 },
    { .frame = 107, .declaredSprites = 4, .storedRows = 6 },
}};

// One step of a frame-sequence table: the step, and the frame
// shown at it. Identity is a field, never a position.
struct ExpectedWorldAnimFrameStep {
    std::uint16_t index;
    std::uint8_t  frame;
};

// The frames _ee4de3 steps through.
inline constexpr std::array<ExpectedWorldAnimFrameStep, 5>
kExpectedWorldAnimDismountChocoboFrames = {{
    { .index = 0, .frame =  73 },
    { .index = 1, .frame =  74 },
    { .index = 2, .frame =  73 },
    { .index = 3, .frame =  75 },
    { .index = 4, .frame =  76 },
}};

// The frames _ee5196 steps through.
inline constexpr std::array<ExpectedWorldAnimFrameStep, 43>
kExpectedWorldAnimSmokingAirshipFrames = {{
    { .index =  0, .frame =   0 },
    { .index =  1, .frame =   0 },
    { .index =  2, .frame =   0 },
    { .index =  3, .frame =   0 },
    { .index =  4, .frame =   0 },
    { .index =  5, .frame =   0 },
    { .index =  6, .frame =   0 },
    { .index =  7, .frame =  86 },
    { .index =  8, .frame =  86 },
    { .index =  9, .frame =  86 },
    { .index = 10, .frame =  86 },
    { .index = 11, .frame =  86 },
    { .index = 12, .frame =   0 },
    { .index = 13, .frame =  87 },
    { .index = 14, .frame =  87 },
    { .index = 15, .frame =  86 },
    { .index = 16, .frame =  86 },
    { .index = 17, .frame =  86 },
    { .index = 18, .frame =   0 },
    { .index = 19, .frame =  89 },
    { .index = 20, .frame =  88 },
    { .index = 21, .frame =  87 },
    { .index = 22, .frame =  86 },
    { .index = 23, .frame =  86 },
    { .index = 24, .frame =   0 },
    { .index = 25, .frame =  88 },
    { .index = 26, .frame =  87 },
    { .index = 27, .frame =  87 },
    { .index = 28, .frame =  86 },
    { .index = 29, .frame =  86 },
    { .index = 30, .frame =   0 },
    { .index = 31, .frame =  87 },
    { .index = 32, .frame =  87 },
    { .index = 33, .frame =  86 },
    { .index = 34, .frame =  86 },
    { .index = 35, .frame =  86 },
    { .index = 36, .frame =   0 },
    { .index = 37, .frame =  87 },
    { .index = 38, .frame =  86 },
    { .index = 39, .frame =  86 },
    { .index = 40, .frame =  86 },
    { .index = 41, .frame =  86 },
    { .index = 42, .frame =   0 },
}};

// The frames _ee5350 steps through.
inline constexpr std::array<ExpectedWorldAnimFrameStep, 4>
kExpectedWorldAnimBirdFrames = {{
    { .index = 0, .frame =  95 },
    { .index = 1, .frame =  96 },
    { .index = 2, .frame =  97 },
    { .index = 3, .frame =  96 },
}};

// Where the smoking-airship table's second label sits, and how
// wide one altitude row is.
inline constexpr std::size_t kExpectedSmokingAirshipSecondLabelAt = 18;
inline constexpr std::size_t kExpectedSmokingAirshipRowStride = 6;

}  // namespace ostinato::test
